@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ParseUtil.PreallocatedException\n<size:10>elki.utilities.io" as elki.utilities.io.ParseUtil.PreallocatedException [[ParseUtil.PreallocatedException.html]] {
        {static} -serialVersionUID: long
        +PreallocatedException(String)
        +fillInStackTrace(): Throwable
    }

    class "<size:14>NumberFormatException\n<size:10>java.lang" as java.lang.NumberFormatException
    class "<size:14>ParseUtil\n<size:10>elki.utilities.io" as elki.utilities.io.ParseUtil [[ParseUtil.html]]

    java.lang.NumberFormatException <|-- elki.utilities.io.ParseUtil.PreallocatedException
    elki.utilities.io.ParseUtil +-- elki.utilities.io.ParseUtil.PreallocatedException

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
