@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>InMemoryIDistanceIndex.Factory\n<size:10>elki.index.idistance" as elki.index.idistance.InMemoryIDistanceIndex.Factory<V> [[InMemoryIDistanceIndex.Factory.html]] {
        ~distance: Distance<? super V>
        ~initialization: KMedoidsInitialization<V>
        ~k: int
        +Factory(Distance<? super V>, KMedoidsInitialization<V>, int)
        +instantiate(Relation<V>): InMemoryIDistanceIndex<V>
        +getInputTypeRestriction(): TypeInformation
    }

    interface "<size:14>IndexFactory\n<size:10>elki.index" as elki.index.IndexFactory<V> [[../IndexFactory.html]] {
        {abstract} +instantiate(Relation<V>): Index
        {abstract} +getInputTypeRestriction(): TypeInformation
    }
    class "<size:14>InMemoryIDistanceIndex\n<size:10>elki.index.idistance" as elki.index.idistance.InMemoryIDistanceIndex<O> [[InMemoryIDistanceIndex.html]]
    class "<size:14>InMemoryIDistanceIndex.Factory.Par\n<size:10>elki.index.idistance" as elki.index.idistance.InMemoryIDistanceIndex.Factory.Par<V>

    elki.index.IndexFactory <|.. elki.index.idistance.InMemoryIDistanceIndex.Factory
    elki.index.idistance.InMemoryIDistanceIndex +-- elki.index.idistance.InMemoryIDistanceIndex.Factory
    elki.index.idistance.InMemoryIDistanceIndex.Factory +-- elki.index.idistance.InMemoryIDistanceIndex.Factory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
