@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>TooltipStringVisualization\n<size:10>elki.visualization.visualizers.scatterplot" as elki.visualization.visualizers.scatterplot.TooltipStringVisualization [[TooltipStringVisualization.html]] {
        {static} +NAME_ID: String
        {static} +NAME_LABEL: String
        {static} +NAME_CLASS: String
        {static} +NAME_EID: String
        +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
        +processNewResult(VisualizerContext, Object): void
        -addTooltips(String, Relation<?>, VisualizerContext, Relation<?>, ScatterPlotProjector<?>): void
    }

    interface "<size:14>VisFactory\n<size:10>elki.visualization.visualizers" as elki.visualization.visualizers.VisFactory [[../VisFactory.html]] {
        {abstract} +processNewResult(VisualizerContext, Object): void
        {abstract} +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
    }
    class "<size:14>TooltipStringVisualization.Instance\n<size:10>elki.visualization.visualizers.scatterplot" as elki.visualization.visualizers.scatterplot.TooltipStringVisualization.Instance [[TooltipStringVisualization.Instance.html]]

    elki.visualization.visualizers.VisFactory <|.. elki.visualization.visualizers.scatterplot.TooltipStringVisualization
    elki.visualization.visualizers.scatterplot.TooltipStringVisualization +-- elki.visualization.visualizers.scatterplot.TooltipStringVisualization.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
