@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PeanoSpatialSorter\n<size:10>elki.math.spacefillingcurves" as elki.math.spacefillingcurves.PeanoSpatialSorter [[PeanoSpatialSorter.html]] {
        {static} +STATIC: PeanoSpatialSorter
        +sort(List<? extends SpatialComparable>, int, int, double[], int[]): void
        #peanoSort(List<? extends SpatialComparable>, int, int, double[], int[], int, long[], boolean): void
    }

    interface "<size:14>SpatialSorter\n<size:10>elki.math.spacefillingcurves" as elki.math.spacefillingcurves.SpatialSorter [[SpatialSorter.html]] {
        {abstract} +sort(List<? extends SpatialComparable>, int, int, double[], int[]): void
    }
    class "<size:14>PeanoSpatialSorter.Par\n<size:10>elki.math.spacefillingcurves" as elki.math.spacefillingcurves.PeanoSpatialSorter.Par [[PeanoSpatialSorter.Par.html]]

    elki.math.spacefillingcurves.SpatialSorter <|.. elki.math.spacefillingcurves.PeanoSpatialSorter
    elki.math.spacefillingcurves.PeanoSpatialSorter +-- elki.math.spacefillingcurves.PeanoSpatialSorter.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
