@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>SpatialSorter\n<size:10>elki.math.spacefillingcurves" as elki.math.spacefillingcurves.SpatialSorter [[SpatialSorter.html]] {
        +sort(List<? extends SpatialComparable>): void
        {abstract} +sort(List<? extends SpatialComparable>, int, int, double[], int[]): void
        {static} +computeMinMax(Iterable<? extends SpatialComparable>): double[]
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
