@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>OpenGL3DParallelCoordinates.Instance.Shared\n<size:10>elki.visualization.parallel3d" as elki.visualization.parallel3d.OpenGL3DParallelCoordinates.Instance.Shared<O> [[OpenGL3DParallelCoordinates.Instance.Shared.html]] {
        ~dim: int
        ~rel: Relation<? extends O>
        ~labels: String[]
        ~proj: ProjectionParallel
        ~stylepol: StylingPolicy
        ~stylelib: StyleLibrary
        ~layout: Layout
        ~settings: Settings<O>
        ~camera: Simple1DOFCamera
        ~textrenderer: TextRenderer
        ~mat: double[]
    }

    class "<size:14>OpenGL3DParallelCoordinates.Instance\n<size:10>elki.visualization.parallel3d" as elki.visualization.parallel3d.OpenGL3DParallelCoordinates.Instance<O extends NumberVector> [[OpenGL3DParallelCoordinates.Instance.html]]

    elki.visualization.parallel3d.OpenGL3DParallelCoordinates.Instance +-- elki.visualization.parallel3d.OpenGL3DParallelCoordinates.Instance.Shared

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
