@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CFTree\n<size:10>elki.clustering.hierarchical.birch" as elki.clustering.hierarchical.birch.CFTree [[CFTree.html]] {
        {static} +LOG: Logging
        ~distance: BIRCHDistance
        ~absorption: BIRCHAbsorptionCriterion
        ~thresholdsq: double
        ~capacity: int
        ~root: TreeNode
        ~leaves: int
        +CFTree(BIRCHDistance, BIRCHAbsorptionCriterion, double, int)
        +insert(NumberVector): void
        #rebuildTree(): void
        -estimateThreshold(TreeNode): double
        -insert(TreeNode, NumberVector): TreeNode
        +findLeaf(NumberVector): ClusteringFeature
        -findLeaf(TreeNode, NumberVector): ClusteringFeature
        -split(TreeNode, ClusteringFeature): TreeNode
        -insert(TreeNode, ClusteringFeature): TreeNode
        -add(ClusteringFeature[], ClusteringFeature): boolean
        +leafIterator(): LeafIterator
        #printDebug(StringBuilder, ClusteringFeature, int): StringBuilder
    }
    class "<size:14>CFTree.LeafIterator\n<size:10>elki.clustering.hierarchical.birch" as elki.clustering.hierarchical.birch.CFTree.LeafIterator [[CFTree.LeafIterator.html]]
    class "<size:14>CFTree.TreeNode\n<size:10>elki.clustering.hierarchical.birch" as elki.clustering.hierarchical.birch.CFTree.TreeNode
    class "<size:14>CFTree.Factory\n<size:10>elki.clustering.hierarchical.birch" as elki.clustering.hierarchical.birch.CFTree.Factory [[CFTree.Factory.html]]

    elki.clustering.hierarchical.birch.CFTree +-- elki.clustering.hierarchical.birch.CFTree.LeafIterator
    elki.clustering.hierarchical.birch.CFTree +-- elki.clustering.hierarchical.birch.CFTree.TreeNode
    elki.clustering.hierarchical.birch.CFTree +-- elki.clustering.hierarchical.birch.CFTree.Factory

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
