@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Xoroshiro128NonThreadsafeRandom\n<size:10>elki.utilities.random" as elki.utilities.random.Xoroshiro128NonThreadsafeRandom [[Xoroshiro128NonThreadsafeRandom.html]] {
        {static} -serialVersionUID: long
        -s0: long
        -s1: long
        {static} ~BADBOUND: String
        +Xoroshiro128NonThreadsafeRandom()
        +Xoroshiro128NonThreadsafeRandom(long)
        +setSeed(long): void
        +nextLong(): long
        #next(int): int
        +nextInt(): int
        +nextDouble(): double
        +nextInt(int): int
    }

    class "<size:14>Random\n<size:10>java.util" as java.util.Random

    java.util.Random <|-- elki.utilities.random.Xoroshiro128NonThreadsafeRandom

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
