@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SimpleOutlierEnsemble\n<size:10>elki.outlier.meta" as elki.outlier.meta.SimpleOutlierEnsemble [[SimpleOutlierEnsemble.html]] {
        {static} -LOG: Logging
        -algorithms: List<? extends OutlierAlgorithm>
        -voting: EnsembleVoting
        +SimpleOutlierEnsemble(List<? extends OutlierAlgorithm>, EnsembleVoting)
        +getInputTypeRestriction(): TypeInformation[]
        +autorun(Database): OutlierResult
    }

    interface "<size:14>OutlierAlgorithm\n<size:10>elki.outlier" as elki.outlier.OutlierAlgorithm [[../OutlierAlgorithm.html]]
    class "<size:14>SimpleOutlierEnsemble.Par\n<size:10>elki.outlier.meta" as elki.outlier.meta.SimpleOutlierEnsemble.Par [[SimpleOutlierEnsemble.Par.html]]

    elki.outlier.OutlierAlgorithm <|.. elki.outlier.meta.SimpleOutlierEnsemble
    elki.outlier.meta.SimpleOutlierEnsemble +-- elki.outlier.meta.SimpleOutlierEnsemble.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
