@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>BoundedMidpointSplit.Par\n<size:10>elki.index.tree.spatial.kd.split" as elki.index.tree.spatial.kd.split.BoundedMidpointSplit.Par [[BoundedMidpointSplit.Par.html]] {
        +make(): BoundedMidpointSplit
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>BoundedMidpointSplit\n<size:10>elki.index.tree.spatial.kd.split" as elki.index.tree.spatial.kd.split.BoundedMidpointSplit [[BoundedMidpointSplit.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.index.tree.spatial.kd.split.BoundedMidpointSplit.Par
    elki.index.tree.spatial.kd.split.BoundedMidpointSplit +-- elki.index.tree.spatial.kd.split.BoundedMidpointSplit.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
