@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LeastOneDimSSQSplit.Par\n<size:10>elki.index.tree.spatial.kd.split" as elki.index.tree.spatial.kd.split.LeastOneDimSSQSplit.Par [[LeastOneDimSSQSplit.Par.html]] {
        +make(): LeastOneDimSSQSplit
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>LeastOneDimSSQSplit\n<size:10>elki.index.tree.spatial.kd.split" as elki.index.tree.spatial.kd.split.LeastOneDimSSQSplit [[LeastOneDimSSQSplit.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.index.tree.spatial.kd.split.LeastOneDimSSQSplit.Par
    elki.index.tree.spatial.kd.split.LeastOneDimSSQSplit +-- elki.index.tree.spatial.kd.split.LeastOneDimSSQSplit.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
