@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LeastSSQSplit\n<size:10>elki.index.tree.spatial.kd.split" as elki.index.tree.spatial.kd.split.LeastSSQSplit [[LeastSSQSplit.html]] {
        {static} +STATIC: LeastSSQSplit
        +findSplit(Relation<? extends NumberVector>, int, ArrayModifiableDBIDs, DBIDArrayMIter, int, int, SortDBIDsBySingleDimension): Info
    }

    interface "<size:14>SplitStrategy\n<size:10>elki.index.tree.spatial.kd.split" as elki.index.tree.spatial.kd.split.SplitStrategy [[SplitStrategy.html]] {
        {abstract} +findSplit(Relation<? extends NumberVector>, int, ArrayModifiableDBIDs, DBIDArrayMIter, int, int, SortDBIDsBySingleDimension): Info
    }
    class "<size:14>LeastSSQSplit.Par\n<size:10>elki.index.tree.spatial.kd.split" as elki.index.tree.spatial.kd.split.LeastSSQSplit.Par [[LeastSSQSplit.Par.html]]

    elki.index.tree.spatial.kd.split.SplitStrategy <|.. elki.index.tree.spatial.kd.split.LeastSSQSplit
    elki.index.tree.spatial.kd.split.LeastSSQSplit +-- elki.index.tree.spatial.kd.split.LeastSSQSplit.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
