@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MinusLogScaling\n<size:10>elki.utilities.scaling" as elki.utilities.scaling.MinusLogScaling [[MinusLogScaling.html]] {
        +getScaled(double): double
        +getMin(): double
        +getMax(): double
    }

    interface "<size:14>StaticScalingFunction\n<size:10>elki.utilities.scaling" as elki.utilities.scaling.StaticScalingFunction [[StaticScalingFunction.html]]

    elki.utilities.scaling.StaticScalingFunction <|.. elki.utilities.scaling.MinusLogScaling

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
