@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>HilOut.ScoreType\n<size:10>elki.outlier.distance" as elki.outlier.distance.HilOut.ScoreType [[HilOut.ScoreType.html]] {
        {static} +ALL
        {static} +TOPN
    }

    class "<size:14>HilOut\n<size:10>elki.outlier.distance" as elki.outlier.distance.HilOut<O extends NumberVector> [[HilOut.html]]

    elki.outlier.distance.HilOut +-- elki.outlier.distance.HilOut.ScoreType

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
