@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>KNNDD.Par\n<size:10>elki.outlier.distance" as elki.outlier.distance.KNNDD.Par<O> [[KNNDD.Par.html]] {
        {static} +K_ID: OptionID
        #distance: Distance<? super O>
        #k: int
        +configure(Parameterization): void
        +make(): KNNDD<O>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>KNNDD\n<size:10>elki.outlier.distance" as elki.outlier.distance.KNNDD<O> [[KNNDD.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.outlier.distance.KNNDD.Par
    elki.outlier.distance.KNNDD +-- elki.outlier.distance.KNNDD.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
