@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>KNNSOS.Par\n<size:10>elki.outlier.distance" as elki.outlier.distance.KNNSOS.Par<O> {
        {static} +KNN_ID: OptionID
        #distance: Distance<? super O>
        #k: int
        +configure(Parameterization): void
        +make(): KNNSOS<O>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>KNNSOS\n<size:10>elki.outlier.distance" as elki.outlier.distance.KNNSOS<O> [[KNNSOS.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.outlier.distance.KNNSOS.Par
    elki.outlier.distance.KNNSOS +-- elki.outlier.distance.KNNSOS.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
