@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ReinsertStrategy\n<size:10>elki.index.tree.spatial.rstarvariants.strategies.reinsert" as elki.index.tree.spatial.rstarvariants.strategies.reinsert.ReinsertStrategy [[ReinsertStrategy.html]] {
        {abstract} +computeReinserts(A, ArrayAdapter<? extends SpatialComparable, ? super A>, SpatialComparable): int[]
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
