@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CompactCircularMSTLayout3DPC\n<size:10>elki.visualization.parallel3d.layout" as elki.visualization.parallel3d.layout.CompactCircularMSTLayout3DPC [[CompactCircularMSTLayout3DPC.html]] {
        +CompactCircularMSTLayout3DPC(Dependence)
        +layout(int, double[]): Layout
        -computeWeights(Node): void
        {static} +computePositions(Node, int, double, double, double, double): void
        ~makeNode(int, List<Node>): Node
    }

    abstract class "<size:14>AbstractLayout3DPC\n<size:10>elki.visualization.parallel3d.layout" as elki.visualization.parallel3d.layout.AbstractLayout3DPC<Node> [[AbstractLayout3DPC.html]] {
        {abstract} +layout(int, double[]): Layout
        {abstract} ~makeNode(int, List<N extends Node>): Node
    }
    class "<size:14>CompactCircularMSTLayout3DPC.Node\n<size:10>elki.visualization.parallel3d.layout" as elki.visualization.parallel3d.layout.CompactCircularMSTLayout3DPC.Node [[CompactCircularMSTLayout3DPC.Node.html]]
    class "<size:14>CompactCircularMSTLayout3DPC.Par\n<size:10>elki.visualization.parallel3d.layout" as elki.visualization.parallel3d.layout.CompactCircularMSTLayout3DPC.Par [[CompactCircularMSTLayout3DPC.Par.html]]

    elki.visualization.parallel3d.layout.AbstractLayout3DPC <|-- elki.visualization.parallel3d.layout.CompactCircularMSTLayout3DPC
    elki.visualization.parallel3d.layout.CompactCircularMSTLayout3DPC +-- elki.visualization.parallel3d.layout.CompactCircularMSTLayout3DPC.Node
    elki.visualization.parallel3d.layout.CompactCircularMSTLayout3DPC +-- elki.visualization.parallel3d.layout.CompactCircularMSTLayout3DPC.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
