@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ArrayIntegerStore\n<size:10>elki.database.datastore.memory" as elki.database.datastore.memory.ArrayIntegerStore [[ArrayIntegerStore.html]] {
        -data: int[]
        -idmap: DataStoreIDMap
        -def: int
        +ArrayIntegerStore(int, DataStoreIDMap)
        +ArrayIntegerStore(int, DataStoreIDMap, int)
        +--get--(DBIDRef): Integer
        +--put--(DBIDRef, Integer): Integer
        +intValue(DBIDRef): int
        +putInt(DBIDRef, int): int
        +put(DBIDRef, int): int
        +increment(DBIDRef, int): void
        +destroy(): void
        +delete(DBIDRef): void
        +clear(): void
    }

    interface "<size:14>WritableIntegerDataStore\n<size:10>elki.database.datastore" as elki.database.datastore.WritableIntegerDataStore [[../WritableIntegerDataStore.html]] {
        {abstract} +--put--(DBIDRef, Integer): Integer
        {abstract} +putInt(DBIDRef, int): int
        {abstract} +put(DBIDRef, int): int
        {abstract} +increment(DBIDRef, int): void
    }

    elki.database.datastore.WritableIntegerDataStore <|.. elki.database.datastore.memory.ArrayIntegerStore

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
