@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ArrayDBIDStore\n<size:10>elki.database.datastore.memory" as elki.database.datastore.memory.ArrayDBIDStore [[ArrayDBIDStore.html]] {
        -data: ArrayModifiableDBIDs
        -idmap: DataStoreIDMap
        +ArrayDBIDStore(int, DataStoreIDMap)
        +--get--(DBIDRef): DBID
        +assignVar(DBIDRef, DBIDVar): DBIDVar
        +--put--(DBIDRef, DBID): DBID
        +putDBID(DBIDRef, DBIDRef): void
        +put(DBIDRef, DBIDRef): void
        +destroy(): void
        +clear(): void
        +delete(DBIDRef): void
    }

    interface "<size:14>WritableDBIDDataStore\n<size:10>elki.database.datastore" as elki.database.datastore.WritableDBIDDataStore [[../WritableDBIDDataStore.html]] {
        {abstract} +--put--(DBIDRef, DBID): DBID
        {abstract} +putDBID(DBIDRef, DBIDRef): void
        {abstract} +put(DBIDRef, DBIDRef): void
    }

    elki.database.datastore.WritableDBIDDataStore <|.. elki.database.datastore.memory.ArrayDBIDStore

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
