@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>QuickSelect.Adapter\n<size:10>elki.utilities.datastructures" as elki.utilities.datastructures.QuickSelect.Adapter<T> [[QuickSelect.Adapter.html]] {
        {abstract} +swap(T, int, int): void
        {abstract} +compare(T, int, int): int
        +isSorted(T, int, int): void
    }

    class "<size:14>QuickSelect\n<size:10>elki.utilities.datastructures" as elki.utilities.datastructures.QuickSelect [[QuickSelect.html]]

    elki.utilities.datastructures.QuickSelect +-- elki.utilities.datastructures.QuickSelect.Adapter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
