@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SilhouettePlotProjector\n<size:10>elki.visualization.projector" as elki.visualization.projector.SilhouettePlotProjector [[SilhouettePlotProjector.html]] {
        -clustering: Clustering<?>
        -plot: SilhouettePlot
        -values: DoubleDBIDList[]
        +SilhouettePlotProjector(Clustering<?>, DoubleRelation)
        {static} -sortSilhouette(Clustering<?>, DoubleRelation): DoubleDBIDList[]
        +getMenuName(): String
        +arrange(VisualizerContext): Collection<PlotItem>
        +getSilhouettePlot(VisualizerContext): SilhouettePlot
        +getResult(): Clustering<?>
        +getValues(): DoubleDBIDList[]
    }

    interface "<size:14>Projector\n<size:10>elki.visualization.projector" as elki.visualization.projector.Projector [[Projector.html]] {
        {abstract} +arrange(VisualizerContext): Collection<PlotItem>
    }

    elki.visualization.projector.Projector <|.. elki.visualization.projector.SilhouettePlotProjector

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
