@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SilhouettePlotFactory\n<size:10>elki.visualization.projector" as elki.visualization.projector.SilhouettePlotFactory [[SilhouettePlotFactory.html]] {
        +processNewResult(VisualizerContext, Object): void
    }

    interface "<size:14>ProjectorFactory\n<size:10>elki.visualization.projector" as elki.visualization.projector.ProjectorFactory [[ProjectorFactory.html]] {
        {abstract} +processNewResult(VisualizerContext, Object): void
    }

    elki.visualization.projector.ProjectorFactory <|.. elki.visualization.projector.SilhouettePlotFactory

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
