@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MemoryKDTree.Factory\n<size:10>elki.index.tree.spatial.kd" as elki.index.tree.spatial.kd.MemoryKDTree.Factory<O extends NumberVector> [[MemoryKDTree.Factory.html]] {
        ~split: SplitStrategy
        ~leafsize: int
        +Factory(SplitStrategy, int)
        +instantiate(Relation<O extends NumberVector>): MemoryKDTree<O extends NumberVector>
        +getInputTypeRestriction(): TypeInformation
    }

    interface "<size:14>IndexFactory\n<size:10>elki.index" as elki.index.IndexFactory<O extends NumberVector> [[../../../IndexFactory.html]] {
        {abstract} +instantiate(Relation<V>): Index
        {abstract} +getInputTypeRestriction(): TypeInformation
    }
    class "<size:14>MemoryKDTree\n<size:10>elki.index.tree.spatial.kd" as elki.index.tree.spatial.kd.MemoryKDTree<O extends NumberVector> [[MemoryKDTree.html]]
    class "<size:14>MemoryKDTree.Factory.Par\n<size:10>elki.index.tree.spatial.kd" as elki.index.tree.spatial.kd.MemoryKDTree.Factory.Par<O extends NumberVector> [[MemoryKDTree.Factory.Par.html]]

    elki.index.IndexFactory <|.. elki.index.tree.spatial.kd.MemoryKDTree.Factory
    elki.index.tree.spatial.kd.MemoryKDTree +-- elki.index.tree.spatial.kd.MemoryKDTree.Factory
    elki.index.tree.spatial.kd.MemoryKDTree.Factory +-- elki.index.tree.spatial.kd.MemoryKDTree.Factory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
