@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MemoryKDTree.KDNode\n<size:10>elki.index.tree.spatial.kd" as elki.index.tree.spatial.kd.MemoryKDTree.KDNode [[MemoryKDTree.KDNode.html]] {
        ~split: double
        ~dim: int
        ~leftChild: Object
        ~rightChild: Object
        +KDNode(int, double, Object, Object)
    }

    class "<size:14>MemoryKDTree\n<size:10>elki.index.tree.spatial.kd" as elki.index.tree.spatial.kd.MemoryKDTree<O extends NumberVector> [[MemoryKDTree.html]]

    elki.index.tree.spatial.kd.MemoryKDTree +-- elki.index.tree.spatial.kd.MemoryKDTree.KDNode

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
