@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>InMemoryInvertedIndex.CosineKNNQuery\n<size:10>elki.index.invertedlist" as elki.index.invertedlist.InMemoryInvertedIndex.CosineKNNQuery [[InMemoryInvertedIndex.CosineKNNQuery.html]] {
        +getKNN(V extends NumberVector, int): KNNList
    }

    interface "<size:14>KNNSearcher\n<size:10>elki.database.query.knn" as elki.database.query.knn.KNNSearcher<V extends NumberVector> [[../../database/query/knn/KNNSearcher.html]] {
        {abstract} +getKNN(V extends NumberVector, int): KNNList
    }
    class "<size:14>InMemoryInvertedIndex\n<size:10>elki.index.invertedlist" as elki.index.invertedlist.InMemoryInvertedIndex<V extends NumberVector> [[InMemoryInvertedIndex.html]]

    elki.database.query.knn.KNNSearcher <|.. elki.index.invertedlist.InMemoryInvertedIndex.CosineKNNQuery
    elki.index.invertedlist.InMemoryInvertedIndex +-- elki.index.invertedlist.InMemoryInvertedIndex.CosineKNNQuery

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
