@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>SVDD.RadiusAcceptor\n<size:10>elki.svm" as elki.svm.SVDD.RadiusAcceptor [[SVDD.RadiusAcceptor.html]] {
        {abstract} +setRSquare(double): void
    }

    class "<size:14>SVDD\n<size:10>elki.svm" as elki.svm.SVDD [[SVDD.html]]

    elki.svm.SVDD +-- elki.svm.SVDD.RadiusAcceptor

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
