@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>Visualization\n<size:10>elki.visualization.visualizers" as elki.visualization.visualizers.Visualization [[Visualization.html]] {
        {abstract} +getLayer(): Element
        {abstract} +incrementalRedraw(): void
        {abstract} +fullRedraw(): void
        {abstract} +destroy(): void
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
