@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RelativeEigenPairFilter.Par\n<size:10>elki.math.linearalgebra.pca.filter" as elki.math.linearalgebra.pca.filter.RelativeEigenPairFilter.Par [[RelativeEigenPairFilter.Par.html]] {
        {static} +EIGENPAIR_FILTER_RALPHA: OptionID
        #ralpha: double
        +configure(Parameterization): void
        +make(): RelativeEigenPairFilter
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>RelativeEigenPairFilter\n<size:10>elki.math.linearalgebra.pca.filter" as elki.math.linearalgebra.pca.filter.RelativeEigenPairFilter [[RelativeEigenPairFilter.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.math.linearalgebra.pca.filter.RelativeEigenPairFilter.Par
    elki.math.linearalgebra.pca.filter.RelativeEigenPairFilter +-- elki.math.linearalgebra.pca.filter.RelativeEigenPairFilter.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
