@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SelectionTableWindow.DatabaseTableModel\n<size:10>elki.visualization.gui" as elki.visualization.gui.SelectionTableWindow.DatabaseTableModel [[SelectionTableWindow.DatabaseTableModel.html]] {
        {static} -serialVersionUID: long
        +getColumnCount(): int
        +getRowCount(): int
        +getValueAt(int, int): Object
        +getColumnName(int): String
        +isCellEditable(int, int): boolean
        +setValueAt(Object, int, int): void
    }

    abstract class "<size:14>AbstractTableModel\n<size:10>javax.swing.table" as javax.swing.table.AbstractTableModel
    class "<size:14>SelectionTableWindow\n<size:10>elki.visualization.gui" as elki.visualization.gui.SelectionTableWindow [[SelectionTableWindow.html]]

    javax.swing.table.AbstractTableModel <|-- elki.visualization.gui.SelectionTableWindow.DatabaseTableModel
    elki.visualization.gui.SelectionTableWindow +-- elki.visualization.gui.SelectionTableWindow.DatabaseTableModel

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
