@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SupportVectorClustering.Par\n<size:10>elki.clustering.svm" as elki.clustering.svm.SupportVectorClustering.Par {
        {static} +KERNEL_ID: OptionID
        {static} +C_ID: OptionID
        #kernel: PrimitiveSimilarity<? super NumberVector>
        #C: double
        +configure(Parameterization): void
        +make(): SupportVectorClustering
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>SupportVectorClustering\n<size:10>elki.clustering.svm" as elki.clustering.svm.SupportVectorClustering [[SupportVectorClustering.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.clustering.svm.SupportVectorClustering.Par
    elki.clustering.svm.SupportVectorClustering +-- elki.clustering.svm.SupportVectorClustering.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
