@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DeLiCluTreeIndex\n<size:10>elki.index.tree.spatial.rstarvariants.deliclu" as elki.index.tree.spatial.rstarvariants.deliclu.DeLiCluTreeIndex<O extends NumberVector> [[DeLiCluTreeIndex.html]] {
        -relation: Relation<O extends NumberVector>
        {static} -LOG: Logging
        +DeLiCluTreeIndex(Relation<O extends NumberVector>, PageFile<DeLiCluNode>, RTreeSettings)
        #createNewLeafEntry(DBID): DeLiCluLeafEntry
        +setHandled(DBIDRef, O extends NumberVector): IndexTreePath<DeLiCluEntry>
        +initialize(): void
        +insert(DBIDRef): void
        +insertAll(DBIDs): void
        +delete(DBIDRef): boolean
        +deleteAll(DBIDs): void
        +kNNByObject(DistanceQuery<O extends NumberVector>, int, int): KNNSearcher<O extends NumberVector>
        +rangeByObject(DistanceQuery<O extends NumberVector>, double, int): RangeSearcher<O extends NumberVector>
        +priorityByObject(DistanceQuery<O extends NumberVector>, double, int): PrioritySearcher<O extends NumberVector>
        #getLogger(): Logging
    }

    abstract class "<size:14>DeLiCluTree\n<size:10>elki.index.tree.spatial.rstarvariants.deliclu" as elki.index.tree.spatial.rstarvariants.deliclu.DeLiCluTree [[DeLiCluTree.html]]
    interface "<size:14>DistancePriorityIndex\n<size:10>elki.index" as elki.index.DistancePriorityIndex<O extends NumberVector> [[../../../../DistancePriorityIndex.html]] {
        {abstract} +priorityByObject(DistanceQuery<O>, double, int): PrioritySearcher<O>
    }
    interface "<size:14>DynamicIndex\n<size:10>elki.index" as elki.index.DynamicIndex [[../../../../DynamicIndex.html]] {
        {abstract} +delete(DBIDRef): boolean
        {abstract} +insert(DBIDRef): void
        {abstract} +deleteAll(DBIDs): void
        {abstract} +insertAll(DBIDs): void
    }

    elki.index.tree.spatial.rstarvariants.deliclu.DeLiCluTree <|-- elki.index.tree.spatial.rstarvariants.deliclu.DeLiCluTreeIndex
    elki.index.DistancePriorityIndex <|.. elki.index.tree.spatial.rstarvariants.deliclu.DeLiCluTreeIndex
    elki.index.DynamicIndex <|.. elki.index.tree.spatial.rstarvariants.deliclu.DeLiCluTreeIndex

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
