@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>PrimsMinimumSpanningTree.Collector\n<size:10>elki.math.geometry" as elki.math.geometry.PrimsMinimumSpanningTree.Collector [[PrimsMinimumSpanningTree.Collector.html]] {
        {abstract} +addEdge(double, int, int): void
    }

    class "<size:14>PrimsMinimumSpanningTree\n<size:10>elki.math.geometry" as elki.math.geometry.PrimsMinimumSpanningTree [[PrimsMinimumSpanningTree.html]]

    elki.math.geometry.PrimsMinimumSpanningTree +-- elki.math.geometry.PrimsMinimumSpanningTree.Collector

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
