@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PrimsMinimumSpanningTree.Array2DAdapter\n<size:10>elki.math.geometry" as elki.math.geometry.PrimsMinimumSpanningTree.Array2DAdapter [[PrimsMinimumSpanningTree.Array2DAdapter.html]] {
        +distance(double[], int, int): double
        +size(double[]): int
    }

    interface "<size:14>PrimsMinimumSpanningTree.Adapter\n<size:10>elki.math.geometry" as elki.math.geometry.PrimsMinimumSpanningTree.Adapter<double[]> [[PrimsMinimumSpanningTree.Adapter.html]] {
        {abstract} +distance(double[], int, int): double
        {abstract} +size(double[]): int
    }
    class "<size:14>PrimsMinimumSpanningTree\n<size:10>elki.math.geometry" as elki.math.geometry.PrimsMinimumSpanningTree [[PrimsMinimumSpanningTree.html]]

    elki.math.geometry.PrimsMinimumSpanningTree.Adapter <|.. elki.math.geometry.PrimsMinimumSpanningTree.Array2DAdapter
    elki.math.geometry.PrimsMinimumSpanningTree +-- elki.math.geometry.PrimsMinimumSpanningTree.Array2DAdapter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
