@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AlternateRefinement\n<size:10>elki.clustering.kmedoids.initialization" as elki.clustering.kmedoids.initialization.AlternateRefinement<O> [[AlternateRefinement.html]] {
        {static} -LOG: Logging
        -inner: KMedoidsInitialization<O>
        ~maxiter: int
        +AlternateRefinement(KMedoidsInitialization<O>, int)
        +chooseInitialMedoids(int, DBIDs, DistanceQuery<? super O>): DBIDs
        {static} +findMedoid(DBIDs, DistanceQuery<?>, IntegerDataStore, int, DBIDArrayMIter, double[]): boolean
        {static} +assignToNearestCluster(DBIDArrayIter, DBIDs, DistanceQuery<?>, WritableIntegerDataStore, double[]): double
    }

    interface "<size:14>KMedoidsInitialization\n<size:10>elki.clustering.kmedoids.initialization" as elki.clustering.kmedoids.initialization.KMedoidsInitialization<O> [[KMedoidsInitialization.html]] {
        {abstract} +chooseInitialMedoids(int, DBIDs, DistanceQuery<? super O>): DBIDs
    }
    class "<size:14>AlternateRefinement.Par\n<size:10>elki.clustering.kmedoids.initialization" as elki.clustering.kmedoids.initialization.AlternateRefinement.Par<O> [[AlternateRefinement.Par.html]]

    elki.clustering.kmedoids.initialization.KMedoidsInitialization <|.. elki.clustering.kmedoids.initialization.AlternateRefinement
    elki.clustering.kmedoids.initialization.AlternateRefinement +-- elki.clustering.kmedoids.initialization.AlternateRefinement.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
