@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DBSCANOutlierDetection.Par\n<size:10>elki.outlier.clustering" as elki.outlier.clustering.DBSCANOutlierDetection.Par [[DBSCANOutlierDetection.Par.html]] {
        #clusterer: GeneralizedDBSCAN
        +configure(Parameterization): void
        +make(): DBSCANOutlierDetection
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>DBSCANOutlierDetection\n<size:10>elki.outlier.clustering" as elki.outlier.clustering.DBSCANOutlierDetection [[DBSCANOutlierDetection.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.outlier.clustering.DBSCANOutlierDetection.Par
    elki.outlier.clustering.DBSCANOutlierDetection +-- elki.outlier.clustering.DBSCANOutlierDetection.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
