@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>KMeansMinusMinusOutlierDetection.Par\n<size:10>elki.outlier.clustering" as elki.outlier.clustering.KMeansMinusMinusOutlierDetection.Par [[KMeansMinusMinusOutlierDetection.Par.html]] {
        ~kmeansminusminus: KMeansMinusMinus<?>
        +configure(Parameterization): void
        +make(): KMeansMinusMinusOutlierDetection
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>KMeansMinusMinusOutlierDetection\n<size:10>elki.outlier.clustering" as elki.outlier.clustering.KMeansMinusMinusOutlierDetection [[KMeansMinusMinusOutlierDetection.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.outlier.clustering.KMeansMinusMinusOutlierDetection.Par
    elki.outlier.clustering.KMeansMinusMinusOutlierDetection +-- elki.outlier.clustering.KMeansMinusMinusOutlierDetection.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
