@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>KMeansOutlierDetection\n<size:10>elki.outlier.clustering" as elki.outlier.clustering.KMeansOutlierDetection<O extends NumberVector> [[KMeansOutlierDetection.html]] {
        {static} -LOG: Logging
        ~clusterer: KMeans<O extends NumberVector, ?>
        ~rule: Rule
        +KMeansOutlierDetection(KMeans<O extends NumberVector, ?>, Rule)
        +getInputTypeRestriction(): TypeInformation[]
        +run(Relation<O extends NumberVector>): OutlierResult
        -distanceScoring(Clustering<?>, Relation<O extends NumberVector>, NumberVectorDistance<? super NumberVector>, WritableDoubleDataStore, DoubleMinMax): void
        -singletonsScoring(Clustering<?>, Relation<O extends NumberVector>, NumberVectorDistance<? super NumberVector>, WritableDoubleDataStore, DoubleMinMax): void
        -varianceScoring(Clustering<?>, Relation<O extends NumberVector>, NumberVectorDistance<? super NumberVector>, WritableDoubleDataStore, DoubleMinMax): void
    }

    interface "<size:14>OutlierAlgorithm\n<size:10>elki.outlier" as elki.outlier.OutlierAlgorithm [[../OutlierAlgorithm.html]]
    enum "<size:14>KMeansOutlierDetection.Rule\n<size:10>elki.outlier.clustering" as elki.outlier.clustering.KMeansOutlierDetection.Rule [[KMeansOutlierDetection.Rule.html]]
    class "<size:14>KMeansOutlierDetection.Par\n<size:10>elki.outlier.clustering" as elki.outlier.clustering.KMeansOutlierDetection.Par<O extends NumberVector>

    elki.outlier.OutlierAlgorithm <|.. elki.outlier.clustering.KMeansOutlierDetection
    elki.outlier.clustering.KMeansOutlierDetection +-- elki.outlier.clustering.KMeansOutlierDetection.Rule
    elki.outlier.clustering.KMeansOutlierDetection +-- elki.outlier.clustering.KMeansOutlierDetection.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
