@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MiniGUI.SettingsComboboxModel\n<size:10>elki.gui.minigui" as elki.gui.minigui.MiniGUI.SettingsComboboxModel [[MiniGUI.SettingsComboboxModel.html]] {
        {static} -serialVersionUID: long
        #store: SavedSettingsFile
        #selected: String
        +SettingsComboboxModel(SavedSettingsFile)
        +getSelectedItem(): String
        +setSelectedItem(Object): void
        +getElementAt(int): String
        +getSize(): int
        +update(): void
    }

    abstract class "<size:14>AbstractListModel\n<size:10>javax.swing" as javax.swing.AbstractListModel<String>
    interface "<size:14>ComboBoxModel\n<size:10>javax.swing" as javax.swing.ComboBoxModel<String> {
        {abstract} +setSelectedItem(Object): void
        {abstract} +getSelectedItem(): Object
    }
    class "<size:14>MiniGUI\n<size:10>elki.gui.minigui" as elki.gui.minigui.MiniGUI [[MiniGUI.html]]

    javax.swing.AbstractListModel <|-- elki.gui.minigui.MiniGUI.SettingsComboboxModel
    javax.swing.ComboBoxModel <|.. elki.gui.minigui.MiniGUI.SettingsComboboxModel
    elki.gui.minigui.MiniGUI +-- elki.gui.minigui.MiniGUI.SettingsComboboxModel

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
