@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CauchyDistribution.Par\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.CauchyDistribution.Par [[CauchyDistribution.Par.html]] {
        {static} +SHAPE_ID: OptionID
        ~location: double
        ~shape: double
        +configure(Parameterization): void
        +make(): CauchyDistribution
    }

    interface "<size:14>Distribution.Parameterizer\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.Distribution.Parameterizer [[Distribution.Parameterizer.html]]
    class "<size:14>CauchyDistribution\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.CauchyDistribution [[CauchyDistribution.html]]

    elki.math.statistics.distribution.Distribution.Parameterizer <|.. elki.math.statistics.distribution.CauchyDistribution.Par
    elki.math.statistics.distribution.CauchyDistribution +-- elki.math.statistics.distribution.CauchyDistribution.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
