@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ExponentiallyModifiedGaussianDistribution.Par\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.ExponentiallyModifiedGaussianDistribution.Par [[ExponentiallyModifiedGaussianDistribution.Par.html]] {
        {static} +RATE_ID: OptionID
        ~mean: double
        ~stddev: double
        ~lambda: double
        +configure(Parameterization): void
        +make(): ExponentiallyModifiedGaussianDistribution
    }

    interface "<size:14>Distribution.Parameterizer\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.Distribution.Parameterizer [[Distribution.Parameterizer.html]]
    class "<size:14>ExponentiallyModifiedGaussianDistribution\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.ExponentiallyModifiedGaussianDistribution [[ExponentiallyModifiedGaussianDistribution.html]]

    elki.math.statistics.distribution.Distribution.Parameterizer <|.. elki.math.statistics.distribution.ExponentiallyModifiedGaussianDistribution.Par
    elki.math.statistics.distribution.ExponentiallyModifiedGaussianDistribution +-- elki.math.statistics.distribution.ExponentiallyModifiedGaussianDistribution.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
