@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>InverseGaussianDistribution.Par\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.InverseGaussianDistribution.Par [[InverseGaussianDistribution.Par.html]] {
        ~mean: double
        ~shape: double
        +configure(Parameterization): void
        +make(): InverseGaussianDistribution
    }

    interface "<size:14>Distribution.Parameterizer\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.Distribution.Parameterizer [[Distribution.Parameterizer.html]]
    class "<size:14>InverseGaussianDistribution\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.InverseGaussianDistribution [[InverseGaussianDistribution.html]]

    elki.math.statistics.distribution.Distribution.Parameterizer <|.. elki.math.statistics.distribution.InverseGaussianDistribution.Par
    elki.math.statistics.distribution.InverseGaussianDistribution +-- elki.math.statistics.distribution.InverseGaussianDistribution.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
