@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LogGammaDistribution.Par\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.LogGammaDistribution.Par [[LogGammaDistribution.Par.html]] {
        {static} +SHIFT_ID: OptionID
        ~k: double
        ~theta: double
        ~shift: double
        +configure(Parameterization): void
        +make(): LogGammaDistribution
    }

    interface "<size:14>Distribution.Parameterizer\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.Distribution.Parameterizer [[Distribution.Parameterizer.html]]
    class "<size:14>LogGammaDistribution\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.LogGammaDistribution [[LogGammaDistribution.html]]

    elki.math.statistics.distribution.Distribution.Parameterizer <|.. elki.math.statistics.distribution.LogGammaDistribution.Par
    elki.math.statistics.distribution.LogGammaDistribution +-- elki.math.statistics.distribution.LogGammaDistribution.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
