@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RayleighDistribution\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.RayleighDistribution [[RayleighDistribution.html]] {
        ~mu: double
        ~sigma: double
        +RayleighDistribution(double)
        +RayleighDistribution(double, double)
        +getMu(): double
        +getSigma(): double
        +pdf(double): double
        {static} +pdf(double, double): double
        +logpdf(double): double
        {static} +logpdf(double, double): double
        +cdf(double): double
        {static} +cdf(double, double): double
        +quantile(double): double
        {static} +quantile(double, double): double
        +nextRandom(Random): double
    }

    interface "<size:14>Distribution\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.Distribution [[Distribution.html]] {
        {abstract} +pdf(double): double
        {abstract} +logpdf(double): double
        {abstract} +cdf(double): double
        {abstract} +quantile(double): double
    }
    class "<size:14>RayleighDistribution.Par\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.RayleighDistribution.Par [[RayleighDistribution.Par.html]]

    elki.math.statistics.distribution.Distribution <|.. elki.math.statistics.distribution.RayleighDistribution
    elki.math.statistics.distribution.RayleighDistribution +-- elki.math.statistics.distribution.RayleighDistribution.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
