@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SkewGeneralizedNormalDistribution.Par\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.SkewGeneralizedNormalDistribution.Par [[SkewGeneralizedNormalDistribution.Par.html]] {
        {static} +SKEW_ID: OptionID
        ~mean: double
        ~sigma: double
        ~skew: double
        +configure(Parameterization): void
        +make(): SkewGeneralizedNormalDistribution
    }

    interface "<size:14>Distribution.Parameterizer\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.Distribution.Parameterizer [[Distribution.Parameterizer.html]]
    class "<size:14>SkewGeneralizedNormalDistribution\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.SkewGeneralizedNormalDistribution [[SkewGeneralizedNormalDistribution.html]]

    elki.math.statistics.distribution.Distribution.Parameterizer <|.. elki.math.statistics.distribution.SkewGeneralizedNormalDistribution.Par
    elki.math.statistics.distribution.SkewGeneralizedNormalDistribution +-- elki.math.statistics.distribution.SkewGeneralizedNormalDistribution.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
