@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>WeibullDistribution.Par\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.WeibullDistribution.Par [[WeibullDistribution.Par.html]] {
        ~theta: double
        ~k: double
        ~lambda: double
        +configure(Parameterization): void
        +make(): WeibullDistribution
    }

    interface "<size:14>Distribution.Parameterizer\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.Distribution.Parameterizer [[Distribution.Parameterizer.html]]
    class "<size:14>WeibullDistribution\n<size:10>elki.math.statistics.distribution" as elki.math.statistics.distribution.WeibullDistribution [[WeibullDistribution.html]]

    elki.math.statistics.distribution.Distribution.Parameterizer <|.. elki.math.statistics.distribution.WeibullDistribution.Par
    elki.math.statistics.distribution.WeibullDistribution +-- elki.math.statistics.distribution.WeibullDistribution.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
