@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DTWDistance\n<size:10>elki.distance.timeseries" as elki.distance.timeseries.DTWDistance [[DTWDistance.html]] {
        +DTWDistance()
        +DTWDistance(double)
        +distance(NumberVector, NumberVector): double
        #firstRow(double[], int, NumberVector, NumberVector, int): void
        #delta(double, double): double
    }

    abstract class "<size:14>AbstractEditDistance\n<size:10>elki.distance.timeseries" as elki.distance.timeseries.AbstractEditDistance [[AbstractEditDistance.html]]
    class "<size:14>DTWDistance.Par\n<size:10>elki.distance.timeseries" as elki.distance.timeseries.DTWDistance.Par [[DTWDistance.Par.html]]

    elki.distance.timeseries.AbstractEditDistance <|-- elki.distance.timeseries.DTWDistance
    elki.distance.timeseries.DTWDistance +-- elki.distance.timeseries.DTWDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
