@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ALIDEstimator.Par\n<size:10>elki.math.statistics.intrinsicdimensionality" as elki.math.statistics.intrinsicdimensionality.ALIDEstimator.Par [[ALIDEstimator.Par.html]] {
        +make(): ALIDEstimator
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>ALIDEstimator\n<size:10>elki.math.statistics.intrinsicdimensionality" as elki.math.statistics.intrinsicdimensionality.ALIDEstimator [[ALIDEstimator.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.math.statistics.intrinsicdimensionality.ALIDEstimator.Par
    elki.math.statistics.intrinsicdimensionality.ALIDEstimator +-- elki.math.statistics.intrinsicdimensionality.ALIDEstimator.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
