@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>KDEOS.Par\n<size:10>elki.outlier.lof" as elki.outlier.lof.KDEOS.Par<O> {
        {static} +KERNEL_ID: OptionID
        {static} +KERNEL_MIN_ID: OptionID
        {static} +KERNEL_SCALE_ID: OptionID
        {static} +KMIN_ID: OptionID
        {static} +KMAX_ID: OptionID
        {static} +IDIM_ID: OptionID
        #distance: Distance<? super O>
        #kernel: KernelDensityFunction
        #kmin: int
        #kmax: int
        #scale: double
        #minBandwidth: double
        #idim: int
        +configure(Parameterization): void
        +make(): KDEOS<O>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>KDEOS\n<size:10>elki.outlier.lof" as elki.outlier.lof.KDEOS<O> [[KDEOS.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.outlier.lof.KDEOS.Par
    elki.outlier.lof.KDEOS +-- elki.outlier.lof.KDEOS.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
