@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LDOF\n<size:10>elki.outlier.lof" as elki.outlier.lof.LDOF<O> [[LDOF.html]] {
        {static} -LOG: Logging
        {static} -LDOF_BASELINE: double
        #distance: Distance<? super O>
        #kplus: int
        +LDOF(Distance<? super O>, int)
        +getInputTypeRestriction(): TypeInformation[]
        +run(Relation<O>): OutlierResult
    }

    interface "<size:14>OutlierAlgorithm\n<size:10>elki.outlier" as elki.outlier.OutlierAlgorithm [[../OutlierAlgorithm.html]]
    class "<size:14>LDOF.Par\n<size:10>elki.outlier.lof" as elki.outlier.lof.LDOF.Par<O> [[LDOF.Par.html]]

    elki.outlier.OutlierAlgorithm <|.. elki.outlier.lof.LDOF
    elki.outlier.lof.LDOF +-- elki.outlier.lof.LDOF.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
