@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LOF.Par\n<size:10>elki.outlier.lof" as elki.outlier.lof.LOF.Par<O> {
        {static} +K_ID: OptionID
        #distance: Distance<? super O>
        #k: int
        +configure(Parameterization): void
        +make(): LOF<O>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>LOF\n<size:10>elki.outlier.lof" as elki.outlier.lof.LOF<O> [[LOF.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.outlier.lof.LOF.Par
    elki.outlier.lof.LOF +-- elki.outlier.lof.LOF.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
