@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MultipleProjectionsLocalitySensitiveHashFunction\n<size:10>elki.index.lsh.hashfunctions" as elki.index.lsh.hashfunctions.MultipleProjectionsLocalitySensitiveHashFunction [[MultipleProjectionsLocalitySensitiveHashFunction.html]] {
        ~projection: Projection
        ~shift: double[]
        ~iwidth: double
        ~randoms1: int[]
        {static} -MASK32: long
        +MultipleProjectionsLocalitySensitiveHashFunction(Projection, double, Random)
        +hashObject(NumberVector): int
        +hashObject(NumberVector, double[]): int
        {static} +fastModPrime(long): int
        +getNumberOfProjections(): int
    }

    interface "<size:14>LocalitySensitiveHashFunction\n<size:10>elki.index.lsh.hashfunctions" as elki.index.lsh.hashfunctions.LocalitySensitiveHashFunction<NumberVector> [[LocalitySensitiveHashFunction.html]] {
        {abstract} +hashObject(NumberVector): int
        {abstract} +hashObject(NumberVector, double[]): int
        {abstract} +getNumberOfProjections(): int
    }

    elki.index.lsh.hashfunctions.LocalitySensitiveHashFunction <|.. elki.index.lsh.hashfunctions.MultipleProjectionsLocalitySensitiveHashFunction

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
