@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CLIQUE.Par\n<size:10>elki.clustering.subspace" as elki.clustering.subspace.CLIQUE.Par [[CLIQUE.Par.html]] {
        {static} +XSI_ID: OptionID
        {static} +TAU_ID: OptionID
        {static} +PRUNE_ID: OptionID
        #xsi: int
        #tau: double
        #prune: boolean
        +configure(Parameterization): void
        +make(): CLIQUE
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>CLIQUE\n<size:10>elki.clustering.subspace" as elki.clustering.subspace.CLIQUE [[CLIQUE.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.clustering.subspace.CLIQUE.Par
    elki.clustering.subspace.CLIQUE +-- elki.clustering.subspace.CLIQUE.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
