@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DiSH.Par\n<size:10>elki.clustering.subspace" as elki.clustering.subspace.DiSH.Par [[DiSH.Par.html]] {
        {static} +DEFAULT_EPSILON: double
        {static} +EPSILON_ID: OptionID
        {static} +MINPTS_ID: OptionID
        {static} +DEFAULT_STRATEGY: Strategy
        {static} +STRATEGY_ID: OptionID
        {static} +MU_ID: OptionID
        #epsilon: double
        #minpts: int
        #strategy: Strategy
        +configure(Parameterization): void
        +make(): DiSH
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>DiSH\n<size:10>elki.clustering.subspace" as elki.clustering.subspace.DiSH [[DiSH.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.clustering.subspace.DiSH.Par
    elki.clustering.subspace.DiSH +-- elki.clustering.subspace.DiSH.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
