@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>GNAT.GNATKNNSearcher\n<size:10>elki.index.tree.metrical.vptree" as elki.index.tree.metrical.vptree.GNAT.GNATKNNSearcher [[GNAT.GNATKNNSearcher.html]] {
        #mvpKNNSearch(KNNHeap, Node, double): double
        {abstract} #queryDistance(DBIDRef): double
    }

    class "<size:14>GNAT\n<size:10>elki.index.tree.metrical.vptree" as elki.index.tree.metrical.vptree.GNAT<O> [[GNAT.html]]

    elki.index.tree.metrical.vptree.GNAT +-- elki.index.tree.metrical.vptree.GNAT.GNATKNNSearcher

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
