@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>VPTree.VPTreeRangeDBIDSearcher\n<size:10>elki.index.tree.metrical.vptree" as elki.index.tree.metrical.vptree.VPTree.VPTreeRangeDBIDSearcher [[VPTree.VPTreeRangeDBIDSearcher.html]] {
        -query: DBIDRef
        +getRange(DBIDRef, double, ModifiableDoubleDBIDList): ModifiableDoubleDBIDList
        #queryDistance(DBIDRef): double
    }

    abstract class "<size:14>VPTree.VPTreeRangeSearcher\n<size:10>elki.index.tree.metrical.vptree" as elki.index.tree.metrical.vptree.VPTree.VPTreeRangeSearcher [[VPTree.VPTreeRangeSearcher.html]] {
        {abstract} #queryDistance(DBIDRef): double
    }
    interface "<size:14>RangeSearcher\n<size:10>elki.database.query.range" as elki.database.query.range.RangeSearcher<DBIDRef> [[../../../../database/query/range/RangeSearcher.html]] {
        {abstract} +getRange(DBIDRef, double, ModifiableDoubleDBIDList): ModifiableDoubleDBIDList
    }
    class "<size:14>VPTree\n<size:10>elki.index.tree.metrical.vptree" as elki.index.tree.metrical.vptree.VPTree<O> [[VPTree.html]]

    elki.index.tree.metrical.vptree.VPTree.VPTreeRangeSearcher <|-- elki.index.tree.metrical.vptree.VPTree.VPTreeRangeDBIDSearcher
    elki.database.query.range.RangeSearcher <|.. elki.index.tree.metrical.vptree.VPTree.VPTreeRangeDBIDSearcher
    elki.index.tree.metrical.vptree.VPTree +-- elki.index.tree.metrical.vptree.VPTree.VPTreeRangeDBIDSearcher

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
