@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CoverTree.CoverTreePriorityDBIDSearcher\n<size:10>elki.index.tree.metrical.covertree" as elki.index.tree.metrical.covertree.CoverTree.CoverTreePriorityDBIDSearcher [[CoverTree.CoverTreePriorityDBIDSearcher.html]] {
        -query: DBIDRef
        +search(DBIDRef): PrioritySearcher<DBIDRef>
        #queryDistance(DBIDRef): double
    }

    abstract class "<size:14>CoverTree.CoverTreePrioritySearcher\n<size:10>elki.index.tree.metrical.covertree" as elki.index.tree.metrical.covertree.CoverTree.CoverTreePrioritySearcher<DBIDRef> [[CoverTree.CoverTreePrioritySearcher.html]] {
        {abstract} #queryDistance(DBIDRef): double
    }
    class "<size:14>CoverTree\n<size:10>elki.index.tree.metrical.covertree" as elki.index.tree.metrical.covertree.CoverTree<O> [[CoverTree.html]]

    elki.index.tree.metrical.covertree.CoverTree.CoverTreePrioritySearcher <|-- elki.index.tree.metrical.covertree.CoverTree.CoverTreePriorityDBIDSearcher
    elki.index.tree.metrical.covertree.CoverTree +-- elki.index.tree.metrical.covertree.CoverTree.CoverTreePriorityDBIDSearcher

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
