@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>SimplifiedCoverTree.CoverTreeKNNSearcher\n<size:10>elki.index.tree.metrical.covertree" as elki.index.tree.metrical.covertree.SimplifiedCoverTree.CoverTreeKNNSearcher [[SimplifiedCoverTree.CoverTreeKNNSearcher.html]] {
        -pq: DoubleObjectMinHeap<Node>
        -tmp: DBIDVar
        #doSearch(int): KNNList
        {abstract} #queryDistance(DBIDRef): double
    }

    class "<size:14>SimplifiedCoverTree\n<size:10>elki.index.tree.metrical.covertree" as elki.index.tree.metrical.covertree.SimplifiedCoverTree<O> [[SimplifiedCoverTree.html]]

    elki.index.tree.metrical.covertree.SimplifiedCoverTree +-- elki.index.tree.metrical.covertree.SimplifiedCoverTree.CoverTreeKNNSearcher

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
