@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>VisualizationMenuAction\n<size:10>elki.visualization" as elki.visualization.VisualizationMenuAction [[VisualizationMenuAction.html]] {
        {abstract} +activate(): void
        +enabled(): boolean
    }

    interface "<size:14>VisualizationItem\n<size:10>elki.visualization" as elki.visualization.VisualizationItem [[VisualizationItem.html]] {
        {abstract} +getMenuName(): String
    }

    elki.visualization.VisualizationItem <|-- elki.visualization.VisualizationMenuAction

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
