@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>VisualizationTask.UpdateFlag\n<size:10>elki.visualization" as elki.visualization.VisualizationTask.UpdateFlag [[VisualizationTask.UpdateFlag.html]] {
        {static} +ON_DATA
        {static} +ON_SELECTION
        {static} +ON_STYLEPOLICY
        {static} +ON_SAMPLE
        ~bit: int
        -UpdateFlag(int)
    }

    class "<size:14>VisualizationTask\n<size:10>elki.visualization" as elki.visualization.VisualizationTask [[VisualizationTask.html]]

    elki.visualization.VisualizationTask +-- elki.visualization.VisualizationTask.UpdateFlag

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
