@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>HandlerList\n<size:10>elki.utilities" as elki.utilities.HandlerList<H> [[HandlerList.html]] {
        -handlers: ArrayList<Pair<Class<?>, H>>
        +insertHandler(Class<?>, H): void
        +getHandler(Object): H
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
