@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>BatikUtil\n<size:10>elki.visualization.batikutil" as elki.visualization.batikutil.BatikUtil [[BatikUtil.html]] {
        {static} +getRelativeCoordinates(Event, Element): double[]
        {static} +hasFOPInstalled(): boolean
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
