@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LID\n<size:10>elki.outlier.intrinsic" as elki.outlier.intrinsic.LID<O> [[LID.html]] {
        {static} -LOG: Logging
        #distance: Distance<? super O>
        #kplus: int
        #estimator: IntrinsicDimensionalityEstimator<? super O>
        +LID(Distance<? super O>, int, IntrinsicDimensionalityEstimator<? super O>)
        +getInputTypeRestriction(): TypeInformation[]
        +run(Relation<O>): OutlierResult
    }

    interface "<size:14>OutlierAlgorithm\n<size:10>elki.outlier" as elki.outlier.OutlierAlgorithm [[../OutlierAlgorithm.html]]
    class "<size:14>LID.Par\n<size:10>elki.outlier.intrinsic" as elki.outlier.intrinsic.LID.Par<O> [[LID.Par.html]]

    elki.outlier.OutlierAlgorithm <|.. elki.outlier.intrinsic.LID
    elki.outlier.intrinsic.LID +-- elki.outlier.intrinsic.LID.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
