@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>DatabaseEventManager.Type\n<size:10>elki.database" as elki.database.DatabaseEventManager.Type [[DatabaseEventManager.Type.html]] {
        {static} +INSERT
        {static} +REMOVE
        {static} +UPDATE
    }

    class "<size:14>DatabaseEventManager\n<size:10>elki.database" as elki.database.DatabaseEventManager [[DatabaseEventManager.html]]

    elki.database.DatabaseEventManager +-- elki.database.DatabaseEventManager.Type

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
