@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ReplaceNaNWithRandomFilter\n<size:10>elki.datasource.filter.cleaning" as elki.datasource.filter.cleaning.ReplaceNaNWithRandomFilter [[ReplaceNaNWithRandomFilter.html]] {
        {static} -LOG: Logging
        -densecols: Factory<?>[]
        -dist: Distribution
        -rows: ArrayList<Object>
        -rnd: Random
        +ReplaceNaNWithRandomFilter(Distribution, RandomFactory)
        +getMeta(): BundleMeta
        +data(int): Object
        +nextEvent(): Event
        -updateMeta(BundleMeta): void
        +filter(MultipleObjectsBundle): MultipleObjectsBundle
    }

    abstract class "<size:14>AbstractStreamFilter\n<size:10>elki.datasource.filter" as elki.datasource.filter.AbstractStreamFilter [[../AbstractStreamFilter.html]]
    class "<size:14>ReplaceNaNWithRandomFilter.Par\n<size:10>elki.datasource.filter.cleaning" as elki.datasource.filter.cleaning.ReplaceNaNWithRandomFilter.Par [[ReplaceNaNWithRandomFilter.Par.html]]

    elki.datasource.filter.AbstractStreamFilter <|-- elki.datasource.filter.cleaning.ReplaceNaNWithRandomFilter
    elki.datasource.filter.cleaning.ReplaceNaNWithRandomFilter +-- elki.datasource.filter.cleaning.ReplaceNaNWithRandomFilter.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
