@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>VectorDimensionalityFilter.Par\n<size:10>elki.datasource.filter.cleaning" as elki.datasource.filter.cleaning.VectorDimensionalityFilter.Par<V extends NumberVector> {
        {static} +DIM_P: OptionID
        ~dim: int
        +configure(Parameterization): void
        +make(): VectorDimensionalityFilter<V extends NumberVector>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>VectorDimensionalityFilter\n<size:10>elki.datasource.filter.cleaning" as elki.datasource.filter.cleaning.VectorDimensionalityFilter<V extends NumberVector> [[VectorDimensionalityFilter.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.datasource.filter.cleaning.VectorDimensionalityFilter.Par
    elki.datasource.filter.cleaning.VectorDimensionalityFilter +-- elki.datasource.filter.cleaning.VectorDimensionalityFilter.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
