@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>IntegerArrayQuickSort\n<size:10>elki.utilities.datastructures.arrays" as elki.utilities.datastructures.arrays.IntegerArrayQuickSort [[IntegerArrayQuickSort.html]] {
        {static} -INSERTION_THRESHOLD: int
        {static} +sort(int[], IntComparator): void
        {static} +sort(int[], int, int, IntComparator): void
        {static} -quickSort(int[], int, int, IntComparator): void
        {static} -insertionSort(int[], int, int, IntComparator): void
        {static} -sort5(int[], int, int, int, int, int, IntComparator): void
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
