@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ComparatorMaxHeap.UnsortedIter\n<size:10>elki.utilities.datastructures.heap" as elki.utilities.datastructures.heap.ComparatorMaxHeap.UnsortedIter [[ComparatorMaxHeap.UnsortedIter.html]] {
        #pos: int
        +valid(): boolean
        +advance(): UnsortedIter
        +get(): K
    }

    interface "<size:14>ObjectHeap.UnsortedIter\n<size:10>elki.utilities.datastructures.heap" as elki.utilities.datastructures.heap.ObjectHeap.UnsortedIter<K> [[ObjectHeap.UnsortedIter.html]] {
        {abstract} +get(): K
    }
    class "<size:14>ComparatorMaxHeap\n<size:10>elki.utilities.datastructures.heap" as elki.utilities.datastructures.heap.ComparatorMaxHeap<K> [[ComparatorMaxHeap.html]]

    elki.utilities.datastructures.heap.ObjectHeap.UnsortedIter <|.. elki.utilities.datastructures.heap.ComparatorMaxHeap.UnsortedIter
    elki.utilities.datastructures.heap.ComparatorMaxHeap +-- elki.utilities.datastructures.heap.ComparatorMaxHeap.UnsortedIter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
