@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PrecomputedDistanceMatrix.Factory\n<size:10>elki.index.distancematrix" as elki.index.distancematrix.PrecomputedDistanceMatrix.Factory<O> [[PrecomputedDistanceMatrix.Factory.html]] {
        #distance: Distance<? super O>
        +Factory(Distance<? super O>)
        +instantiate(Relation<O>): PrecomputedDistanceMatrix<O>
        +getInputTypeRestriction(): TypeInformation
    }

    interface "<size:14>IndexFactory\n<size:10>elki.index" as elki.index.IndexFactory<O> [[../IndexFactory.html]] {
        {abstract} +instantiate(Relation<V>): Index
        {abstract} +getInputTypeRestriction(): TypeInformation
    }
    class "<size:14>PrecomputedDistanceMatrix\n<size:10>elki.index.distancematrix" as elki.index.distancematrix.PrecomputedDistanceMatrix<O> [[PrecomputedDistanceMatrix.html]]
    class "<size:14>PrecomputedDistanceMatrix.Factory.Par\n<size:10>elki.index.distancematrix" as elki.index.distancematrix.PrecomputedDistanceMatrix.Factory.Par<O>

    elki.index.IndexFactory <|.. elki.index.distancematrix.PrecomputedDistanceMatrix.Factory
    elki.index.distancematrix.PrecomputedDistanceMatrix +-- elki.index.distancematrix.PrecomputedDistanceMatrix.Factory
    elki.index.distancematrix.PrecomputedDistanceMatrix.Factory +-- elki.index.distancematrix.PrecomputedDistanceMatrix.Factory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
