@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PrecomputedSimilarityMatrix.PrecomputedSimilarityQuery\n<size:10>elki.index.distancematrix" as elki.index.distancematrix.PrecomputedSimilarityMatrix.PrecomputedSimilarityQuery [[PrecomputedSimilarityMatrix.PrecomputedSimilarityQuery.html]] {
        +similarity(DBIDRef, DBIDRef): double
        +similarity(O, DBIDRef): double
        +similarity(DBIDRef, O): double
        +similarity(O, O): double
        +getSimilarity(): Similarity<? super O>
        +getRelation(): Relation<? extends O>
    }

    interface "<size:14>SimilarityQuery\n<size:10>elki.database.query.similarity" as elki.database.query.similarity.SimilarityQuery<O> [[../../database/query/similarity/SimilarityQuery.html]] {
        {abstract} +similarity(DBIDRef, DBIDRef): double
        {abstract} +similarity(O, DBIDRef): double
        {abstract} +similarity(DBIDRef, O): double
        {abstract} +similarity(O, O): double
        {abstract} +getRelation(): Relation<? extends O>
        {abstract} +getSimilarity(): Similarity<? super O>
    }
    class "<size:14>PrecomputedSimilarityMatrix\n<size:10>elki.index.distancematrix" as elki.index.distancematrix.PrecomputedSimilarityMatrix<O> [[PrecomputedSimilarityMatrix.html]]

    elki.database.query.similarity.SimilarityQuery <|.. elki.index.distancematrix.PrecomputedSimilarityMatrix.PrecomputedSimilarityQuery
    elki.index.distancematrix.PrecomputedSimilarityMatrix +-- elki.index.distancematrix.PrecomputedSimilarityMatrix.PrecomputedSimilarityQuery

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
