@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CLINK.Par\n<size:10>elki.clustering.hierarchical" as elki.clustering.hierarchical.CLINK.Par<O> [[CLINK.Par.html]] {
        #distance: Distance<? super O>
        +configure(Parameterization): void
        +make(): CLINK<O>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>CLINK\n<size:10>elki.clustering.hierarchical" as elki.clustering.hierarchical.CLINK<O> [[CLINK.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.clustering.hierarchical.CLINK.Par
    elki.clustering.hierarchical.CLINK +-- elki.clustering.hierarchical.CLINK.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
