@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ClusterDistanceMatrix\n<size:10>elki.clustering.hierarchical" as elki.clustering.hierarchical.ClusterDistanceMatrix [[ClusterDistanceMatrix.html]] {
        +matrix: double[]
        +clustermap: int[]
        +size: int
        +ClusterDistanceMatrix(int)
        {static} +triangleSize(int): int
        +get(int, int): double
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
