@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ClusterPrototypeMergeHistory\n<size:10>elki.clustering.hierarchical" as elki.clustering.hierarchical.ClusterPrototypeMergeHistory [[ClusterPrototypeMergeHistory.html]] {
        #prototypes: ArrayDBIDs
        +ClusterPrototypeMergeHistory(ArrayDBIDs, int[], double[], int[], boolean, ArrayDBIDs)
        +prototype(int): DBID
    }

    class "<size:14>ClusterMergeHistory\n<size:10>elki.clustering.hierarchical" as elki.clustering.hierarchical.ClusterMergeHistory [[ClusterMergeHistory.html]]

    elki.clustering.hierarchical.ClusterMergeHistory <|-- elki.clustering.hierarchical.ClusterPrototypeMergeHistory

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
