@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>HierarchicalClusteringAlgorithm\n<size:10>elki.clustering.hierarchical" as elki.clustering.hierarchical.HierarchicalClusteringAlgorithm [[HierarchicalClusteringAlgorithm.html]] {
        +autorun(Database): ClusterMergeHistory
    }

    interface "<size:14>Algorithm\n<size:10>elki" as elki.Algorithm [[../../Algorithm.html]] {
        {abstract} +getInputTypeRestriction(): TypeInformation[]
    }

    elki.Algorithm <|-- elki.clustering.hierarchical.HierarchicalClusteringAlgorithm

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
