@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LinearMemoryNNChain.Par\n<size:10>elki.clustering.hierarchical" as elki.clustering.hierarchical.LinearMemoryNNChain.Par<O extends NumberVector> {
        {static} +LINKAGE_ID: OptionID
        #linkage: GeometricLinkage
        +configure(Parameterization): void
        +make(): LinearMemoryNNChain<O extends NumberVector>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>LinearMemoryNNChain\n<size:10>elki.clustering.hierarchical" as elki.clustering.hierarchical.LinearMemoryNNChain<O extends NumberVector> [[LinearMemoryNNChain.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.clustering.hierarchical.LinearMemoryNNChain.Par
    elki.clustering.hierarchical.LinearMemoryNNChain +-- elki.clustering.hierarchical.LinearMemoryNNChain.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
