@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MiniMaxNNChain.Par\n<size:10>elki.clustering.hierarchical" as elki.clustering.hierarchical.MiniMaxNNChain.Par<O> {
        +make(): MiniMaxNNChain<O>
    }

    class "<size:14>MiniMax.Par\n<size:10>elki.clustering.hierarchical" as elki.clustering.hierarchical.MiniMax.Par<O>
    class "<size:14>MiniMaxNNChain\n<size:10>elki.clustering.hierarchical" as elki.clustering.hierarchical.MiniMaxNNChain<O> [[MiniMaxNNChain.html]]

    elki.clustering.hierarchical.MiniMax.Par <|-- elki.clustering.hierarchical.MiniMaxNNChain.Par
    elki.clustering.hierarchical.MiniMaxNNChain +-- elki.clustering.hierarchical.MiniMaxNNChain.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
