@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>EuclideanSphericalHamerlyKMeans.Par\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans.Par<V extends NumberVector> [[EuclideanSphericalHamerlyKMeans.Par.html]] {
        +configure(Parameterization): void
        +make(): EuclideanSphericalHamerlyKMeans<V extends NumberVector>
    }

    class "<size:14>SphericalKMeans.Par\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.SphericalKMeans.Par<V extends NumberVector> [[SphericalKMeans.Par.html]]
    class "<size:14>EuclideanSphericalHamerlyKMeans\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans<V extends NumberVector> [[EuclideanSphericalHamerlyKMeans.html]]

    elki.clustering.kmeans.spherical.SphericalKMeans.Par <|-- elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans.Par
    elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans +-- elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
