@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>EuclideanSphericalHamerlyKMeans\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans<V extends NumberVector> [[EuclideanSphericalHamerlyKMeans.html]] {
        {static} -LOG: Logging
        #varstat: boolean
        +EuclideanSphericalHamerlyKMeans(int, int, KMeansInitialization, boolean)
        +run(Relation<V extends NumberVector>): Clustering<KMeansModel>
        #getLogger(): Logging
    }

    class "<size:14>SphericalKMeans\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.SphericalKMeans<V extends NumberVector> [[SphericalKMeans.html]]
    class "<size:14>EuclideanSphericalHamerlyKMeans.Instance\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans.Instance [[EuclideanSphericalHamerlyKMeans.Instance.html]]
    class "<size:14>EuclideanSphericalHamerlyKMeans.Par\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans.Par<V extends NumberVector> [[EuclideanSphericalHamerlyKMeans.Par.html]]

    elki.clustering.kmeans.spherical.SphericalKMeans <|-- elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans
    elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans +-- elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans.Instance
    elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans +-- elki.clustering.kmeans.spherical.EuclideanSphericalHamerlyKMeans.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
