@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SphericalSingleAssignmentKMeans\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.SphericalSingleAssignmentKMeans<V extends NumberVector> [[SphericalSingleAssignmentKMeans.html]] {
        {static} -LOG: Logging
        +SphericalSingleAssignmentKMeans(int, KMeansInitialization)
        +run(Relation<V extends NumberVector>): Clustering<KMeansModel>
        #getLogger(): Logging
    }

    class "<size:14>SphericalKMeans\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.SphericalKMeans<V extends NumberVector> [[SphericalKMeans.html]]
    class "<size:14>SphericalSingleAssignmentKMeans.Instance\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.SphericalSingleAssignmentKMeans.Instance [[SphericalSingleAssignmentKMeans.Instance.html]]
    class "<size:14>SphericalSingleAssignmentKMeans.Par\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.SphericalSingleAssignmentKMeans.Par<V extends NumberVector> [[SphericalSingleAssignmentKMeans.Par.html]]

    elki.clustering.kmeans.spherical.SphericalKMeans <|-- elki.clustering.kmeans.spherical.SphericalSingleAssignmentKMeans
    elki.clustering.kmeans.spherical.SphericalSingleAssignmentKMeans +-- elki.clustering.kmeans.spherical.SphericalSingleAssignmentKMeans.Instance
    elki.clustering.kmeans.spherical.SphericalSingleAssignmentKMeans +-- elki.clustering.kmeans.spherical.SphericalSingleAssignmentKMeans.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
