@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SphericalElkanKMeans.Par\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.SphericalElkanKMeans.Par<V extends NumberVector> [[SphericalElkanKMeans.Par.html]] {
        +make(): SphericalElkanKMeans<V extends NumberVector>
    }

    class "<size:14>SphericalSimplifiedElkanKMeans.Par\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.SphericalSimplifiedElkanKMeans.Par<V extends NumberVector> [[SphericalSimplifiedElkanKMeans.Par.html]]
    class "<size:14>SphericalElkanKMeans\n<size:10>elki.clustering.kmeans.spherical" as elki.clustering.kmeans.spherical.SphericalElkanKMeans<V extends NumberVector> [[SphericalElkanKMeans.html]]

    elki.clustering.kmeans.spherical.SphericalSimplifiedElkanKMeans.Par <|-- elki.clustering.kmeans.spherical.SphericalElkanKMeans.Par
    elki.clustering.kmeans.spherical.SphericalElkanKMeans +-- elki.clustering.kmeans.spherical.SphericalElkanKMeans.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
