@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>FasterMSC.Instance2\n<size:10>elki.clustering.silhouette" as elki.clustering.silhouette.FasterMSC.Instance2 [[FasterMSC.Instance2.html]] {
        +Instance2(DistanceQuery<?>, DBIDs, WritableIntegerDataStore)
        #run(ArrayModifiableDBIDs, int): double
    }

    class "<size:14>FastMSC.Instance2\n<size:10>elki.clustering.silhouette" as elki.clustering.silhouette.FastMSC.Instance2 [[FastMSC.Instance2.html]]
    class "<size:14>FasterMSC\n<size:10>elki.clustering.silhouette" as elki.clustering.silhouette.FasterMSC<O> [[FasterMSC.html]]

    elki.clustering.silhouette.FastMSC.Instance2 <|-- elki.clustering.silhouette.FasterMSC.Instance2
    elki.clustering.silhouette.FasterMSC +-- elki.clustering.silhouette.FasterMSC.Instance2

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
