@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>FastMSC.Instance2\n<size:10>elki.clustering.silhouette" as elki.clustering.silhouette.FastMSC.Instance2 [[FastMSC.Instance2.html]] {
        #ids: DBIDs
        #distQ: DistanceQuery<?>
        #dm0: WritableDoubleDataStore
        #dm1: WritableDoubleDataStore
        #assignment: WritableIntegerDataStore
        +Instance2(DistanceQuery<?>, DBIDs, WritableIntegerDataStore)
        #run(ArrayModifiableDBIDs, int): double
        #assignToNearestCluster(ArrayDBIDs): double
        #findBestSwap(DBIDRef, double[]): void
        #doSwap(ArrayDBIDs, int, DBIDRef): double
        +silhouetteScores(): DoubleDataStore
    }

    class "<size:14>FastMSC\n<size:10>elki.clustering.silhouette" as elki.clustering.silhouette.FastMSC<O> [[FastMSC.html]]

    elki.clustering.silhouette.FastMSC +-- elki.clustering.silhouette.FastMSC.Instance2

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
