@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PAMMEDSIL.Instance\n<size:10>elki.clustering.silhouette" as elki.clustering.silhouette.PAMMEDSIL.Instance [[PAMMEDSIL.Instance.html]] {
        +Instance(DistanceQuery<?>, DBIDs, WritableIntegerDataStore)
        #run(ArrayModifiableDBIDs, int): double
        #medoidsilhouette(IntegerDataStore, DBIDArrayIter): double
        #medoidsilhouette(IntegerDataStore, DBIDArrayIter, int, DBIDRef): double
    }

    class "<size:14>PAMSIL.Instance\n<size:10>elki.clustering.silhouette" as elki.clustering.silhouette.PAMSIL.Instance [[PAMSIL.Instance.html]]
    class "<size:14>PAMMEDSIL\n<size:10>elki.clustering.silhouette" as elki.clustering.silhouette.PAMMEDSIL<O> [[PAMMEDSIL.html]]

    elki.clustering.silhouette.PAMSIL.Instance <|-- elki.clustering.silhouette.PAMMEDSIL.Instance
    elki.clustering.silhouette.PAMMEDSIL +-- elki.clustering.silhouette.PAMMEDSIL.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
