@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>DatabaseDistanceQuery\n<size:10>elki.database.query.distance" as elki.database.query.distance.DatabaseDistanceQuery<O> [[DatabaseDistanceQuery.html]] {
        +distance(O, DBIDRef): double
        +distance(DBIDRef, O): double
        +distance(O, O): double
    }

    interface "<size:14>DistanceQuery\n<size:10>elki.database.query.distance" as elki.database.query.distance.DistanceQuery<O> [[DistanceQuery.html]] {
        {abstract} +distance(DBIDRef, DBIDRef): double
        {abstract} +distance(O, DBIDRef): double
        {abstract} +distance(DBIDRef, O): double
        {abstract} +distance(O, O): double
        {abstract} +getDistance(): Distance<? super O>
        {abstract} +getRelation(): Relation<? extends O>
    }

    elki.database.query.distance.DistanceQuery <|-- elki.database.query.distance.DatabaseDistanceQuery

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
