@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LinearScanPrioritySearcher.ByDBID\n<size:10>elki.database.query.distance" as elki.database.query.distance.LinearScanPrioritySearcher.ByDBID<O> [[LinearScanPrioritySearcher.ByDBID.html]] {
        +ByDBID(DistanceQuery<O>)
        +search(DBIDRef): PrioritySearcher<DBIDRef>
    }

    abstract class "<size:14>LinearScanPrioritySearcher\n<size:10>elki.database.query.distance" as elki.database.query.distance.LinearScanPrioritySearcher<Q, O> [[LinearScanPrioritySearcher.html]]
    abstract class "<size:14>LinearScanPrioritySearcher\n<size:10>elki.database.query.distance" as elki.database.query.distance.LinearScanPrioritySearcher<Q, O> [[LinearScanPrioritySearcher.html]]

    elki.database.query.distance.LinearScanPrioritySearcher <|-- elki.database.query.distance.LinearScanPrioritySearcher.ByDBID
    elki.database.query.distance.LinearScanPrioritySearcher +-- elki.database.query.distance.LinearScanPrioritySearcher.ByDBID

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
