@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SplitNumberVectorFilter.Par\n<size:10>elki.datasource.filter.typeconversions" as elki.datasource.filter.typeconversions.SplitNumberVectorFilter.Par<V extends NumberVector> [[SplitNumberVectorFilter.Par.html]] {
        {static} +SELECTED_ATTRIBUTES_ID: OptionID
        #dims: int[]
        +configure(Parameterization): void
        +make(): SplitNumberVectorFilter<V extends NumberVector>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>SplitNumberVectorFilter\n<size:10>elki.datasource.filter.typeconversions" as elki.datasource.filter.typeconversions.SplitNumberVectorFilter<V extends NumberVector> [[SplitNumberVectorFilter.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.datasource.filter.typeconversions.SplitNumberVectorFilter.Par
    elki.datasource.filter.typeconversions.SplitNumberVectorFilter +-- elki.datasource.filter.typeconversions.SplitNumberVectorFilter.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
