@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SimplifiedLRDProcessor.Instance\n<size:10>elki.outlier.lof.parallel" as elki.outlier.lof.parallel.SimplifiedLRDProcessor.Instance [[SimplifiedLRDProcessor.Instance.html]] {
        +Instance(Instance)
        +map(DBIDRef): void
    }

    abstract class "<size:14>AbstractDoubleProcessor.Instance\n<size:10>elki.parallel.processor" as elki.parallel.processor.AbstractDoubleProcessor.Instance [[../../../parallel/processor/AbstractDoubleProcessor.Instance.html]] {
        {abstract} +map(DBIDRef): void
    }
    class "<size:14>SimplifiedLRDProcessor\n<size:10>elki.outlier.lof.parallel" as elki.outlier.lof.parallel.SimplifiedLRDProcessor [[SimplifiedLRDProcessor.html]]

    elki.parallel.processor.AbstractDoubleProcessor.Instance <|-- elki.outlier.lof.parallel.SimplifiedLRDProcessor.Instance
    elki.outlier.lof.parallel.SimplifiedLRDProcessor +-- elki.outlier.lof.parallel.SimplifiedLRDProcessor.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
