@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>LeafEntry\n<size:10>elki.index.tree" as elki.index.tree.LeafEntry [[LeafEntry.html]] {
        {abstract} +getDBID(): DBID
    }

    interface "<size:14>Externalizable\n<size:10>java.io" as java.io.Externalizable {
        {abstract} +writeExternal(ObjectOutput): void
        {abstract} +readExternal(ObjectInput): void
    }

    java.io.Externalizable <|-- elki.index.tree.LeafEntry

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
