@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SharedInteger\n<size:10>elki.parallel.variables" as elki.parallel.variables.SharedInteger [[SharedInteger.html]] {
        +instantiate(): Instance
    }

    interface "<size:14>SharedVariable\n<size:10>elki.parallel.variables" as elki.parallel.variables.SharedVariable<Instance> [[SharedVariable.html]] {
        {abstract} +instantiate(): Instance
    }
    class "<size:14>SharedInteger.Instance\n<size:10>elki.parallel.variables" as elki.parallel.variables.SharedInteger.Instance [[SharedInteger.Instance.html]]

    elki.parallel.variables.SharedVariable <|.. elki.parallel.variables.SharedInteger
    elki.parallel.variables.SharedInteger +-- elki.parallel.variables.SharedInteger.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
