@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ClassParameter\n<size:10>elki.utilities.optionhandling.parameters" as elki.utilities.optionhandling.parameters.ClassParameter<C> [[ClassParameter.html]] {
        {static} -LOG: Logging
        #restrictionClass: Class<C>
        +ClassParameter(OptionID, Class<?>, Class<?>)
        +ClassParameter(OptionID, Class<?>)
        #parseValue(Object): Class<? extends C>
        +validate(Class<? extends C>): boolean
        +getSyntax(): String
        +describeValues(StringBuilder): StringBuilder
        {static} #describeImplementations(StringBuilder, Class<?>, List<Class<?>>): StringBuilder
        +getValueAsString(): String
        +getDefaultValueAsString(): String
        {static} +canonicalClassName(Class<?>, Package): String
        {static} +canonicalClassName(Class<?>, Class<?>): String
        +instantiateClass(Parameterization): C
        +getRestrictionClass(): Class<C>
        +getKnownImplementations(): List<Class<?>>
        +grab(Parameterization, Consumer<C>): boolean
    }

    abstract class "<size:14>AbstractParameter\n<size:10>elki.utilities.optionhandling.parameters" as elki.utilities.optionhandling.parameters.AbstractParameter<ClassParameter<C>, Class<? extends C>> [[AbstractParameter.html]] {
        {abstract} #parseValue(Object): Class<? extends C>
    }

    elki.utilities.optionhandling.parameters.AbstractParameter <|-- elki.utilities.optionhandling.parameters.ClassParameter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
