@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DoubleParameter\n<size:10>elki.utilities.optionhandling.parameters" as elki.utilities.optionhandling.parameters.DoubleParameter [[DoubleParameter.html]] {
        +DoubleParameter(OptionID, double)
        +DoubleParameter(OptionID)
        +getValueAsString(): String
        #parseValue(Object): Double
        +getSyntax(): String
        +doubleValue(): double
        +grab(Parameterization, DoubleConsumer): boolean
    }

    abstract class "<size:14>NumberParameter\n<size:10>elki.utilities.optionhandling.parameters" as elki.utilities.optionhandling.parameters.NumberParameter<DoubleParameter, Double> [[NumberParameter.html]]

    elki.utilities.optionhandling.parameters.NumberParameter <|-- elki.utilities.optionhandling.parameters.DoubleParameter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
