@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AbsolutePearsonCorrelationDistance\n<size:10>elki.distance.correlation" as elki.distance.correlation.AbsolutePearsonCorrelationDistance [[AbsolutePearsonCorrelationDistance.html]] {
        {static} +STATIC: AbsolutePearsonCorrelationDistance
        +distance(NumberVector, NumberVector): double
    }

    abstract class "<size:14>AbstractNumberVectorDistance\n<size:10>elki.distance" as elki.distance.AbstractNumberVectorDistance [[../AbstractNumberVectorDistance.html]]
    class "<size:14>AbsolutePearsonCorrelationDistance.Par\n<size:10>elki.distance.correlation" as elki.distance.correlation.AbsolutePearsonCorrelationDistance.Par [[AbsolutePearsonCorrelationDistance.Par.html]]

    elki.distance.AbstractNumberVectorDistance <|-- elki.distance.correlation.AbsolutePearsonCorrelationDistance
    elki.distance.correlation.AbsolutePearsonCorrelationDistance +-- elki.distance.correlation.AbsolutePearsonCorrelationDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
