@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PearsonCorrelationDistance\n<size:10>elki.distance.correlation" as elki.distance.correlation.PearsonCorrelationDistance [[PearsonCorrelationDistance.html]] {
        {static} +STATIC: PearsonCorrelationDistance
        +distance(NumberVector, NumberVector): double
    }

    abstract class "<size:14>AbstractNumberVectorDistance\n<size:10>elki.distance" as elki.distance.AbstractNumberVectorDistance [[../AbstractNumberVectorDistance.html]]
    class "<size:14>PearsonCorrelationDistance.Par\n<size:10>elki.distance.correlation" as elki.distance.correlation.PearsonCorrelationDistance.Par [[PearsonCorrelationDistance.Par.html]]

    elki.distance.AbstractNumberVectorDistance <|-- elki.distance.correlation.PearsonCorrelationDistance
    elki.distance.correlation.PearsonCorrelationDistance +-- elki.distance.correlation.PearsonCorrelationDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
