@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PearsonCorrelationDistance.Par\n<size:10>elki.distance.correlation" as elki.distance.correlation.PearsonCorrelationDistance.Par [[PearsonCorrelationDistance.Par.html]] {
        +make(): PearsonCorrelationDistance
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>PearsonCorrelationDistance\n<size:10>elki.distance.correlation" as elki.distance.correlation.PearsonCorrelationDistance [[PearsonCorrelationDistance.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.distance.correlation.PearsonCorrelationDistance.Par
    elki.distance.correlation.PearsonCorrelationDistance +-- elki.distance.correlation.PearsonCorrelationDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
