@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>WeightedSquaredPearsonCorrelationDistance.Par\n<size:10>elki.distance.correlation" as elki.distance.correlation.WeightedSquaredPearsonCorrelationDistance.Par [[WeightedSquaredPearsonCorrelationDistance.Par.html]] {
        #weights: double[]
        +configure(Parameterization): void
        +make(): WeightedSquaredPearsonCorrelationDistance
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>WeightedSquaredPearsonCorrelationDistance\n<size:10>elki.distance.correlation" as elki.distance.correlation.WeightedSquaredPearsonCorrelationDistance [[WeightedSquaredPearsonCorrelationDistance.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.distance.correlation.WeightedSquaredPearsonCorrelationDistance.Par
    elki.distance.correlation.WeightedSquaredPearsonCorrelationDistance +-- elki.distance.correlation.WeightedSquaredPearsonCorrelationDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
