@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractDistanceBasedApplication\n<size:10>elki.application" as elki.application.AbstractDistanceBasedApplication<O> [[AbstractDistanceBasedApplication.html]] {
        #distance: Distance<? super O>
        #inputstep: InputStep
        +AbstractDistanceBasedApplication(InputStep, Distance<? super O>)
    }

    abstract class "<size:14>AbstractApplication\n<size:10>elki.application" as elki.application.AbstractApplication [[AbstractApplication.html]] {
        {abstract} +run(): void
    }
    abstract class "<size:14>AbstractDistanceBasedApplication.Par\n<size:10>elki.application" as elki.application.AbstractDistanceBasedApplication.Par<O>

    elki.application.AbstractApplication <|-- elki.application.AbstractDistanceBasedApplication
    elki.application.AbstractDistanceBasedApplication +-- elki.application.AbstractDistanceBasedApplication.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
