@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ClassifierHoldoutEvaluationTask.Par\n<size:10>elki.application" as elki.application.ClassifierHoldoutEvaluationTask.Par<O> [[ClassifierHoldoutEvaluationTask.Par.html]] {
        {static} +HOLDOUT_ID: OptionID
        #databaseConnection: DatabaseConnection
        #indexFactories: Collection<? extends IndexFactory<?>>
        #algorithm: Classifier<O>
        #holdout: Holdout
        +configure(Parameterization): void
        +make(): ClassifierHoldoutEvaluationTask<O>
    }

    abstract class "<size:14>AbstractApplication.Par\n<size:10>elki.application" as elki.application.AbstractApplication.Par [[AbstractApplication.Par.html]] {
        {abstract} +make(): AbstractApplication
    }
    class "<size:14>ClassifierHoldoutEvaluationTask\n<size:10>elki.application" as elki.application.ClassifierHoldoutEvaluationTask<O> [[ClassifierHoldoutEvaluationTask.html]]

    elki.application.AbstractApplication.Par <|-- elki.application.ClassifierHoldoutEvaluationTask.Par
    elki.application.ClassifierHoldoutEvaluationTask +-- elki.application.ClassifierHoldoutEvaluationTask.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
