@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractNumberVectorDistance\n<size:10>elki.distance" as elki.distance.AbstractNumberVectorDistance [[AbstractNumberVectorDistance.html]] {
        +getInputTypeRestriction(): SimpleTypeInformation<? super NumberVector>
        {static} +dimensionality(SpatialComparable, SpatialComparable): int
        {static} +dimensionality(double[], SpatialComparable): int
        {static} +dimensionality(double[], double[]): int
        {static} +dimensionality(SpatialComparable, SpatialComparable, int): int
        {static} +dimensionality(double[], SpatialComparable, int): int
        {static} +dimensionality(double[], double[], int): int
        {static} +dimensionality(NumberVector, NumberVector): int
        {static} +dimensionality(NumberVector, NumberVector, int): int
    }

    interface "<size:14>NumberVectorDistance\n<size:10>elki.distance" as elki.distance.NumberVectorDistance<NumberVector> [[NumberVectorDistance.html]] {
        {abstract} +distance(NumberVector, NumberVector): double
    }

    elki.distance.NumberVectorDistance <|.. elki.distance.AbstractNumberVectorDistance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
