@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CosineUnitlengthDistance\n<size:10>elki.distance" as elki.distance.CosineUnitlengthDistance [[CosineUnitlengthDistance.html]] {
        {static} +STATIC: CosineUnitlengthDistance
        +distance(NumberVector, NumberVector): double
        +minDist(SpatialComparable, SpatialComparable): double
        +isSquared(): boolean
        +getInputTypeRestriction(): SimpleTypeInformation<? super NumberVector>
    }

    interface "<size:14>SpatialPrimitiveDistance\n<size:10>elki.distance" as elki.distance.SpatialPrimitiveDistance<NumberVector> [[SpatialPrimitiveDistance.html]] {
        {abstract} +minDist(SpatialComparable, SpatialComparable): double
    }
    interface "<size:14>NumberVectorDistance\n<size:10>elki.distance" as elki.distance.NumberVectorDistance<NumberVector> [[NumberVectorDistance.html]] {
        {abstract} +distance(NumberVector, NumberVector): double
    }
    class "<size:14>CosineUnitlengthDistance.Par\n<size:10>elki.distance" as elki.distance.CosineUnitlengthDistance.Par [[CosineUnitlengthDistance.Par.html]]

    elki.distance.SpatialPrimitiveDistance <|.. elki.distance.CosineUnitlengthDistance
    elki.distance.NumberVectorDistance <|.. elki.distance.CosineUnitlengthDistance
    elki.distance.CosineUnitlengthDistance +-- elki.distance.CosineUnitlengthDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
