@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>Distance\n<size:10>elki.distance" as elki.distance.Distance<O> [[Distance.html]] {
        +isSymmetric(): boolean
        +isMetric(): boolean
        +isSquared(): boolean
        {abstract} +getInputTypeRestriction(): TypeInformation
        {abstract} +instantiate(Relation<T extends O>): DistanceQuery<T extends O>
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
