@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>IndexBasedDistance.Instance\n<size:10>elki.distance" as elki.distance.IndexBasedDistance.Instance<T, I extends Index> [[IndexBasedDistance.Instance.html]] {
        {abstract} +getIndex(): I extends Index
    }

    interface "<size:14>DatabaseDistanceQuery\n<size:10>elki.database.query.distance" as elki.database.query.distance.DatabaseDistanceQuery<T> [[../database/query/distance/DatabaseDistanceQuery.html]]
    interface "<size:14>IndexBasedDistance\n<size:10>elki.distance" as elki.distance.IndexBasedDistance<O> [[IndexBasedDistance.html]]

    elki.database.query.distance.DatabaseDistanceQuery <|-- elki.distance.IndexBasedDistance.Instance
    elki.distance.IndexBasedDistance +-- elki.distance.IndexBasedDistance.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
