@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MahalanobisDistance\n<size:10>elki.distance" as elki.distance.MahalanobisDistance [[MahalanobisDistance.html]] {
        +MahalanobisDistance(double[])
        +distance(NumberVector, NumberVector): double
        +norm(NumberVector): double
        +isMetric(): boolean
        +isSquared(): boolean
    }

    class "<size:14>MatrixWeightedQuadraticDistance\n<size:10>elki.distance" as elki.distance.MatrixWeightedQuadraticDistance [[MatrixWeightedQuadraticDistance.html]]

    elki.distance.MatrixWeightedQuadraticDistance <|-- elki.distance.MahalanobisDistance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
