@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RandomStableDistance.Par\n<size:10>elki.distance" as elki.distance.RandomStableDistance.Par [[RandomStableDistance.Par.html]] {
        +make(): RandomStableDistance
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>RandomStableDistance\n<size:10>elki.distance" as elki.distance.RandomStableDistance [[RandomStableDistance.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.distance.RandomStableDistance.Par
    elki.distance.RandomStableDistance +-- elki.distance.RandomStableDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
