@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SqrtCosineUnitlengthDistance\n<size:10>elki.distance" as elki.distance.SqrtCosineUnitlengthDistance [[SqrtCosineUnitlengthDistance.html]] {
        {static} +STATIC: SqrtCosineUnitlengthDistance
        +distance(NumberVector, NumberVector): double
        +minDist(SpatialComparable, SpatialComparable): double
        +isSquared(): boolean
        +isMetric(): boolean
    }

    class "<size:14>CosineUnitlengthDistance\n<size:10>elki.distance" as elki.distance.CosineUnitlengthDistance [[CosineUnitlengthDistance.html]]
    class "<size:14>SqrtCosineUnitlengthDistance.Par\n<size:10>elki.distance" as elki.distance.SqrtCosineUnitlengthDistance.Par [[SqrtCosineUnitlengthDistance.Par.html]]

    elki.distance.CosineUnitlengthDistance <|-- elki.distance.SqrtCosineUnitlengthDistance
    elki.distance.SqrtCosineUnitlengthDistance +-- elki.distance.SqrtCosineUnitlengthDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
