@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MemoryPageFile\n<size:10>elki.persistent" as elki.persistent.MemoryPageFile<P extends Page> [[MemoryPageFile.html]] {
        {static} -LOG: Logging
        -file: Int2ObjectOpenHashMap<P extends Page>
        +MemoryPageFile(int)
        +readPage(int): P extends Page
        #writePage(int, P extends Page): void
        +deletePage(int): void
        +clear(): void
        #getLogger(): Logging
    }

    abstract class "<size:14>AbstractStoringPageFile\n<size:10>elki.persistent" as elki.persistent.AbstractStoringPageFile<P extends Page> [[AbstractStoringPageFile.html]]

    elki.persistent.AbstractStoringPageFile <|-- elki.persistent.MemoryPageFile

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
