@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>OnDiskArrayPageFileFactory\n<size:10>elki.persistent" as elki.persistent.OnDiskArrayPageFileFactory<P extends Page> [[OnDiskArrayPageFileFactory.html]] {
        -fileName: Path
        +OnDiskArrayPageFileFactory(int, Path)
        +newPageFile(Class<P extends Page>): PageFile<P extends Page>
    }

    abstract class "<size:14>AbstractPageFileFactory\n<size:10>elki.persistent" as elki.persistent.AbstractPageFileFactory<P extends Page> [[AbstractPageFileFactory.html]]
    class "<size:14>OnDiskArrayPageFileFactory.Par\n<size:10>elki.persistent" as elki.persistent.OnDiskArrayPageFileFactory.Par

    elki.persistent.AbstractPageFileFactory <|-- elki.persistent.OnDiskArrayPageFileFactory
    elki.persistent.OnDiskArrayPageFileFactory +-- elki.persistent.OnDiskArrayPageFileFactory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
