@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ProgressTracker\n<size:10>elki.logging.progress" as elki.logging.progress.ProgressTracker [[ProgressTracker.html]] {
        -progresses: ArrayList<WeakReference<Progress>>
        +getProgresses(): Collection<Progress>
        +addProgress(Progress): void
        +removeCompleted(): Collection<Progress>
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
