@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MkMaxDirectoryEntry\n<size:10>elki.index.tree.metrical.mtreevariants.mktrees.mkmax" as elki.index.tree.metrical.mtreevariants.mktrees.mkmax.MkMaxDirectoryEntry [[MkMaxDirectoryEntry.html]] {
        {static} -serialVersionUID: long
        -knnDistance: double
        +MkMaxDirectoryEntry()
        +MkMaxDirectoryEntry(DBID, double, int, double, double)
        +getKnnDistance(): double
        +setKnnDistance(double): void
        +writeExternal(ObjectOutput): void
        +readExternal(ObjectInput): void
    }

    class "<size:14>MTreeDirectoryEntry\n<size:10>elki.index.tree.metrical.mtreevariants" as elki.index.tree.metrical.mtreevariants.MTreeDirectoryEntry [[../../MTreeDirectoryEntry.html]]
    interface "<size:14>MkMaxEntry\n<size:10>elki.index.tree.metrical.mtreevariants.mktrees.mkmax" as elki.index.tree.metrical.mtreevariants.mktrees.mkmax.MkMaxEntry [[MkMaxEntry.html]] {
        {abstract} +getKnnDistance(): double
        {abstract} +setKnnDistance(double): void
    }

    elki.index.tree.metrical.mtreevariants.MTreeDirectoryEntry <|-- elki.index.tree.metrical.mtreevariants.mktrees.mkmax.MkMaxDirectoryEntry
    elki.index.tree.metrical.mtreevariants.mktrees.mkmax.MkMaxEntry <|.. elki.index.tree.metrical.mtreevariants.mktrees.mkmax.MkMaxDirectoryEntry

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
