@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DoubleIntegerDBIDArrayList\n<size:10>elki.database.ids.integer" as elki.database.ids.integer.DoubleIntegerDBIDArrayList [[DoubleIntegerDBIDArrayList.html]] {
        {static} -INITIAL_SIZE: int
        ~size: int
        ~dists: double[]
        ~ids: int[]
        {static} -EMPTY_DISTS: double[]
        {static} -EMPTY_IDS: int[]
        #DoubleIntegerDBIDArrayList()
        #DoubleIntegerDBIDArrayList(int)
        +iter(): Itr
        +contains(DBIDRef): boolean
        +size(): int
        +assignVar(int, DBIDVar): DBIDVar
        +doubleValue(int): double
        #addInternal(double, int): void
        #grow(): void
        +add(double, DBIDRef): void
        +add(DoubleDBIDPair): void
        +clear(): ModifiableDoubleDBIDList
        +sort(): ModifiableDoubleDBIDList
        +sortDescending(): ModifiableDoubleDBIDList
        #reverse(): void
        +remove(int): void
        +removeSwap(int): void
        +swap(int, int): void
        +truncate(int): void
        +slice(int, int): DoubleIntegerDBIDList
    }

    interface "<size:14>ModifiableDoubleDBIDList\n<size:10>elki.database.ids" as elki.database.ids.ModifiableDoubleDBIDList [[../ModifiableDoubleDBIDList.html]] {
        {abstract} +add(double, DBIDRef): void
        {abstract} +add(DoubleDBIDPair): void
        {abstract} +clear(): ModifiableDoubleDBIDList
        {abstract} +sort(): ModifiableDoubleDBIDList
        {abstract} +sortDescending(): ModifiableDoubleDBIDList
        {abstract} +swap(int, int): void
        {abstract} +remove(int): void
        {abstract} +removeSwap(int): void
        {abstract} +iter(): DoubleDBIDListMIter
    }
    interface "<size:14>DoubleIntegerDBIDList\n<size:10>elki.database.ids.integer" as elki.database.ids.integer.DoubleIntegerDBIDList [[DoubleIntegerDBIDList.html]] {
        {abstract} +iter(): DoubleIntegerDBIDListIter
    }
    class "<size:14>DoubleIntegerDBIDArrayList.Itr\n<size:10>elki.database.ids.integer" as elki.database.ids.integer.DoubleIntegerDBIDArrayList.Itr [[DoubleIntegerDBIDArrayList.Itr.html]]

    elki.database.ids.ModifiableDoubleDBIDList <|.. elki.database.ids.integer.DoubleIntegerDBIDArrayList
    elki.database.ids.integer.DoubleIntegerDBIDList <|.. elki.database.ids.integer.DoubleIntegerDBIDArrayList
    elki.database.ids.integer.DoubleIntegerDBIDArrayList +-- elki.database.ids.integer.DoubleIntegerDBIDArrayList.Itr

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
