@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DoubleIntegerDBIDHeap\n<size:10>elki.database.ids.integer" as elki.database.ids.integer.DoubleIntegerDBIDHeap [[DoubleIntegerDBIDHeap.html]] {
        -heap: DoubleIntegerHeap
        #DoubleIntegerDBIDHeap(DoubleIntegerHeap)
        +insert(double, DBIDRef): double
        +insert(double, DBIDRef, int): double
        +replaceTopElement(double, DBIDRef): void
        +poll(): void
        +size(): int
        +isEmpty(): boolean
        +clear(): void
        +peekKey(): double
        +internalGetIndex(): int
        +contains(DBIDRef): boolean
        +unorderedIterator(): DoubleDBIDIter
    }

    interface "<size:14>DoubleDBIDHeap\n<size:10>elki.database.ids" as elki.database.ids.DoubleDBIDHeap [[../DoubleDBIDHeap.html]] {
        {abstract} +peekKey(): double
        {abstract} +poll(): void
        {abstract} +insert(double, DBIDRef): double
        {abstract} +insert(double, DBIDRef, int): double
        {abstract} +size(): int
        {abstract} +clear(): void
        {abstract} +unorderedIterator(): DoubleDBIDIter
        {abstract} +contains(DBIDRef): boolean
    }
    class "<size:14>DoubleIntegerDBIDHeap.UnorderedIter\n<size:10>elki.database.ids.integer" as elki.database.ids.integer.DoubleIntegerDBIDHeap.UnorderedIter [[DoubleIntegerDBIDHeap.UnorderedIter.html]]

    elki.database.ids.DoubleDBIDHeap <|.. elki.database.ids.integer.DoubleIntegerDBIDHeap
    elki.database.ids.integer.DoubleIntegerDBIDHeap +-- elki.database.ids.integer.DoubleIntegerDBIDHeap.UnorderedIter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
