@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DoubleIntegerDBIDKNNHeap.UnorderedIter\n<size:10>elki.database.ids.integer" as elki.database.ids.integer.DoubleIntegerDBIDKNNHeap.UnorderedIter [[DoubleIntegerDBIDKNNHeap.UnorderedIter.html]] {
        -it: DoubleDBIDIter
        -t: int
        +UnorderedIter(DoubleDBIDIter)
        +internalGetIndex(): int
        +valid(): boolean
        +doubleValue(): double
        +advance(): DoubleDBIDIter
    }

    interface "<size:14>DoubleDBIDIter\n<size:10>elki.database.ids" as elki.database.ids.DoubleDBIDIter [[../DoubleDBIDIter.html]] {
        {abstract} +doubleValue(): double
        {abstract} +advance(): DoubleDBIDIter
    }
    class "<size:14>DoubleIntegerDBIDKNNHeap\n<size:10>elki.database.ids.integer" as elki.database.ids.integer.DoubleIntegerDBIDKNNHeap [[DoubleIntegerDBIDKNNHeap.html]]

    elki.database.ids.DoubleDBIDIter <|.. elki.database.ids.integer.DoubleIntegerDBIDKNNHeap.UnorderedIter
    elki.database.ids.integer.DoubleIntegerDBIDKNNHeap +-- elki.database.ids.integer.DoubleIntegerDBIDKNNHeap.UnorderedIter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
