@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>UnmodifiableIntegerDBIDs.UnmodifiableDBIDIter\n<size:10>elki.database.ids.integer" as elki.database.ids.integer.UnmodifiableIntegerDBIDs.UnmodifiableDBIDIter [[UnmodifiableIntegerDBIDs.UnmodifiableDBIDIter.html]] {
        -it: IntegerDBIDIter
        +UnmodifiableDBIDIter(IntegerDBIDIter)
        +valid(): boolean
        +advance(): DBIDIter
        +internalGetIndex(): int
    }

    interface "<size:14>IntegerDBIDIter\n<size:10>elki.database.ids.integer" as elki.database.ids.integer.IntegerDBIDIter [[IntegerDBIDIter.html]]
    class "<size:14>UnmodifiableIntegerDBIDs\n<size:10>elki.database.ids.integer" as elki.database.ids.integer.UnmodifiableIntegerDBIDs [[UnmodifiableIntegerDBIDs.html]]

    elki.database.ids.integer.IntegerDBIDIter <|.. elki.database.ids.integer.UnmodifiableIntegerDBIDs.UnmodifiableDBIDIter
    elki.database.ids.integer.UnmodifiableIntegerDBIDs +-- elki.database.ids.integer.UnmodifiableIntegerDBIDs.UnmodifiableDBIDIter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
