@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractSimpleProjection\n<size:10>elki.visualization.projections" as elki.visualization.projections.AbstractSimpleProjection [[AbstractSimpleProjection.html]] {
        +AbstractSimpleProjection(Projector, LinearScale[])
        +projectScaledToRender(double[]): double[]
        +projectRenderToScaled(double[]): double[]
        +projectRelativeScaledToRender(double[]): double[]
        +projectRelativeRenderToScaled(double[]): double[]
        #flipSecondEquals(double[]): double[]
        {abstract} #rearrange(double[]): double[]
        {abstract} #dearrange(double[]): double[]
    }

    abstract class "<size:14>AbstractFullProjection\n<size:10>elki.visualization.projections" as elki.visualization.projections.AbstractFullProjection [[AbstractFullProjection.html]]

    elki.visualization.projections.AbstractFullProjection <|-- elki.visualization.projections.AbstractSimpleProjection

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
