@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>Projection\n<size:10>elki.visualization.projections" as elki.visualization.projections.Projection [[Projection.html]] {
        {static} +SCALE: double
        {static} +INVSCALE: double
        {abstract} +getInputDimensionality(): int
        {abstract} +getScale(int): LinearScale
        {abstract} +getProjector(): Projector
    }

    interface "<size:14>VisualizationItem\n<size:10>elki.visualization" as elki.visualization.VisualizationItem [[../VisualizationItem.html]] {
        {abstract} +getMenuName(): String
    }

    elki.visualization.VisualizationItem <|-- elki.visualization.projections.Projection

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
