@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>Projection1D\n<size:10>elki.visualization.projections" as elki.visualization.projections.Projection1D [[Projection1D.html]] {
        {abstract} +fastProjectDataToRenderSpace(double[]): double
        {abstract} +fastProjectDataToRenderSpace(NumberVector): double
        {abstract} +fastProjectScaledToRender(double[]): double
        {abstract} +fastProjectRelativeDataToRenderSpace(double[]): double
        {abstract} +fastProjectRelativeDataToRenderSpace(NumberVector): double
        {abstract} +fastProjectRelativeScaledToRender(double[]): double
    }

    interface "<size:14>Projection\n<size:10>elki.visualization.projections" as elki.visualization.projections.Projection [[Projection.html]] {
        {abstract} +getInputDimensionality(): int
        {abstract} +getScale(int): LinearScale
        {abstract} +getProjector(): Projector
    }

    elki.visualization.projections.Projection <|-- elki.visualization.projections.Projection1D

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
