@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SmallDenseItemset\n<size:10>elki.itemsetmining" as elki.itemsetmining.SmallDenseItemset [[SmallDenseItemset.html]] {
        ~items: long
        ~length: int
        +SmallDenseItemset(long, int)
        +length(): int
        +containedIn(SparseNumberVector): boolean
        +iter(): int
        +iterValid(int): boolean
        +iterAdvance(int): int
        +iterDim(int): int
        +compareTo(Itemset): int
        +appendItemsTo(StringBuilder, VectorFieldTypeInformation<BitVector>): StringBuilder
    }

    abstract class "<size:14>Itemset\n<size:10>elki.itemsetmining" as elki.itemsetmining.Itemset [[Itemset.html]] {
        {abstract} +length(): int
        {abstract} +iter(): int
        {abstract} +iterAdvance(int): int
        {abstract} +iterValid(int): boolean
        {abstract} +iterDim(int): int
    }

    elki.itemsetmining.Itemset <|-- elki.itemsetmining.SmallDenseItemset

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
