@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SparseItemset\n<size:10>elki.itemsetmining" as elki.itemsetmining.SparseItemset [[SparseItemset.html]] {
        ~indices: int[]
        +SparseItemset(int[])
        +SparseItemset(int[], int)
        +SparseItemset(OneItemset, OneItemset)
        +length(): int
        +iter(): int
        +iterValid(int): boolean
        +iterAdvance(int): int
        +iterDim(int): int
        +compareTo(Itemset): int
        +prefixTest(SparseItemset): boolean
    }

    abstract class "<size:14>Itemset\n<size:10>elki.itemsetmining" as elki.itemsetmining.Itemset [[Itemset.html]] {
        {abstract} +length(): int
        {abstract} +iter(): int
        {abstract} +iterAdvance(int): int
        {abstract} +iterValid(int): boolean
        {abstract} +iterDim(int): int
    }

    elki.itemsetmining.Itemset <|-- elki.itemsetmining.SparseItemset

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
