@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractProjectedHashFunctionFamily.Par\n<size:10>elki.index.lsh.hashfamilies" as elki.index.lsh.hashfamilies.AbstractProjectedHashFunctionFamily.Par [[AbstractProjectedHashFunctionFamily.Par.html]] {
        {static} +RANDOM_ID: OptionID
        {static} +WIDTH_ID: OptionID
        {static} +NUMPROJ_ID: OptionID
        ~random: RandomFactory
        ~width: double
        ~k: int
        +configure(Parameterization): void
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    abstract class "<size:14>AbstractProjectedHashFunctionFamily\n<size:10>elki.index.lsh.hashfamilies" as elki.index.lsh.hashfamilies.AbstractProjectedHashFunctionFamily [[AbstractProjectedHashFunctionFamily.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.index.lsh.hashfamilies.AbstractProjectedHashFunctionFamily.Par
    elki.index.lsh.hashfamilies.AbstractProjectedHashFunctionFamily +-- elki.index.lsh.hashfamilies.AbstractProjectedHashFunctionFamily.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
