@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>OneDimSortBulkSplit\n<size:10>elki.index.tree.spatial.rstarvariants.strategies.bulk" as elki.index.tree.spatial.rstarvariants.strategies.bulk.OneDimSortBulkSplit [[OneDimSortBulkSplit.html]] {
        {static} +STATIC: OneDimSortBulkSplit
        +partition(List<T extends SpatialComparable>, int, int): List<List<T extends SpatialComparable>>
    }

    abstract class "<size:14>AbstractBulkSplit\n<size:10>elki.index.tree.spatial.rstarvariants.strategies.bulk" as elki.index.tree.spatial.rstarvariants.strategies.bulk.AbstractBulkSplit [[AbstractBulkSplit.html]]
    class "<size:14>OneDimSortBulkSplit.Par\n<size:10>elki.index.tree.spatial.rstarvariants.strategies.bulk" as elki.index.tree.spatial.rstarvariants.strategies.bulk.OneDimSortBulkSplit.Par [[OneDimSortBulkSplit.Par.html]]

    elki.index.tree.spatial.rstarvariants.strategies.bulk.AbstractBulkSplit <|-- elki.index.tree.spatial.rstarvariants.strategies.bulk.OneDimSortBulkSplit
    elki.index.tree.spatial.rstarvariants.strategies.bulk.OneDimSortBulkSplit +-- elki.index.tree.spatial.rstarvariants.strategies.bulk.OneDimSortBulkSplit.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
