@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SpatialSortBulkSplit.Par\n<size:10>elki.index.tree.spatial.rstarvariants.strategies.bulk" as elki.index.tree.spatial.rstarvariants.strategies.bulk.SpatialSortBulkSplit.Par [[SpatialSortBulkSplit.Par.html]] {
        {static} +SORTER_ID: OptionID
        ~sorter: SpatialSorter
        +configure(Parameterization): void
        +make(): SpatialSortBulkSplit
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>SpatialSortBulkSplit\n<size:10>elki.index.tree.spatial.rstarvariants.strategies.bulk" as elki.index.tree.spatial.rstarvariants.strategies.bulk.SpatialSortBulkSplit [[SpatialSortBulkSplit.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.index.tree.spatial.rstarvariants.strategies.bulk.SpatialSortBulkSplit.Par
    elki.index.tree.spatial.rstarvariants.strategies.bulk.SpatialSortBulkSplit +-- elki.index.tree.spatial.rstarvariants.strategies.bulk.SpatialSortBulkSplit.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
