@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AFKMC2.Instance\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.AFKMC2.Instance [[AFKMC2.Instance.html]] {
        +Instance(Relation<? extends NumberVector>, NumberVectorDistance<?>, int, RandomFactory)
        #sample(double): DBIDRef
        #getLogger(): Logging
    }

    class "<size:14>KMC2.Instance\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.KMC2.Instance [[KMC2.Instance.html]]
    class "<size:14>AFKMC2\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.AFKMC2 [[AFKMC2.html]]

    elki.clustering.kmeans.initialization.KMC2.Instance <|-- elki.clustering.kmeans.initialization.AFKMC2.Instance
    elki.clustering.kmeans.initialization.AFKMC2 +-- elki.clustering.kmeans.initialization.AFKMC2.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
