@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>FarthestSumPoints.Par\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.FarthestSumPoints.Par<V> [[FarthestSumPoints.Par.html]] {
        +make(): FarthestSumPoints<V>
    }

    class "<size:14>FarthestPoints.Par\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.FarthestPoints.Par<V> [[FarthestPoints.Par.html]]
    class "<size:14>FarthestSumPoints\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.FarthestSumPoints<O> [[FarthestSumPoints.html]]

    elki.clustering.kmeans.initialization.FarthestPoints.Par <|-- elki.clustering.kmeans.initialization.FarthestSumPoints.Par
    elki.clustering.kmeans.initialization.FarthestSumPoints +-- elki.clustering.kmeans.initialization.FarthestSumPoints.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
