@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>FirstK\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.FirstK<O> [[FirstK.html]] {
        +chooseInitialMeans(Relation<? extends NumberVector>, int, NumberVectorDistance<?>): double[]
        +chooseInitialMedoids(int, DBIDs, DistanceQuery<? super O>): DBIDs
    }

    interface "<size:14>KMeansInitialization\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.KMeansInitialization [[KMeansInitialization.html]] {
        {abstract} +chooseInitialMeans(Relation<? extends NumberVector>, int, NumberVectorDistance<?>): double[]
    }
    interface "<size:14>KMedoidsInitialization\n<size:10>elki.clustering.kmedoids.initialization" as elki.clustering.kmedoids.initialization.KMedoidsInitialization<O> [[../../kmedoids/initialization/KMedoidsInitialization.html]] {
        {abstract} +chooseInitialMedoids(int, DBIDs, DistanceQuery<? super O>): DBIDs
    }
    class "<size:14>FirstK.Par\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.FirstK.Par<V extends NumberVector> [[FirstK.Par.html]]

    elki.clustering.kmeans.initialization.KMeansInitialization <|.. elki.clustering.kmeans.initialization.FirstK
    elki.clustering.kmedoids.initialization.KMedoidsInitialization <|.. elki.clustering.kmeans.initialization.FirstK
    elki.clustering.kmeans.initialization.FirstK +-- elki.clustering.kmeans.initialization.FirstK.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
