@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>KMC2.Par\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.KMC2.Par [[KMC2.Par.html]] {
        {static} +M_ID: OptionID
        #m: int
        +configure(Parameterization): void
        +make(): KMC2
    }

    abstract class "<size:14>AbstractKMeansInitialization.Par\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.AbstractKMeansInitialization.Par [[AbstractKMeansInitialization.Par.html]]
    class "<size:14>KMC2\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.KMC2 [[KMC2.html]]

    elki.clustering.kmeans.initialization.AbstractKMeansInitialization.Par <|-- elki.clustering.kmeans.initialization.KMC2.Par
    elki.clustering.kmeans.initialization.KMC2 +-- elki.clustering.kmeans.initialization.KMC2.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
