@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RandomNormalGenerated.Par\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.RandomNormalGenerated.Par [[RandomNormalGenerated.Par.html]] {
        +make(): RandomNormalGenerated
    }

    abstract class "<size:14>AbstractKMeansInitialization.Par\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.AbstractKMeansInitialization.Par [[AbstractKMeansInitialization.Par.html]]
    class "<size:14>RandomNormalGenerated\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.RandomNormalGenerated [[RandomNormalGenerated.html]]

    elki.clustering.kmeans.initialization.AbstractKMeansInitialization.Par <|-- elki.clustering.kmeans.initialization.RandomNormalGenerated.Par
    elki.clustering.kmeans.initialization.RandomNormalGenerated +-- elki.clustering.kmeans.initialization.RandomNormalGenerated.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
