@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RandomlyChosen.Par\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.RandomlyChosen.Par<V> [[RandomlyChosen.Par.html]] {
        +make(): RandomlyChosen<V>
    }

    abstract class "<size:14>AbstractKMeansInitialization.Par\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.AbstractKMeansInitialization.Par [[AbstractKMeansInitialization.Par.html]]
    class "<size:14>RandomlyChosen\n<size:10>elki.clustering.kmeans.initialization" as elki.clustering.kmeans.initialization.RandomlyChosen<O> [[RandomlyChosen.html]]

    elki.clustering.kmeans.initialization.AbstractKMeansInitialization.Par <|-- elki.clustering.kmeans.initialization.RandomlyChosen.Par
    elki.clustering.kmeans.initialization.RandomlyChosen +-- elki.clustering.kmeans.initialization.RandomlyChosen.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
