@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>COPOutlierScaling.Par\n<size:10>elki.utilities.scaling.outlier" as elki.utilities.scaling.outlier.COPOutlierScaling.Par [[COPOutlierScaling.Par.html]] {
        {static} +PHI_ID: OptionID
        -phi: double
        +configure(Parameterization): void
        +make(): COPOutlierScaling
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>COPOutlierScaling\n<size:10>elki.utilities.scaling.outlier" as elki.utilities.scaling.outlier.COPOutlierScaling [[COPOutlierScaling.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.utilities.scaling.outlier.COPOutlierScaling.Par
    elki.utilities.scaling.outlier.COPOutlierScaling +-- elki.utilities.scaling.outlier.COPOutlierScaling.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
