@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MinusLogStandardDeviationScaling.Par\n<size:10>elki.utilities.scaling.outlier" as elki.utilities.scaling.outlier.MinusLogStandardDeviationScaling.Par [[MinusLogStandardDeviationScaling.Par.html]] {
        +make(): MinusLogStandardDeviationScaling
    }

    class "<size:14>StandardDeviationScaling.Par\n<size:10>elki.utilities.scaling.outlier" as elki.utilities.scaling.outlier.StandardDeviationScaling.Par [[StandardDeviationScaling.Par.html]]
    class "<size:14>MinusLogStandardDeviationScaling\n<size:10>elki.utilities.scaling.outlier" as elki.utilities.scaling.outlier.MinusLogStandardDeviationScaling [[MinusLogStandardDeviationScaling.html]]

    elki.utilities.scaling.outlier.StandardDeviationScaling.Par <|-- elki.utilities.scaling.outlier.MinusLogStandardDeviationScaling.Par
    elki.utilities.scaling.outlier.MinusLogStandardDeviationScaling +-- elki.utilities.scaling.outlier.MinusLogStandardDeviationScaling.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
