@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SqrtStandardDeviationScaling\n<size:10>elki.utilities.scaling.outlier" as elki.utilities.scaling.outlier.SqrtStandardDeviationScaling [[SqrtStandardDeviationScaling.html]] {
        ~min: double
        ~mean: double
        ~factor: double
        ~pmin: double
        ~pmean: double
        ~plambda: double
        +SqrtStandardDeviationScaling(double, double, double)
        +getScaled(double): double
        +prepare(OutlierResult): void
        +prepare(A, NumberArrayAdapter<?, A>): void
        +getMin(): double
        +getMax(): double
    }

    interface "<size:14>OutlierScaling\n<size:10>elki.utilities.scaling.outlier" as elki.utilities.scaling.outlier.OutlierScaling [[OutlierScaling.html]] {
        {abstract} +prepare(OutlierResult): void
        {abstract} +prepare(A, NumberArrayAdapter<?, A>): void
    }
    class "<size:14>SqrtStandardDeviationScaling.Par\n<size:10>elki.utilities.scaling.outlier" as elki.utilities.scaling.outlier.SqrtStandardDeviationScaling.Par [[SqrtStandardDeviationScaling.Par.html]]

    elki.utilities.scaling.outlier.OutlierScaling <|.. elki.utilities.scaling.outlier.SqrtStandardDeviationScaling
    elki.utilities.scaling.outlier.SqrtStandardDeviationScaling +-- elki.utilities.scaling.outlier.SqrtStandardDeviationScaling.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
