@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>StandardDeviationScaling\n<size:10>elki.utilities.scaling.outlier" as elki.utilities.scaling.outlier.StandardDeviationScaling [[StandardDeviationScaling.html]] {
        #fixedmean: double
        #lambda: double
        ~mean: double
        ~factor: double
        +StandardDeviationScaling(double, double)
        +StandardDeviationScaling()
        +getScaled(double): double
        +prepare(OutlierResult): void
        +prepare(A, NumberArrayAdapter<?, A>): void
        +getMin(): double
        +getMax(): double
    }

    interface "<size:14>OutlierScaling\n<size:10>elki.utilities.scaling.outlier" as elki.utilities.scaling.outlier.OutlierScaling [[OutlierScaling.html]] {
        {abstract} +prepare(OutlierResult): void
        {abstract} +prepare(A, NumberArrayAdapter<?, A>): void
    }
    class "<size:14>StandardDeviationScaling.Par\n<size:10>elki.utilities.scaling.outlier" as elki.utilities.scaling.outlier.StandardDeviationScaling.Par [[StandardDeviationScaling.Par.html]]

    elki.utilities.scaling.outlier.OutlierScaling <|.. elki.utilities.scaling.outlier.StandardDeviationScaling
    elki.utilities.scaling.outlier.StandardDeviationScaling +-- elki.utilities.scaling.outlier.StandardDeviationScaling.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
