@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>StreamingParser\n<size:10>elki.datasource.parser" as elki.datasource.parser.StreamingParser [[StreamingParser.html]] {
        {abstract} +initStream(InputStream): void
    }

    interface "<size:14>Parser\n<size:10>elki.datasource.parser" as elki.datasource.parser.Parser [[Parser.html]] {
        {abstract} +parse(InputStream): MultipleObjectsBundle
        {abstract} +cleanup(): void
    }
    interface "<size:14>BundleStreamSource\n<size:10>elki.datasource.bundle" as elki.datasource.bundle.BundleStreamSource [[../bundle/BundleStreamSource.html]] {
        {abstract} +getMeta(): BundleMeta
        {abstract} +data(int): Object
        {abstract} +hasDBIDs(): boolean
        {abstract} +assignDBID(DBIDVar): boolean
        {abstract} +nextEvent(): Event
        {abstract} +asMultipleObjectsBundle(): MultipleObjectsBundle
    }

    elki.datasource.parser.Parser <|-- elki.datasource.parser.StreamingParser
    elki.datasource.bundle.BundleStreamSource <|-- elki.datasource.parser.StreamingParser

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
