@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>TermFrequencyParser.Par\n<size:10>elki.datasource.parser" as elki.datasource.parser.TermFrequencyParser.Par<V extends SparseNumberVector> [[TermFrequencyParser.Par.html]] {
        {static} +NORMALIZE_FLAG: OptionID
        ~normalize: boolean
        +configure(Parameterization): void
        #getFactory(Parameterization): void
        +make(): TermFrequencyParser<V extends SparseNumberVector>
    }

    class "<size:14>NumberVectorLabelParser.Par\n<size:10>elki.datasource.parser" as elki.datasource.parser.NumberVectorLabelParser.Par<V extends SparseNumberVector> [[NumberVectorLabelParser.Par.html]]
    class "<size:14>TermFrequencyParser\n<size:10>elki.datasource.parser" as elki.datasource.parser.TermFrequencyParser<V extends SparseNumberVector> [[TermFrequencyParser.html]]

    elki.datasource.parser.NumberVectorLabelParser.Par <|-- elki.datasource.parser.TermFrequencyParser.Par
    elki.datasource.parser.TermFrequencyParser +-- elki.datasource.parser.TermFrequencyParser.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
