@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>Counter\n<size:10>elki.logging.statistics" as elki.logging.statistics.Counter [[Counter.html]] {
        {abstract} +increment(): long
        {abstract} +decrement(): long
        {abstract} +getValue(): long
        {abstract} +increment(long): long
    }

    interface "<size:14>Statistic\n<size:10>elki.logging.statistics" as elki.logging.statistics.Statistic [[Statistic.html]] {
        {abstract} +getKey(): String
        {abstract} +formatValue(): String
    }

    elki.logging.statistics.Statistic <|-- elki.logging.statistics.Counter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
