@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DistanceFunctionVisualization\n<size:10>elki.visualization.visualizers.scatterplot.selection" as elki.visualization.visualizers.scatterplot.selection.DistanceFunctionVisualization [[DistanceFunctionVisualization.html]] {
        {static} +NAME: String
        +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
        +processNewResult(VisualizerContext, Object): void
        {static} +getLPNormP(AbstractMaterializeKNNPreprocessor<?>): double
        {static} +isAngularDistance(AbstractMaterializeKNNPreprocessor<?>): boolean
        {static} +drawCosine(SVGPlot, Projection2D, NumberVector, double): Element
    }

    interface "<size:14>VisFactory\n<size:10>elki.visualization.visualizers" as elki.visualization.visualizers.VisFactory [[../../VisFactory.html]] {
        {abstract} +processNewResult(VisualizerContext, Object): void
        {abstract} +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
    }
    class "<size:14>DistanceFunctionVisualization.Instance\n<size:10>elki.visualization.visualizers.scatterplot.selection" as elki.visualization.visualizers.scatterplot.selection.DistanceFunctionVisualization.Instance [[DistanceFunctionVisualization.Instance.html]]

    elki.visualization.visualizers.VisFactory <|.. elki.visualization.visualizers.scatterplot.selection.DistanceFunctionVisualization
    elki.visualization.visualizers.scatterplot.selection.DistanceFunctionVisualization +-- elki.visualization.visualizers.scatterplot.selection.DistanceFunctionVisualization.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
