@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DistanceFunctionVisualization.Instance\n<size:10>elki.visualization.visualizers.scatterplot.selection" as elki.visualization.visualizers.scatterplot.selection.DistanceFunctionVisualization.Instance [[DistanceFunctionVisualization.Instance.html]] {
        {static} +KNNMARKER: String
        {static} +KNNDIST: String
        {static} +DISTANCEFUNCTION: String
        -result: AbstractMaterializeKNNPreprocessor<? extends NumberVector>
        +Instance(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection)
        +fullRedraw(): void
        -addCSSClasses(SVGPlot): void
    }

    abstract class "<size:14>AbstractScatterplotVisualization\n<size:10>elki.visualization.visualizers.scatterplot" as elki.visualization.visualizers.scatterplot.AbstractScatterplotVisualization [[../AbstractScatterplotVisualization.html]]
    interface "<size:14>DataStoreListener\n<size:10>elki.database.datastore" as elki.database.datastore.DataStoreListener [[../../../../database/datastore/DataStoreListener.html]] {
        {abstract} +contentChanged(DataStoreEvent): void
    }
    class "<size:14>DistanceFunctionVisualization\n<size:10>elki.visualization.visualizers.scatterplot.selection" as elki.visualization.visualizers.scatterplot.selection.DistanceFunctionVisualization [[DistanceFunctionVisualization.html]]

    elki.visualization.visualizers.scatterplot.AbstractScatterplotVisualization <|-- elki.visualization.visualizers.scatterplot.selection.DistanceFunctionVisualization.Instance
    elki.database.datastore.DataStoreListener <|.. elki.visualization.visualizers.scatterplot.selection.DistanceFunctionVisualization.Instance
    elki.visualization.visualizers.scatterplot.selection.DistanceFunctionVisualization +-- elki.visualization.visualizers.scatterplot.selection.DistanceFunctionVisualization.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
