@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SelectionCubeVisualization.Instance\n<size:10>elki.visualization.visualizers.scatterplot.selection" as elki.visualization.visualizers.scatterplot.selection.SelectionCubeVisualization.Instance [[SelectionCubeVisualization.Instance.html]] {
        {static} +MARKER: String
        {static} +CSS_CUBE: String
        {static} +CSS_CUBEFRAME: String
        +Instance(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection)
        -addCSSClasses(SVGPlot): void
        -setSVGRect(SVGPlot, Projection2D): void
        +fullRedraw(): void
    }

    abstract class "<size:14>AbstractScatterplotVisualization\n<size:10>elki.visualization.visualizers.scatterplot" as elki.visualization.visualizers.scatterplot.AbstractScatterplotVisualization [[../AbstractScatterplotVisualization.html]]
    class "<size:14>SelectionCubeVisualization\n<size:10>elki.visualization.visualizers.scatterplot.selection" as elki.visualization.visualizers.scatterplot.selection.SelectionCubeVisualization [[SelectionCubeVisualization.html]]

    elki.visualization.visualizers.scatterplot.AbstractScatterplotVisualization <|-- elki.visualization.visualizers.scatterplot.selection.SelectionCubeVisualization.Instance
    elki.visualization.visualizers.scatterplot.selection.SelectionCubeVisualization +-- elki.visualization.visualizers.scatterplot.selection.SelectionCubeVisualization.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
