@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>Parameterization\n<size:10>elki.utilities.optionhandling.parameterization" as elki.utilities.optionhandling.parameterization.Parameterization [[Parameterization.html]] {
        +grab(Parameter<?>): boolean
        {abstract} +setValueForOption(Parameter<?>): boolean
        {abstract} +getErrors(): Collection<ParameterException>
        {abstract} +reportError(ParameterException): void
        {abstract} +hasUnusedParameters(): boolean
        +descend(Object): Parameterization
        +hasErrors(): boolean
        +tryInstantiate(Class<C>): C
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
