@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ClusterOrderVisualization.Instance\n<size:10>elki.visualization.visualizers.scatterplot.cluster" as elki.visualization.visualizers.scatterplot.cluster.ClusterOrderVisualization.Instance [[ClusterOrderVisualization.Instance.html]] {
        {static} -CSSNAME: String
        #result: ClusterOrder
        #order: boolean
        +Instance(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection)
        +fullRedraw(): void
    }

    abstract class "<size:14>AbstractScatterplotVisualization\n<size:10>elki.visualization.visualizers.scatterplot" as elki.visualization.visualizers.scatterplot.AbstractScatterplotVisualization [[../AbstractScatterplotVisualization.html]]
    interface "<size:14>DataStoreListener\n<size:10>elki.database.datastore" as elki.database.datastore.DataStoreListener [[../../../../database/datastore/DataStoreListener.html]] {
        {abstract} +contentChanged(DataStoreEvent): void
    }
    class "<size:14>ClusterOrderVisualization\n<size:10>elki.visualization.visualizers.scatterplot.cluster" as elki.visualization.visualizers.scatterplot.cluster.ClusterOrderVisualization [[ClusterOrderVisualization.html]]

    elki.visualization.visualizers.scatterplot.AbstractScatterplotVisualization <|-- elki.visualization.visualizers.scatterplot.cluster.ClusterOrderVisualization.Instance
    elki.database.datastore.DataStoreListener <|.. elki.visualization.visualizers.scatterplot.cluster.ClusterOrderVisualization.Instance
    elki.visualization.visualizers.scatterplot.cluster.ClusterOrderVisualization +-- elki.visualization.visualizers.scatterplot.cluster.ClusterOrderVisualization.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
