@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ClusterConvexHullVisualization.Par\n<size:10>elki.visualization.visualizers.scatterplot.cluster" as elki.visualization.visualizers.scatterplot.cluster.ClusterConvexHullVisualization.Par [[ClusterConvexHullVisualization.Par.html]] {
        +make(): ClusterConvexHullVisualization
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>ClusterConvexHullVisualization\n<size:10>elki.visualization.visualizers.scatterplot.cluster" as elki.visualization.visualizers.scatterplot.cluster.ClusterConvexHullVisualization [[ClusterConvexHullVisualization.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.visualization.visualizers.scatterplot.cluster.ClusterConvexHullVisualization.Par
    elki.visualization.visualizers.scatterplot.cluster.ClusterConvexHullVisualization +-- elki.visualization.visualizers.scatterplot.cluster.ClusterConvexHullVisualization.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
