@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>JensenShannonEquiwidthDependence\n<size:10>elki.math.statistics.dependence" as elki.math.statistics.dependence.JensenShannonEquiwidthDependence [[JensenShannonEquiwidthDependence.html]] {
        {static} +STATIC: JensenShannonEquiwidthDependence
        +dependence(NumberArrayAdapter<?, A>, A, NumberArrayAdapter<?, B>, B): double
    }

    interface "<size:14>Dependence\n<size:10>elki.math.statistics.dependence" as elki.math.statistics.dependence.Dependence [[Dependence.html]] {
        {abstract} +dependence(NumberArrayAdapter<?, A>, A, NumberArrayAdapter<?, B>, B): double
    }
    class "<size:14>JensenShannonEquiwidthDependence.Par\n<size:10>elki.math.statistics.dependence" as elki.math.statistics.dependence.JensenShannonEquiwidthDependence.Par [[JensenShannonEquiwidthDependence.Par.html]]

    elki.math.statistics.dependence.Dependence <|.. elki.math.statistics.dependence.JensenShannonEquiwidthDependence
    elki.math.statistics.dependence.JensenShannonEquiwidthDependence +-- elki.math.statistics.dependence.JensenShannonEquiwidthDependence.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
