@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CFRandomlyChosen.Par\n<size:10>elki.clustering.kmeans.initialization.betula" as elki.clustering.kmeans.initialization.betula.CFRandomlyChosen.Par [[CFRandomlyChosen.Par.html]] {
        +make(): CFRandomlyChosen
    }

    abstract class "<size:14>AbstractCFKMeansInitialization.Par\n<size:10>elki.clustering.kmeans.initialization.betula" as elki.clustering.kmeans.initialization.betula.AbstractCFKMeansInitialization.Par [[AbstractCFKMeansInitialization.Par.html]]
    class "<size:14>CFRandomlyChosen\n<size:10>elki.clustering.kmeans.initialization.betula" as elki.clustering.kmeans.initialization.betula.CFRandomlyChosen [[CFRandomlyChosen.html]]

    elki.clustering.kmeans.initialization.betula.AbstractCFKMeansInitialization.Par <|-- elki.clustering.kmeans.initialization.betula.CFRandomlyChosen.Par
    elki.clustering.kmeans.initialization.betula.CFRandomlyChosen +-- elki.clustering.kmeans.initialization.betula.CFRandomlyChosen.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
