@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CFWeightedRandomlyChosen\n<size:10>elki.clustering.kmeans.initialization.betula" as elki.clustering.kmeans.initialization.betula.CFWeightedRandomlyChosen [[CFWeightedRandomlyChosen.html]] {
        +CFWeightedRandomlyChosen(RandomFactory)
        +chooseInitialMeans(CFTree<?>, List<? extends ClusterFeature>, int): double[]
    }

    abstract class "<size:14>AbstractCFKMeansInitialization\n<size:10>elki.clustering.kmeans.initialization.betula" as elki.clustering.kmeans.initialization.betula.AbstractCFKMeansInitialization [[AbstractCFKMeansInitialization.html]] {
        {abstract} +chooseInitialMeans(CFTree<?>, List<? extends ClusterFeature>, int): double[]
    }
    class "<size:14>CFWeightedRandomlyChosen.Par\n<size:10>elki.clustering.kmeans.initialization.betula" as elki.clustering.kmeans.initialization.betula.CFWeightedRandomlyChosen.Par [[CFWeightedRandomlyChosen.Par.html]]

    elki.clustering.kmeans.initialization.betula.AbstractCFKMeansInitialization <|-- elki.clustering.kmeans.initialization.betula.CFWeightedRandomlyChosen
    elki.clustering.kmeans.initialization.betula.CFWeightedRandomlyChosen +-- elki.clustering.kmeans.initialization.betula.CFWeightedRandomlyChosen.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
