@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CFWeightedRandomlyChosen.Par\n<size:10>elki.clustering.kmeans.initialization.betula" as elki.clustering.kmeans.initialization.betula.CFWeightedRandomlyChosen.Par [[CFWeightedRandomlyChosen.Par.html]] {
        +make(): CFWeightedRandomlyChosen
    }

    abstract class "<size:14>AbstractCFKMeansInitialization.Par\n<size:10>elki.clustering.kmeans.initialization.betula" as elki.clustering.kmeans.initialization.betula.AbstractCFKMeansInitialization.Par [[AbstractCFKMeansInitialization.Par.html]]
    class "<size:14>CFWeightedRandomlyChosen\n<size:10>elki.clustering.kmeans.initialization.betula" as elki.clustering.kmeans.initialization.betula.CFWeightedRandomlyChosen [[CFWeightedRandomlyChosen.html]]

    elki.clustering.kmeans.initialization.betula.AbstractCFKMeansInitialization.Par <|-- elki.clustering.kmeans.initialization.betula.CFWeightedRandomlyChosen.Par
    elki.clustering.kmeans.initialization.betula.CFWeightedRandomlyChosen +-- elki.clustering.kmeans.initialization.betula.CFWeightedRandomlyChosen.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
