@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SquaredEuclideanWeight\n<size:10>elki.clustering.kmeans.initialization.betula" as elki.clustering.kmeans.initialization.betula.SquaredEuclideanWeight [[SquaredEuclideanWeight.html]] {
        +squaredWeight(ClusterFeature, ClusterFeature): double
    }

    interface "<size:14>CFInitWeight\n<size:10>elki.clustering.kmeans.initialization.betula" as elki.clustering.kmeans.initialization.betula.CFInitWeight [[CFInitWeight.html]] {
        {abstract} +squaredWeight(ClusterFeature, ClusterFeature): double
    }

    elki.clustering.kmeans.initialization.betula.CFInitWeight <|.. elki.clustering.kmeans.initialization.betula.SquaredEuclideanWeight

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
