@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LoggingStep\n<size:10>elki.workflow" as elki.workflow.LoggingStep [[LoggingStep.html]] {
        +LoggingStep(Level, String[])
    }

    interface "<size:14>WorkflowStep\n<size:10>elki.workflow" as elki.workflow.WorkflowStep [[WorkflowStep.html]]
    class "<size:14>LoggingStep.Par\n<size:10>elki.workflow" as elki.workflow.LoggingStep.Par [[LoggingStep.Par.html]]

    elki.workflow.WorkflowStep <|.. elki.workflow.LoggingStep
    elki.workflow.LoggingStep +-- elki.workflow.LoggingStep.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
