@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>OutputStep.Par\n<size:10>elki.workflow" as elki.workflow.OutputStep.Par [[OutputStep.Par.html]] {
        -resulthandlers: List<? extends ResultHandler>
        {static} +RESULT_HANDLER_ID: OptionID
        {static} +OUTPUT_ID: OptionID
        +configure(Parameterization): void
        +make(): OutputStep
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>OutputStep\n<size:10>elki.workflow" as elki.workflow.OutputStep [[OutputStep.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.workflow.OutputStep.Par
    elki.workflow.OutputStep +-- elki.workflow.OutputStep.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
