@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AddUniformScale\n<size:10>elki.algorithm.statistics" as elki.algorithm.statistics.AddUniformScale [[AddUniformScale.html]] {
        +run(Database): Void
        -run(Relation<? extends NumberVector>): ScalesResult
        +getInputTypeRestriction(): TypeInformation[]
    }

    interface "<size:14>Algorithm\n<size:10>elki" as elki.Algorithm [[../../Algorithm.html]] {
        {abstract} +getInputTypeRestriction(): TypeInformation[]
    }

    elki.Algorithm <|.. elki.algorithm.statistics.AddUniformScale

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
