@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DistanceQuantileSampler\n<size:10>elki.algorithm.statistics" as elki.algorithm.statistics.DistanceQuantileSampler<O> [[DistanceQuantileSampler.html]] {
        {static} -LOG: Logging
        {static} -PREFIX: String
        -distance: Distance<? super O>
        -quantile: double
        -sampling: double
        -nozeros: boolean
        -rand: RandomFactory
        +DistanceQuantileSampler(Distance<? super O>, double, double, boolean, RandomFactory)
        +getInputTypeRestriction(): TypeInformation[]
        +run(Relation<O>): CollectionResult<double[]>
    }

    interface "<size:14>Algorithm\n<size:10>elki" as elki.Algorithm [[../../Algorithm.html]] {
        {abstract} +getInputTypeRestriction(): TypeInformation[]
    }
    class "<size:14>DistanceQuantileSampler.Par\n<size:10>elki.algorithm.statistics" as elki.algorithm.statistics.DistanceQuantileSampler.Par<O> [[DistanceQuantileSampler.Par.html]]

    elki.Algorithm <|.. elki.algorithm.statistics.DistanceQuantileSampler
    elki.algorithm.statistics.DistanceQuantileSampler +-- elki.algorithm.statistics.DistanceQuantileSampler.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
