@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>EvaluateRetrievalPerformance.Par\n<size:10>elki.algorithm.statistics" as elki.algorithm.statistics.EvaluateRetrievalPerformance.Par<O> {
        {static} +SAMPLING_ID: OptionID
        {static} +SEED_ID: OptionID
        {static} +INCLUDESELF_ID: OptionID
        {static} +MAXK_ID: OptionID
        #distance: Distance<? super O>
        #sampling: double
        #seed: RandomFactory
        #includeSelf: boolean
        #maxk: int
        +configure(Parameterization): void
        +make(): EvaluateRetrievalPerformance<O>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>EvaluateRetrievalPerformance\n<size:10>elki.algorithm.statistics" as elki.algorithm.statistics.EvaluateRetrievalPerformance<O> [[EvaluateRetrievalPerformance.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.algorithm.statistics.EvaluateRetrievalPerformance.Par
    elki.algorithm.statistics.EvaluateRetrievalPerformance +-- elki.algorithm.statistics.EvaluateRetrievalPerformance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
