@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SphericalHaversineEarthModel.Par\n<size:10>elki.math.geodesy" as elki.math.geodesy.SphericalHaversineEarthModel.Par [[SphericalHaversineEarthModel.Par.html]] {
        +make(): SphericalHaversineEarthModel
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>SphericalHaversineEarthModel\n<size:10>elki.math.geodesy" as elki.math.geodesy.SphericalHaversineEarthModel [[SphericalHaversineEarthModel.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.math.geodesy.SphericalHaversineEarthModel.Par
    elki.math.geodesy.SphericalHaversineEarthModel +-- elki.math.geodesy.SphericalHaversineEarthModel.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
