@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RTreeParallelVisualization.Par\n<size:10>elki.visualization.visualizers.parallel.index" as elki.visualization.visualizers.parallel.index.RTreeParallelVisualization.Par [[RTreeParallelVisualization.Par.html]] {
        #fill: boolean
        +configure(Parameterization): void
        +make(): RTreeParallelVisualization
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>RTreeParallelVisualization\n<size:10>elki.visualization.visualizers.parallel.index" as elki.visualization.visualizers.parallel.index.RTreeParallelVisualization [[RTreeParallelVisualization.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.visualization.visualizers.parallel.index.RTreeParallelVisualization.Par
    elki.visualization.visualizers.parallel.index.RTreeParallelVisualization +-- elki.visualization.visualizers.parallel.index.RTreeParallelVisualization.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
