@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractStaticHistogram.Iter\n<size:10>elki.utilities.datastructures.histogram" as elki.utilities.datastructures.histogram.AbstractStaticHistogram.Iter [[AbstractStaticHistogram.Iter.html]] {
        ~bin: int
        +getCenter(): double
        +getLeft(): double
        +getRight(): double
        +valid(): boolean
        +advance(): Iter
        +getOffset(): int
        +advance(int): Iter
        +retract(): Iter
        +seek(int): Iter
    }

    interface "<size:14>Histogram.Iter\n<size:10>elki.utilities.datastructures.histogram" as elki.utilities.datastructures.histogram.Histogram.Iter [[Histogram.Iter.html]] {
        {abstract} +getCenter(): double
        {abstract} +getLeft(): double
        {abstract} +getRight(): double
    }
    abstract class "<size:14>AbstractStaticHistogram\n<size:10>elki.utilities.datastructures.histogram" as elki.utilities.datastructures.histogram.AbstractStaticHistogram [[AbstractStaticHistogram.html]] {
        {abstract} +iter(): Iter
    }

    elki.utilities.datastructures.histogram.Histogram.Iter <|.. elki.utilities.datastructures.histogram.AbstractStaticHistogram.Iter
    elki.utilities.datastructures.histogram.AbstractStaticHistogram +-- elki.utilities.datastructures.histogram.AbstractStaticHistogram.Iter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
