@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DoubleHistogram.Iter\n<size:10>elki.utilities.datastructures.histogram" as elki.utilities.datastructures.histogram.DoubleHistogram.Iter [[DoubleHistogram.Iter.html]] {
        +getValue(): double
        +advance(): Iter
        +advance(int): Iter
        +retract(): Iter
        +seek(int): Iter
    }

    abstract class "<size:14>AbstractStaticHistogram.Iter\n<size:10>elki.utilities.datastructures.histogram" as elki.utilities.datastructures.histogram.AbstractStaticHistogram.Iter [[AbstractStaticHistogram.Iter.html]]
    interface "<size:14>Histogram.Iter\n<size:10>elki.utilities.datastructures.histogram" as elki.utilities.datastructures.histogram.Histogram.Iter [[Histogram.Iter.html]] {
        {abstract} +getCenter(): double
        {abstract} +getLeft(): double
        {abstract} +getRight(): double
    }
    class "<size:14>DoubleHistogram\n<size:10>elki.utilities.datastructures.histogram" as elki.utilities.datastructures.histogram.DoubleHistogram [[DoubleHistogram.html]]

    elki.utilities.datastructures.histogram.AbstractStaticHistogram.Iter <|-- elki.utilities.datastructures.histogram.DoubleHistogram.Iter
    elki.utilities.datastructures.histogram.Histogram.Iter <|.. elki.utilities.datastructures.histogram.DoubleHistogram.Iter
    elki.utilities.datastructures.histogram.DoubleHistogram +-- elki.utilities.datastructures.histogram.DoubleHistogram.Iter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
