@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ObjHistogram.BucketFactory\n<size:10>elki.utilities.datastructures.histogram" as elki.utilities.datastructures.histogram.ObjHistogram.BucketFactory<T> [[ObjHistogram.BucketFactory.html]] {
        {abstract} +make(): T
    }

    class "<size:14>ObjHistogram\n<size:10>elki.utilities.datastructures.histogram" as elki.utilities.datastructures.histogram.ObjHistogram<T> [[ObjHistogram.html]]

    elki.utilities.datastructures.histogram.ObjHistogram +-- elki.utilities.datastructures.histogram.ObjHistogram.BucketFactory

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
