@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>DBIDMIter\n<size:10>elki.database.ids" as elki.database.ids.DBIDMIter [[DBIDMIter.html]] {
        {abstract} +remove(): void
    }

    interface "<size:14>DBIDIter\n<size:10>elki.database.ids" as elki.database.ids.DBIDIter [[DBIDIter.html]] {
        {abstract} +advance(): DBIDIter
    }
    interface "<size:14>MIter\n<size:10>elki.utilities.datastructures.iterator" as elki.utilities.datastructures.iterator.MIter [[../../utilities/datastructures/iterator/MIter.html]] {
        {abstract} +remove(): void
    }

    elki.database.ids.DBIDIter <|-- elki.database.ids.DBIDMIter
    elki.utilities.datastructures.iterator.MIter <|-- elki.database.ids.DBIDMIter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
