@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>DoubleDBIDPair\n<size:10>elki.database.ids" as elki.database.ids.DoubleDBIDPair [[DoubleDBIDPair.html]] {
        {abstract} +doubleValue(): double
    }

    interface "<size:14>DBIDRef\n<size:10>elki.database.ids" as elki.database.ids.DBIDRef [[DBIDRef.html]] {
        {abstract} +internalGetIndex(): int
    }
    interface "<size:14>Comparable\n<size:10>java.lang" as java.lang.Comparable<DoubleDBIDPair> {
        {abstract} +compareTo(DoubleDBIDPair): int
    }

    elki.database.ids.DBIDRef <|-- elki.database.ids.DoubleDBIDPair
    java.lang.Comparable <|-- elki.database.ids.DoubleDBIDPair

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
