@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ListSizeConstraint\n<size:10>elki.utilities.optionhandling.constraints" as elki.utilities.optionhandling.constraints.ListSizeConstraint [[ListSizeConstraint.html]] {
        -sizeConstraint: int
        +ListSizeConstraint(int)
        +test(Object): void
        +getDescription(String): String
    }

    interface "<size:14>ParameterConstraint\n<size:10>elki.utilities.optionhandling.constraints" as elki.utilities.optionhandling.constraints.ParameterConstraint<Object> [[ParameterConstraint.html]] {
        {abstract} +test(Object): void
        {abstract} +getDescription(String): String
    }

    elki.utilities.optionhandling.constraints.ParameterConstraint <|.. elki.utilities.optionhandling.constraints.ListSizeConstraint

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
