@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>InputTabPanel\n<size:10>elki.gui.multistep.panels" as elki.gui.multistep.panels.InputTabPanel [[InputTabPanel.html]] {
        {static} -serialVersionUID: long
        -input: InputStep
        -executed: boolean
        #configureStep(Parameterization): void
        #executeStep(): void
        +getInputStep(): InputStep
        #getStatus(): Status
    }

    abstract class "<size:14>ParameterTabPanel\n<size:10>elki.gui.multistep.panels" as elki.gui.multistep.panels.ParameterTabPanel [[ParameterTabPanel.html]] {
        {abstract} #configureStep(Parameterization): void
        {abstract} #getStatus(): Status
        {abstract} #executeStep(): void
    }

    elki.gui.multistep.panels.ParameterTabPanel <|-- elki.gui.multistep.panels.InputTabPanel

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
