@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CauchyMADEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.CauchyMADEstimator [[CauchyMADEstimator.html]] {
        {static} +STATIC: CauchyMADEstimator
        +estimateFromMedianMAD(double, double): CauchyDistribution
        +getDistributionClass(): Class<? super CauchyDistribution>
    }

    interface "<size:14>MADDistributionEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.MADDistributionEstimator<CauchyDistribution> [[MADDistributionEstimator.html]] {
        {abstract} +estimateFromMedianMAD(double, double): CauchyDistribution
    }
    class "<size:14>CauchyMADEstimator.Par\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.CauchyMADEstimator.Par [[CauchyMADEstimator.Par.html]]

    elki.math.statistics.distribution.estimator.MADDistributionEstimator <|.. elki.math.statistics.distribution.estimator.CauchyMADEstimator
    elki.math.statistics.distribution.estimator.CauchyMADEstimator +-- elki.math.statistics.distribution.estimator.CauchyMADEstimator.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
