@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ExponentialMedianEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.ExponentialMedianEstimator [[ExponentialMedianEstimator.html]] {
        {static} +STATIC: ExponentialMedianEstimator
        +estimateFromMedianMAD(double, double): ExponentialDistribution
        +getDistributionClass(): Class<? super ExponentialDistribution>
    }

    interface "<size:14>MADDistributionEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.MADDistributionEstimator<ExponentialDistribution> [[MADDistributionEstimator.html]] {
        {abstract} +estimateFromMedianMAD(double, double): ExponentialDistribution
    }
    class "<size:14>ExponentialMedianEstimator.Par\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.ExponentialMedianEstimator.Par [[ExponentialMedianEstimator.Par.html]]

    elki.math.statistics.distribution.estimator.MADDistributionEstimator <|.. elki.math.statistics.distribution.estimator.ExponentialMedianEstimator
    elki.math.statistics.distribution.estimator.ExponentialMedianEstimator +-- elki.math.statistics.distribution.estimator.ExponentialMedianEstimator.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
