@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LaplaceMADEstimator.Par\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.LaplaceMADEstimator.Par [[LaplaceMADEstimator.Par.html]] {
        +make(): LaplaceMADEstimator
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>LaplaceMADEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.LaplaceMADEstimator [[LaplaceMADEstimator.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.math.statistics.distribution.estimator.LaplaceMADEstimator.Par
    elki.math.statistics.distribution.estimator.LaplaceMADEstimator +-- elki.math.statistics.distribution.estimator.LaplaceMADEstimator.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
