@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LogLogisticMADEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.LogLogisticMADEstimator [[LogLogisticMADEstimator.html]] {
        {static} +STATIC: LogLogisticMADEstimator
        +estimateFromLogMedianMAD(double, double, double): LogLogisticDistribution
        +getDistributionClass(): Class<? super LogLogisticDistribution>
    }

    interface "<size:14>LogMADDistributionEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.LogMADDistributionEstimator<LogLogisticDistribution> [[LogMADDistributionEstimator.html]] {
        {abstract} +estimateFromLogMedianMAD(double, double, double): LogLogisticDistribution
    }
    class "<size:14>LogLogisticMADEstimator.Par\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.LogLogisticMADEstimator.Par [[LogLogisticMADEstimator.Par.html]]

    elki.math.statistics.distribution.estimator.LogMADDistributionEstimator <|.. elki.math.statistics.distribution.estimator.LogLogisticMADEstimator
    elki.math.statistics.distribution.estimator.LogLogisticMADEstimator +-- elki.math.statistics.distribution.estimator.LogLogisticMADEstimator.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
