@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>NormalMOMEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.NormalMOMEstimator [[NormalMOMEstimator.html]] {
        {static} +STATIC: NormalMOMEstimator
        +estimateFromMeanVariance(MeanVariance): NormalDistribution
        +getDistributionClass(): Class<? super NormalDistribution>
    }

    interface "<size:14>MeanVarianceDistributionEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.MeanVarianceDistributionEstimator<NormalDistribution> [[MeanVarianceDistributionEstimator.html]] {
        {abstract} +estimateFromMeanVariance(MeanVariance): NormalDistribution
    }
    class "<size:14>NormalMOMEstimator.Par\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.NormalMOMEstimator.Par [[NormalMOMEstimator.Par.html]]

    elki.math.statistics.distribution.estimator.MeanVarianceDistributionEstimator <|.. elki.math.statistics.distribution.estimator.NormalMOMEstimator
    elki.math.statistics.distribution.estimator.NormalMOMEstimator +-- elki.math.statistics.distribution.estimator.NormalMOMEstimator.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
