@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SkewGNormalLMMEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.SkewGNormalLMMEstimator [[SkewGNormalLMMEstimator.html]] {
        {static} +STATIC: SkewGNormalLMMEstimator
        {static} -A0: double
        {static} -A1: double
        {static} -A2: double
        {static} -A3: double
        {static} -B1: double
        {static} -B2: double
        {static} -B3: double
        +getNumMoments(): int
        +estimateFromLMoments(double[]): SkewGeneralizedNormalDistribution
        +getDistributionClass(): Class<? super SkewGeneralizedNormalDistribution>
    }

    interface "<size:14>LMMDistributionEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.LMMDistributionEstimator<SkewGeneralizedNormalDistribution> [[LMMDistributionEstimator.html]] {
        {abstract} +estimateFromLMoments(double[]): SkewGeneralizedNormalDistribution
        {abstract} +getNumMoments(): int
    }
    class "<size:14>SkewGNormalLMMEstimator.Par\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.SkewGNormalLMMEstimator.Par [[SkewGNormalLMMEstimator.Par.html]]

    elki.math.statistics.distribution.estimator.LMMDistributionEstimator <|.. elki.math.statistics.distribution.estimator.SkewGNormalLMMEstimator
    elki.math.statistics.distribution.estimator.SkewGNormalLMMEstimator +-- elki.math.statistics.distribution.estimator.SkewGNormalLMMEstimator.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
