@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>UniformMinMaxEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.UniformMinMaxEstimator [[UniformMinMaxEstimator.html]] {
        {static} +STATIC: UniformMinMaxEstimator
        +estimate(A, NumberArrayAdapter<?, A>): UniformDistribution
        +estimate(DoubleMinMax): UniformDistribution
        +estimate(double, double): Distribution
        +getDistributionClass(): Class<? super UniformDistribution>
    }

    interface "<size:14>DistributionEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.DistributionEstimator<UniformDistribution> [[DistributionEstimator.html]] {
        {abstract} +estimate(A, NumberArrayAdapter<?, A>): UniformDistribution
        {abstract} +getDistributionClass(): Class<? super Distribution>
    }
    class "<size:14>UniformMinMaxEstimator.Par\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.UniformMinMaxEstimator.Par [[UniformMinMaxEstimator.Par.html]]

    elki.math.statistics.distribution.estimator.DistributionEstimator <|.. elki.math.statistics.distribution.estimator.UniformMinMaxEstimator
    elki.math.statistics.distribution.estimator.UniformMinMaxEstimator +-- elki.math.statistics.distribution.estimator.UniformMinMaxEstimator.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
