@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>UniformLMMEstimator.Par\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.UniformLMMEstimator.Par [[UniformLMMEstimator.Par.html]] {
        +make(): UniformLMMEstimator
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>UniformLMMEstimator\n<size:10>elki.math.statistics.distribution.estimator" as elki.math.statistics.distribution.estimator.UniformLMMEstimator [[UniformLMMEstimator.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.math.statistics.distribution.estimator.UniformLMMEstimator.Par
    elki.math.statistics.distribution.estimator.UniformLMMEstimator +-- elki.math.statistics.distribution.estimator.UniformLMMEstimator.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
