@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CFSFDP\n<size:10>tutorial.clustering" as tutorial.clustering.CFSFDP<O> [[CFSFDP.html]] {
        #distance: Distance<? super O>
        #dc: double
        #k: int
        #CFSFDP(Distance<? super O>, double, int)
        +run(Relation<O>): Clustering<SimplePrototypeModel<DBID>>
        +getInputTypeRestriction(): TypeInformation[]
    }

    interface "<size:14>ClusteringAlgorithm\n<size:10>elki.clustering" as elki.clustering.ClusteringAlgorithm<Clustering<SimplePrototypeModel<DBID>>> [[../../elki/clustering/ClusteringAlgorithm.html]]
    class "<size:14>CFSFDP.Par\n<size:10>tutorial.clustering" as tutorial.clustering.CFSFDP.Par<O> [[CFSFDP.Par.html]]

    elki.clustering.ClusteringAlgorithm <|.. tutorial.clustering.CFSFDP
    tutorial.clustering.CFSFDP +-- tutorial.clustering.CFSFDP.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
