@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>NaiveAgglomerativeHierarchicalClustering3.Linkage\n<size:10>tutorial.clustering" as tutorial.clustering.NaiveAgglomerativeHierarchicalClustering3.Linkage [[NaiveAgglomerativeHierarchicalClustering3.Linkage.html]] {
        {static} +SINGLE
        {static} +COMPLETE
        {static} +GROUP_AVERAGE
        {static} +WEIGHTED_AVERAGE
        {static} +CENTROID
        {static} +MEDIAN
        {static} +WARD
        {abstract} +combine(int, double, int, double, int, double): double
    }

    class "<size:14>NaiveAgglomerativeHierarchicalClustering3\n<size:10>tutorial.clustering" as tutorial.clustering.NaiveAgglomerativeHierarchicalClustering3<O> [[NaiveAgglomerativeHierarchicalClustering3.html]]

    tutorial.clustering.NaiveAgglomerativeHierarchicalClustering3 +-- tutorial.clustering.NaiveAgglomerativeHierarchicalClustering3.Linkage

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
