@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ClassicMultidimensionalScalingTransform.Par\n<size:10>elki.datasource.filter.transform" as elki.datasource.filter.transform.ClassicMultidimensionalScalingTransform.Par<I, O extends NumberVector> {
        {static} +DIM_ID: OptionID
        {static} +DISTANCE_ID: OptionID
        {static} +VECTOR_TYPE_ID: OptionID
        ~tdim: int
        ~dist: PrimitiveDistance<? super I>
        ~factory: Factory<O extends NumberVector>
        +configure(Parameterization): void
        +make(): ClassicMultidimensionalScalingTransform<I, O extends NumberVector>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>ClassicMultidimensionalScalingTransform\n<size:10>elki.datasource.filter.transform" as elki.datasource.filter.transform.ClassicMultidimensionalScalingTransform<I, O extends NumberVector> [[ClassicMultidimensionalScalingTransform.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.datasource.filter.transform.ClassicMultidimensionalScalingTransform.Par
    elki.datasource.filter.transform.ClassicMultidimensionalScalingTransform +-- elki.datasource.filter.transform.ClassicMultidimensionalScalingTransform.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
