@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>GlobalPrincipalComponentAnalysisTransform.Mode\n<size:10>elki.datasource.filter.transform" as elki.datasource.filter.transform.GlobalPrincipalComponentAnalysisTransform.Mode [[GlobalPrincipalComponentAnalysisTransform.Mode.html]] {
        {static} +FULL
        {static} +CENTER_ROTATE
    }

    class "<size:14>GlobalPrincipalComponentAnalysisTransform\n<size:10>elki.datasource.filter.transform" as elki.datasource.filter.transform.GlobalPrincipalComponentAnalysisTransform<O extends NumberVector> [[GlobalPrincipalComponentAnalysisTransform.html]]

    elki.datasource.filter.transform.GlobalPrincipalComponentAnalysisTransform +-- elki.datasource.filter.transform.GlobalPrincipalComponentAnalysisTransform.Mode

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
