@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LinearDiscriminantAnalysisFilter\n<size:10>elki.datasource.filter.transform" as elki.datasource.filter.transform.LinearDiscriminantAnalysisFilter<V extends NumberVector> [[LinearDiscriminantAnalysisFilter.html]] {
        {static} -LOG: Logging
        +LinearDiscriminantAnalysisFilter(int)
        #computeProjectionMatrix(List<V extends NumberVector>, List<? extends ClassLabel>, int): double[]
        #computeCentroids(int, List<V extends NumberVector>, List<ClassLabel>, Map<ClassLabel, IntList>): List<Centroid>
        #getLogger(): Logging
    }

    abstract class "<size:14>AbstractSupervisedProjectionVectorFilter\n<size:10>elki.datasource.filter.transform" as elki.datasource.filter.transform.AbstractSupervisedProjectionVectorFilter<V extends NumberVector> [[AbstractSupervisedProjectionVectorFilter.html]] {
        {abstract} #getLogger(): Logging
        {abstract} #computeProjectionMatrix(List<V extends NumberVector>, List<? extends ClassLabel>, int): double[]
    }
    class "<size:14>LinearDiscriminantAnalysisFilter.Par\n<size:10>elki.datasource.filter.transform" as elki.datasource.filter.transform.LinearDiscriminantAnalysisFilter.Par<V extends NumberVector> [[LinearDiscriminantAnalysisFilter.Par.html]]

    elki.datasource.filter.transform.AbstractSupervisedProjectionVectorFilter <|-- elki.datasource.filter.transform.LinearDiscriminantAnalysisFilter
    elki.datasource.filter.transform.LinearDiscriminantAnalysisFilter +-- elki.datasource.filter.transform.LinearDiscriminantAnalysisFilter.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
