@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>NumberVectorFeatureSelectionFilter\n<size:10>elki.datasource.filter.transform" as elki.datasource.filter.transform.NumberVectorFeatureSelectionFilter<V extends NumberVector> [[NumberVectorFeatureSelectionFilter.html]] {
        -selectedAttributes: long[]
        +NumberVectorFeatureSelectionFilter(long[])
        #filterSingleObject(V extends NumberVector): V extends NumberVector
        #getInputTypeRestriction(): SimpleTypeInformation<? super NumberVector>
        #convertedType(SimpleTypeInformation<V extends NumberVector>): SimpleTypeInformation<? super NumberVector>
        +setSelectedAttributes(long[]): void
        +getSelectedAttributes(): long[]
        +getDimensionality(): int
    }

    abstract class "<size:14>AbstractVectorStreamConversionFilter\n<size:10>elki.datasource.filter" as elki.datasource.filter.AbstractVectorStreamConversionFilter<V extends NumberVector, V extends NumberVector> [[../AbstractVectorStreamConversionFilter.html]]
    class "<size:14>NumberVectorFeatureSelectionFilter.Par\n<size:10>elki.datasource.filter.transform" as elki.datasource.filter.transform.NumberVectorFeatureSelectionFilter.Par [[NumberVectorFeatureSelectionFilter.Par.html]]

    elki.datasource.filter.AbstractVectorStreamConversionFilter <|-- elki.datasource.filter.transform.NumberVectorFeatureSelectionFilter
    elki.datasource.filter.transform.NumberVectorFeatureSelectionFilter +-- elki.datasource.filter.transform.NumberVectorFeatureSelectionFilter.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
