@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>NumberVectorRandomFeatureSelectionFilter\n<size:10>elki.datasource.filter.transform" as elki.datasource.filter.transform.NumberVectorRandomFeatureSelectionFilter<V extends NumberVector> [[NumberVectorRandomFeatureSelectionFilter.html]] {
        #selectedAttributes: long[]
        #k: int
        #rnd: RandomFactory
        +NumberVectorRandomFeatureSelectionFilter(int, RandomFactory)
        #filterSingleObject(V extends NumberVector): V extends NumberVector
        #getInputTypeRestriction(): SimpleTypeInformation<? super NumberVector>
        #convertedType(SimpleTypeInformation<V extends NumberVector>): SimpleTypeInformation<? super NumberVector>
        ~initializeRandomAttributes(SimpleTypeInformation<V extends NumberVector>): void
    }

    abstract class "<size:14>AbstractVectorStreamConversionFilter\n<size:10>elki.datasource.filter" as elki.datasource.filter.AbstractVectorStreamConversionFilter<V extends NumberVector, V extends NumberVector> [[../AbstractVectorStreamConversionFilter.html]]
    class "<size:14>NumberVectorRandomFeatureSelectionFilter.Par\n<size:10>elki.datasource.filter.transform" as elki.datasource.filter.transform.NumberVectorRandomFeatureSelectionFilter.Par [[NumberVectorRandomFeatureSelectionFilter.Par.html]]

    elki.datasource.filter.AbstractVectorStreamConversionFilter <|-- elki.datasource.filter.transform.NumberVectorRandomFeatureSelectionFilter
    elki.datasource.filter.transform.NumberVectorRandomFeatureSelectionFilter +-- elki.datasource.filter.transform.NumberVectorRandomFeatureSelectionFilter.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
