@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>Executor\n<size:10>elki.parallel" as elki.parallel.Executor [[Executor.html]] {
        {abstract} +getInstance(SharedVariable<I extends Instance<?>>): I extends Instance<?>
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
