@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>HySortOD\n<size:10>elki.outlier.density" as elki.outlier.density.HySortOD [[HySortOD.html]] {
        {static} -LOG: Logging
        -b: int
        -l: double
        -strategy: DensityStrategy
        +HySortOD(int, int)
        +run(Database, Relation<? extends NumberVector>): OutlierResult
        -getSortedHypercubes(Relation<? extends NumberVector>): List<Hypercube>
        -score(int): double
        +getInputTypeRestriction(): TypeInformation[]
    }

    interface "<size:14>OutlierAlgorithm\n<size:10>elki.outlier" as elki.outlier.OutlierAlgorithm [[../OutlierAlgorithm.html]]
    class "<size:14>HySortOD.Hypercube\n<size:10>elki.outlier.density" as elki.outlier.density.HySortOD.Hypercube [[HySortOD.Hypercube.html]]
    abstract class "<size:14>HySortOD.DensityStrategy\n<size:10>elki.outlier.density" as elki.outlier.density.HySortOD.DensityStrategy [[HySortOD.DensityStrategy.html]]
    class "<size:14>HySortOD.NaiveStrategy\n<size:10>elki.outlier.density" as elki.outlier.density.HySortOD.NaiveStrategy [[HySortOD.NaiveStrategy.html]]
    class "<size:14>HySortOD.TreeStrategy\n<size:10>elki.outlier.density" as elki.outlier.density.HySortOD.TreeStrategy [[HySortOD.TreeStrategy.html]]
    class "<size:14>HySortOD.Par\n<size:10>elki.outlier.density" as elki.outlier.density.HySortOD.Par

    elki.outlier.OutlierAlgorithm <|.. elki.outlier.density.HySortOD
    elki.outlier.density.HySortOD +-- elki.outlier.density.HySortOD.Hypercube
    elki.outlier.density.HySortOD +-- elki.outlier.density.HySortOD.DensityStrategy
    elki.outlier.density.HySortOD +-- elki.outlier.density.HySortOD.NaiveStrategy
    elki.outlier.density.HySortOD +-- elki.outlier.density.HySortOD.TreeStrategy
    elki.outlier.density.HySortOD +-- elki.outlier.density.HySortOD.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
