@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>EuclideanRStarTreeKNNQuery\n<size:10>elki.index.tree.spatial.rstarvariants.query" as elki.index.tree.spatial.rstarvariants.query.EuclideanRStarTreeKNNQuery<O extends NumberVector> [[EuclideanRStarTreeKNNQuery.html]] {
        {static} -SQUARED: SquaredEuclideanDistance
        +EuclideanRStarTreeKNNQuery(AbstractRStarTree<?, ?, ?>, Relation<? extends NumberVector>)
        +getKNN(O extends NumberVector, int): KNNList
        -expandNode(O extends NumberVector, KNNHeap, DoubleIntegerMinHeap, double, int): double
    }

    class "<size:14>RStarTreeKNNSearcher\n<size:10>elki.index.tree.spatial.rstarvariants.query" as elki.index.tree.spatial.rstarvariants.query.RStarTreeKNNSearcher<O extends NumberVector> [[RStarTreeKNNSearcher.html]]

    elki.index.tree.spatial.rstarvariants.query.RStarTreeKNNSearcher <|-- elki.index.tree.spatial.rstarvariants.query.EuclideanRStarTreeKNNQuery

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
