@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>TreeSphereVisualization\n<size:10>elki.visualization.visualizers.scatterplot.index" as elki.visualization.visualizers.scatterplot.index.TreeSphereVisualization [[TreeSphereVisualization.html]] {
        {static} +INDEX: String
        {static} +NAME: String
        #settings: Par
        +TreeSphereVisualization(Par)
        +processNewResult(VisualizerContext, Object): void
        +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
        {static} +getLPNormP(AbstractMTree<?, ?, ?, ?>): double
        {static} +canVisualize(Relation<?>, AbstractMTree<?, ?, ?, ?>): boolean
    }

    interface "<size:14>VisFactory\n<size:10>elki.visualization.visualizers" as elki.visualization.visualizers.VisFactory [[../../VisFactory.html]] {
        {abstract} +processNewResult(VisualizerContext, Object): void
        {abstract} +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
    }
    enum "<size:14>TreeSphereVisualization.Mode\n<size:10>elki.visualization.visualizers.scatterplot.index" as elki.visualization.visualizers.scatterplot.index.TreeSphereVisualization.Mode [[TreeSphereVisualization.Mode.html]]
    class "<size:14>TreeSphereVisualization.Instance\n<size:10>elki.visualization.visualizers.scatterplot.index" as elki.visualization.visualizers.scatterplot.index.TreeSphereVisualization.Instance<N extends AbstractMTreeNode<?, N, E extends MTreeEntry>, E extends MTreeEntry> [[TreeSphereVisualization.Instance.html]]
    class "<size:14>TreeSphereVisualization.Par\n<size:10>elki.visualization.visualizers.scatterplot.index" as elki.visualization.visualizers.scatterplot.index.TreeSphereVisualization.Par [[TreeSphereVisualization.Par.html]]

    elki.visualization.visualizers.VisFactory <|.. elki.visualization.visualizers.scatterplot.index.TreeSphereVisualization
    elki.visualization.visualizers.scatterplot.index.TreeSphereVisualization +-- elki.visualization.visualizers.scatterplot.index.TreeSphereVisualization.Mode
    elki.visualization.visualizers.scatterplot.index.TreeSphereVisualization +-- elki.visualization.visualizers.scatterplot.index.TreeSphereVisualization.Instance
    elki.visualization.visualizers.scatterplot.index.TreeSphereVisualization +-- elki.visualization.visualizers.scatterplot.index.TreeSphereVisualization.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
