@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AnnulusKMeans\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.AnnulusKMeans<V extends NumberVector> [[AnnulusKMeans.html]] {
        {static} -LOG: Logging
        +AnnulusKMeans(NumberVectorDistance<? super NumberVector>, int, int, KMeansInitialization, boolean)
        +run(Relation<V extends NumberVector>): Clustering<KMeansModel>
        #getLogger(): Logging
    }

    class "<size:14>HamerlyKMeans\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.HamerlyKMeans<V extends NumberVector> [[HamerlyKMeans.html]]
    class "<size:14>AnnulusKMeans.Instance\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.AnnulusKMeans.Instance [[AnnulusKMeans.Instance.html]]
    class "<size:14>AnnulusKMeans.Par\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.AnnulusKMeans.Par<V extends NumberVector> [[AnnulusKMeans.Par.html]]

    elki.clustering.kmeans.HamerlyKMeans <|-- elki.clustering.kmeans.AnnulusKMeans
    elki.clustering.kmeans.AnnulusKMeans +-- elki.clustering.kmeans.AnnulusKMeans.Instance
    elki.clustering.kmeans.AnnulusKMeans +-- elki.clustering.kmeans.AnnulusKMeans.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
