@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>KMeans\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.KMeans<V extends NumberVector, M extends Model> [[KMeans.html]] {
        {static} +DISTANCE_FUNCTION_ID: OptionID
        {static} +INIT_ID: OptionID
        {static} +K_ID: OptionID
        {static} +MAXITER_ID: OptionID
        {static} +SEED_ID: OptionID
        {static} +VARSTAT_ID: OptionID
        {abstract} +run(Relation<V extends NumberVector>): Clustering<M extends Model>
        {abstract} +setK(int): void
        {abstract} +setDistance(NumberVectorDistance<? super NumberVector>): void
        {abstract} +getDistance(): NumberVectorDistance<? super NumberVector>
        {abstract} +setInitializer(KMeansInitialization): void
    }

    interface "<size:14>ClusteringAlgorithm\n<size:10>elki.clustering" as elki.clustering.ClusteringAlgorithm<Clustering<M extends Model>> [[../ClusteringAlgorithm.html]]

    elki.clustering.ClusteringAlgorithm <|-- elki.clustering.kmeans.KMeans

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
