@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LloydKMeans.Instance\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.LloydKMeans.Instance [[LloydKMeans.Instance.html]] {
        +Instance(Relation<? extends NumberVector>, NumberVectorDistance<?>, double[])
        #iterate(int): int
        #getLogger(): Logging
    }

    abstract class "<size:14>AbstractKMeans.Instance\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.AbstractKMeans.Instance [[AbstractKMeans.Instance.html]] {
        {abstract} #iterate(int): int
        {abstract} #getLogger(): Logging
    }
    class "<size:14>LloydKMeans\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.LloydKMeans<V extends NumberVector> [[LloydKMeans.html]]

    elki.clustering.kmeans.AbstractKMeans.Instance <|-- elki.clustering.kmeans.LloydKMeans.Instance
    elki.clustering.kmeans.LloydKMeans +-- elki.clustering.kmeans.LloydKMeans.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
