@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ShallotKMeans\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.ShallotKMeans<V extends NumberVector> [[ShallotKMeans.html]] {
        {static} -LOG: Logging
        +ShallotKMeans(NumberVectorDistance<? super NumberVector>, int, int, KMeansInitialization, boolean)
        +run(Relation<V extends NumberVector>): Clustering<KMeansModel>
        #getLogger(): Logging
    }

    class "<size:14>ExponionKMeans\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.ExponionKMeans<V extends NumberVector> [[ExponionKMeans.html]]
    class "<size:14>ShallotKMeans.Instance\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.ShallotKMeans.Instance [[ShallotKMeans.Instance.html]]
    class "<size:14>ShallotKMeans.Par\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.ShallotKMeans.Par<V extends NumberVector> [[ShallotKMeans.Par.html]]

    elki.clustering.kmeans.ExponionKMeans <|-- elki.clustering.kmeans.ShallotKMeans
    elki.clustering.kmeans.ShallotKMeans +-- elki.clustering.kmeans.ShallotKMeans.Instance
    elki.clustering.kmeans.ShallotKMeans +-- elki.clustering.kmeans.ShallotKMeans.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
