@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SimplifiedElkanKMeans\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.SimplifiedElkanKMeans<V extends NumberVector> [[SimplifiedElkanKMeans.html]] {
        {static} -LOG: Logging
        #varstat: boolean
        +SimplifiedElkanKMeans(NumberVectorDistance<? super NumberVector>, int, int, KMeansInitialization, boolean)
        +run(Relation<V extends NumberVector>): Clustering<KMeansModel>
        #getLogger(): Logging
    }

    abstract class "<size:14>AbstractKMeans\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.AbstractKMeans<V extends NumberVector, KMeansModel> [[AbstractKMeans.html]] {
        {abstract} #getLogger(): Logging
    }
    class "<size:14>SimplifiedElkanKMeans.Instance\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.SimplifiedElkanKMeans.Instance [[SimplifiedElkanKMeans.Instance.html]]
    class "<size:14>SimplifiedElkanKMeans.Par\n<size:10>elki.clustering.kmeans" as elki.clustering.kmeans.SimplifiedElkanKMeans.Par<V extends NumberVector> [[SimplifiedElkanKMeans.Par.html]]

    elki.clustering.kmeans.AbstractKMeans <|-- elki.clustering.kmeans.SimplifiedElkanKMeans
    elki.clustering.kmeans.SimplifiedElkanKMeans +-- elki.clustering.kmeans.SimplifiedElkanKMeans.Instance
    elki.clustering.kmeans.SimplifiedElkanKMeans +-- elki.clustering.kmeans.SimplifiedElkanKMeans.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
