@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Log1PlusNormalization\n<size:10>elki.datasource.filter.normalization.instancewise" as elki.datasource.filter.normalization.instancewise.Log1PlusNormalization<V extends NumberVector> [[Log1PlusNormalization.html]] {
        {static} +STATIC: Log1PlusNormalization<NumberVector>
        #boost: double
        #scale: double
        +Log1PlusNormalization(double)
        #filterSingleObject(V extends NumberVector): V extends NumberVector
        #convertedType(SimpleTypeInformation<V extends NumberVector>): SimpleTypeInformation<? super NumberVector>
        #getInputTypeRestriction(): SimpleTypeInformation<? super NumberVector>
    }

    abstract class "<size:14>AbstractVectorStreamConversionFilter\n<size:10>elki.datasource.filter" as elki.datasource.filter.AbstractVectorStreamConversionFilter<V extends NumberVector, V extends NumberVector> [[../../AbstractVectorStreamConversionFilter.html]]
    interface "<size:14>Normalization\n<size:10>elki.datasource.filter.normalization" as elki.datasource.filter.normalization.Normalization<V extends NumberVector> [[../Normalization.html]]
    class "<size:14>Log1PlusNormalization.Par\n<size:10>elki.datasource.filter.normalization.instancewise" as elki.datasource.filter.normalization.instancewise.Log1PlusNormalization.Par<V extends NumberVector> [[Log1PlusNormalization.Par.html]]

    elki.datasource.filter.AbstractVectorStreamConversionFilter <|-- elki.datasource.filter.normalization.instancewise.Log1PlusNormalization
    elki.datasource.filter.normalization.Normalization <|.. elki.datasource.filter.normalization.instancewise.Log1PlusNormalization
    elki.datasource.filter.normalization.instancewise.Log1PlusNormalization +-- elki.datasource.filter.normalization.instancewise.Log1PlusNormalization.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
