@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ParallelGeneralizedDBSCAN.Instance\n<size:10>elki.clustering.dbscan.parallel" as elki.clustering.dbscan.parallel.ParallelGeneralizedDBSCAN.Instance<T> [[ParallelGeneralizedDBSCAN.Instance.html]] {
        #npred: Instance<T>
        #corepred: Instance<? super T>
        #coremodel: boolean
        -clusterids: WritableDataStore<Assignment>
        -cores: Core[]
        -borders: Border[]
        -nextclus: int
        -database: Database
        -npreds: NeighborPredicate<? extends T>
        -progress: FiniteProgress
        +Instance(Database, NeighborPredicate<T>, CorePredicate<? super T>, boolean)
        +run(): Clustering<Model>
        #processNeighbors(DBIDRef, T): void
        +instantiate(Executor): Mapper
        +cleanup(Instance): void
    }

    interface "<size:14>Processor\n<size:10>elki.parallel.processor" as elki.parallel.processor.Processor [[../../../parallel/processor/Processor.html]] {
        {abstract} +instantiate(Executor): Instance
        {abstract} +cleanup(Instance): void
    }
    class "<size:14>ParallelGeneralizedDBSCAN\n<size:10>elki.clustering.dbscan.parallel" as elki.clustering.dbscan.parallel.ParallelGeneralizedDBSCAN [[ParallelGeneralizedDBSCAN.html]]
    class "<size:14>ParallelGeneralizedDBSCAN.Instance.Mapper\n<size:10>elki.clustering.dbscan.parallel" as elki.clustering.dbscan.parallel.ParallelGeneralizedDBSCAN.Instance.Mapper [[ParallelGeneralizedDBSCAN.Instance.Mapper.html]]

    elki.parallel.processor.Processor <|.. elki.clustering.dbscan.parallel.ParallelGeneralizedDBSCAN.Instance
    elki.clustering.dbscan.parallel.ParallelGeneralizedDBSCAN +-- elki.clustering.dbscan.parallel.ParallelGeneralizedDBSCAN.Instance
    elki.clustering.dbscan.parallel.ParallelGeneralizedDBSCAN.Instance +-- elki.clustering.dbscan.parallel.ParallelGeneralizedDBSCAN.Instance.Mapper

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
