@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MkAppTreeSettings\n<size:10>elki.index.tree.metrical.mtreevariants.mktrees.mkapp" as elki.index.tree.metrical.mtreevariants.mktrees.mkapp.MkAppTreeSettings<O> [[MkAppTreeSettings.html]] {
        #p: int
        #log: boolean
    }

    class "<size:14>MkTreeSettings\n<size:10>elki.index.tree.metrical.mtreevariants.mktrees" as elki.index.tree.metrical.mtreevariants.mktrees.MkTreeSettings<O, MkAppTreeNode<O>, MkAppEntry> [[../MkTreeSettings.html]]

    elki.index.tree.metrical.mtreevariants.mktrees.MkTreeSettings <|-- elki.index.tree.metrical.mtreevariants.mktrees.mkapp.MkAppTreeSettings

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
