@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>IntDoublePair\n<size:10>elki.utilities.pairs" as elki.utilities.pairs.IntDoublePair [[IntDoublePair.html]] {
        +first: int
        +second: double
        {static} +BYFIRST_COMPARATOR: Comparator<IntDoublePair>
        {static} +BYSECOND_COMPARATOR: Comparator<IntDoublePair>
        {static} +SWAPPED_COMPARATOR: Comparator<IntDoublePair>
        +IntDoublePair(int, double)
        +compareTo(IntDoublePair): int
        +compareSwappedTo(IntDoublePair): int
        +setFirst(int): void
        +setSecond(double): void
    }

    interface "<size:14>Comparable\n<size:10>java.lang" as java.lang.Comparable<IntDoublePair> {
        {abstract} +compareTo(IntDoublePair): int
    }

    java.lang.Comparable <|.. elki.utilities.pairs.IntDoublePair

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
