@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RandomDoubleVectorDatabaseConnection.Par\n<size:10>elki.datasource" as elki.datasource.RandomDoubleVectorDatabaseConnection.Par [[RandomDoubleVectorDatabaseConnection.Par.html]] {
        {static} +SEED_ID: OptionID
        {static} +DIM_ID: OptionID
        {static} +SIZE_ID: OptionID
        ~dim: int
        ~size: int
        ~rnd: RandomFactory
        +configure(Parameterization): void
        +make(): RandomDoubleVectorDatabaseConnection
    }

    abstract class "<size:14>AbstractDatabaseConnection.Par\n<size:10>elki.datasource" as elki.datasource.AbstractDatabaseConnection.Par [[AbstractDatabaseConnection.Par.html]]
    class "<size:14>RandomDoubleVectorDatabaseConnection\n<size:10>elki.datasource" as elki.datasource.RandomDoubleVectorDatabaseConnection [[RandomDoubleVectorDatabaseConnection.html]]

    elki.datasource.AbstractDatabaseConnection.Par <|-- elki.datasource.RandomDoubleVectorDatabaseConnection.Par
    elki.datasource.RandomDoubleVectorDatabaseConnection +-- elki.datasource.RandomDoubleVectorDatabaseConnection.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
