@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ArrayLikeUtil\n<size:10>elki.utilities.datastructures.arraylike" as elki.utilities.datastructures.arraylike.ArrayLikeUtil [[ArrayLikeUtil.html]] {
        {static} +FEATUREVECTORADAPTER: FeatureVectorAdapter<?>
        {static} +NUMBERVECTORADAPTER: NumberVectorAdapter
        {static} +DOUBLEARRAYADAPTER: NumberArrayAdapter<Double, double[]>
        {static} +FLOATARRAYADAPTER: NumberArrayAdapter<Float, float[]>
        {static} +featureVectorAdapter(FeatureVector<F>): FeatureVectorAdapter<F>
        {static} +getIndexOfMaximum(A, NumberArrayAdapter<?, A>): int
        {static} +getIndexOfMaximum(double[]): int
        {static} +toPrimitiveDoubleArray(A, NumberArrayAdapter<?, ? super A>): double[]
        {static} +toPrimitiveDoubleArray(NumberVector): double[]
        {static} +toPrimitiveFloatArray(A, NumberArrayAdapter<?, ? super A>): float[]
        {static} +toPrimitiveFloatArray(NumberVector): float[]
        {static} +toPrimitiveIntegerArray(A, NumberArrayAdapter<?, ? super A>): int[]
        {static} +toPrimitiveIntegerArray(NumberVector): int[]
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
