@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DoubleArrayAdapter\n<size:10>elki.utilities.datastructures.arraylike" as elki.utilities.datastructures.arraylike.DoubleArrayAdapter [[DoubleArrayAdapter.html]] {
        {static} +STATIC: DoubleArrayAdapter
        +size(double[]): int
        +--get--(double[], int): Double
        +getDouble(double[], int): double
        +getFloat(double[], int): float
        +getInteger(double[], int): int
        +getShort(double[], int): short
        +getLong(double[], int): long
        +getByte(double[], int): byte
    }

    interface "<size:14>NumberArrayAdapter\n<size:10>elki.utilities.datastructures.arraylike" as elki.utilities.datastructures.arraylike.NumberArrayAdapter<Double, double[]> [[NumberArrayAdapter.html]] {
        {abstract} +size(double[]): int
        {abstract} +get(double[], int): Double
        {abstract} +getDouble(double[], int): double
        {abstract} +getLong(double[], int): long
    }

    elki.utilities.datastructures.arraylike.NumberArrayAdapter <|.. elki.utilities.datastructures.arraylike.DoubleArrayAdapter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
