@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ReferencePointsHeuristic\n<size:10>elki.utilities.referencepoints" as elki.utilities.referencepoints.ReferencePointsHeuristic [[ReferencePointsHeuristic.html]] {
        {abstract} +getReferencePoints(Relation<? extends NumberVector>): Collection<? extends NumberVector>
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
