@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>EnsembleVotingMultiplicative\n<size:10>elki.utilities.ensemble" as elki.utilities.ensemble.EnsembleVotingMultiplicative [[EnsembleVotingMultiplicative.html]] {
        {static} +STATIC: EnsembleVotingMultiplicative
        +combine(double[]): double
        +combine(double[], int): double
    }

    interface "<size:14>EnsembleVoting\n<size:10>elki.utilities.ensemble" as elki.utilities.ensemble.EnsembleVoting [[EnsembleVoting.html]] {
        {abstract} +combine(double[]): double
        {abstract} +combine(double[], int): double
    }
    class "<size:14>EnsembleVotingMultiplicative.Par\n<size:10>elki.utilities.ensemble" as elki.utilities.ensemble.EnsembleVotingMultiplicative.Par [[EnsembleVotingMultiplicative.Par.html]]

    elki.utilities.ensemble.EnsembleVoting <|.. elki.utilities.ensemble.EnsembleVotingMultiplicative
    elki.utilities.ensemble.EnsembleVotingMultiplicative +-- elki.utilities.ensemble.EnsembleVotingMultiplicative.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
