@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>KNNKernelDensityMinimaClustering.Mode\n<size:10>elki.clustering.onedimensional" as elki.clustering.onedimensional.KNNKernelDensityMinimaClustering.Mode [[KNNKernelDensityMinimaClustering.Mode.html]] {
        {static} +BALLOON
        {static} +SAMPLE
    }

    class "<size:14>KNNKernelDensityMinimaClustering\n<size:10>elki.clustering.onedimensional" as elki.clustering.onedimensional.KNNKernelDensityMinimaClustering [[KNNKernelDensityMinimaClustering.html]]

    elki.clustering.onedimensional.KNNKernelDensityMinimaClustering +-- elki.clustering.onedimensional.KNNKernelDensityMinimaClustering.Mode

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
