@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>GeometricLinkage\n<size:10>elki.clustering.hierarchical.linkage" as elki.clustering.hierarchical.linkage.GeometricLinkage [[GeometricLinkage.html]] {
        {abstract} +merge(double[], int, double[], int): double[]
        {abstract} +distance(double[], int, double[], int): double
    }

    interface "<size:14>Linkage\n<size:10>elki.clustering.hierarchical.linkage" as elki.clustering.hierarchical.linkage.Linkage [[Linkage.html]] {
        {abstract} +combine(int, double, int, double, int, double): double
    }

    elki.clustering.hierarchical.linkage.Linkage <|-- elki.clustering.hierarchical.linkage.GeometricLinkage

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
