@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>Linkage\n<size:10>elki.clustering.hierarchical.linkage" as elki.clustering.hierarchical.linkage.Linkage [[Linkage.html]] {
        +initial(double, boolean): double
        +restore(double, boolean): double
        {abstract} +combine(int, double, int, double, int, double): double
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
