@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LinearScanRKNNByObject\n<size:10>elki.database.query.rknn" as elki.database.query.rknn.LinearScanRKNNByObject<O> [[LinearScanRKNNByObject.html]] {
        -distanceQuery: DistanceQuery<O>
        -knnQuery: KNNSearcher<DBIDRef>
        +LinearScanRKNNByObject(DistanceQuery<O>, KNNSearcher<DBIDRef>)
        +getRKNN(O, int): DoubleDBIDList
    }

    interface "<size:14>RKNNSearcher\n<size:10>elki.database.query.rknn" as elki.database.query.rknn.RKNNSearcher<O> [[RKNNSearcher.html]] {
        {abstract} +getRKNN(O, int): DoubleDBIDList
    }
    interface "<size:14>LinearScanQuery\n<size:10>elki.database.query" as elki.database.query.LinearScanQuery [[../LinearScanQuery.html]]

    elki.database.query.rknn.RKNNSearcher <|.. elki.database.query.rknn.LinearScanRKNNByObject
    elki.database.query.LinearScanQuery <|.. elki.database.query.rknn.LinearScanRKNNByObject

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
