@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SOD.SODModel\n<size:10>elki.outlier.subspace" as elki.outlier.subspace.SOD.SODModel [[SOD.SODModel.html]] {
        -center: double[]
        -weightVector: long[]
        +SODModel(double[], long[])
        +writeToText(TextWriterStream, String): void
    }

    interface "<size:14>TextWriteable\n<size:10>elki.result.textwriter" as elki.result.textwriter.TextWriteable [[../../result/textwriter/TextWriteable.html]] {
        {abstract} +writeToText(TextWriterStream, String): void
    }
    class "<size:14>SOD\n<size:10>elki.outlier.subspace" as elki.outlier.subspace.SOD<V extends NumberVector> [[SOD.html]]

    elki.result.textwriter.TextWriteable <|.. elki.outlier.subspace.SOD.SODModel
    elki.outlier.subspace.SOD +-- elki.outlier.subspace.SOD.SODModel

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
