@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CheckParameterizables\n<size:10>elki.application.internal" as elki.application.internal.CheckParameterizables [[CheckParameterizables.html]] {
        {static} -LOG: Logging
        -knownParameterizables: List<Class<?>>
        +checkParameterizables(): void
        -checkSupertypes(Class<?>): boolean
        -checkV3Parameterization(Class<?>, State): State
        -checkDefaultConstructor(Class<?>, State): State
        -checkParameterizer(Class<?>, Class<? extends Parameterizer>): boolean
        {static} +main(String[]): void
    }
    enum "<size:14>CheckParameterizables.State\n<size:10>elki.application.internal" as elki.application.internal.CheckParameterizables.State [[CheckParameterizables.State.html]]

    elki.application.internal.CheckParameterizables +-- elki.application.internal.CheckParameterizables.State

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
