@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ByLabelHierarchicalClustering\n<size:10>elki.clustering.trivial" as elki.clustering.trivial.ByLabelHierarchicalClustering [[ByLabelHierarchicalClustering.html]] {
        {static} -LOG: Logging
        +autorun(Database): Clustering<Model>
        +run(Relation<?>): Clustering<Model>
        -assign(HashMap<String, DBIDs>, String, DBIDRef): void
        +getInputTypeRestriction(): TypeInformation[]
    }

    interface "<size:14>ClusteringAlgorithm\n<size:10>elki.clustering" as elki.clustering.ClusteringAlgorithm<Clustering<Model>> [[../ClusteringAlgorithm.html]]

    elki.clustering.ClusteringAlgorithm <|.. elki.clustering.trivial.ByLabelHierarchicalClustering

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
