@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ClusteringAlgorithm\n<size:10>elki.clustering" as elki.clustering.ClusteringAlgorithm<C extends Clustering<? extends Model>> [[ClusteringAlgorithm.html]] {
        +autorun(Database): C extends Clustering<? extends Model>
    }

    interface "<size:14>Algorithm\n<size:10>elki" as elki.Algorithm [[../Algorithm.html]] {
        {abstract} +getInputTypeRestriction(): TypeInformation[]
    }

    elki.Algorithm <|-- elki.clustering.ClusteringAlgorithm

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
