@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Leader.Par\n<size:10>elki.clustering" as elki.clustering.Leader.Par<O> {
        {static} +THRESHOLD_ID: OptionID
        -threshold: double
        #distance: Distance<? super O>
        +configure(Parameterization): void
        +make(): Leader<O>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>Leader\n<size:10>elki.clustering" as elki.clustering.Leader<O> [[Leader.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.clustering.Leader.Par
    elki.clustering.Leader +-- elki.clustering.Leader.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
