@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SubspaceManhattanDistance.Par\n<size:10>elki.distance.subspace" as elki.distance.subspace.SubspaceManhattanDistance.Par [[SubspaceManhattanDistance.Par.html]] {
        +make(): SubspaceManhattanDistance
    }

    abstract class "<size:14>AbstractDimensionsSelectingDistance.Par\n<size:10>elki.distance.subspace" as elki.distance.subspace.AbstractDimensionsSelectingDistance.Par [[AbstractDimensionsSelectingDistance.Par.html]]
    class "<size:14>SubspaceManhattanDistance\n<size:10>elki.distance.subspace" as elki.distance.subspace.SubspaceManhattanDistance [[SubspaceManhattanDistance.html]]

    elki.distance.subspace.AbstractDimensionsSelectingDistance.Par <|-- elki.distance.subspace.SubspaceManhattanDistance.Par
    elki.distance.subspace.SubspaceManhattanDistance +-- elki.distance.subspace.SubspaceManhattanDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
