@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CFTree.Factory\n<size:10>elki.index.tree.betula" as elki.index.tree.betula.CFTree.Factory<L extends ClusterFeature> [[CFTree.Factory.html]] {
        ~factory: Factory<L extends ClusterFeature>
        ~dist: CFDistance
        ~abs: CFDistance
        ~threshold: double
        ~branchingFactor: int
        ~maxleaves: double
        ~tCriterium: Threshold
        +Factory(Factory<L extends ClusterFeature>, CFDistance, CFDistance, double, int, double, Threshold)
        +newTree(DBIDs, Relation<? extends NumberVector>, boolean): CFTree<L extends ClusterFeature>
    }

    class "<size:14>CFTree\n<size:10>elki.index.tree.betula" as elki.index.tree.betula.CFTree<L extends ClusterFeature> [[CFTree.html]]
    class "<size:14>CFTree.Factory.Par\n<size:10>elki.index.tree.betula" as elki.index.tree.betula.CFTree.Factory.Par<L extends ClusterFeature> [[CFTree.Factory.Par.html]]

    elki.index.tree.betula.CFTree +-- elki.index.tree.betula.CFTree.Factory
    elki.index.tree.betula.CFTree.Factory +-- elki.index.tree.betula.CFTree.Factory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
