@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RdKNNLeafEntry\n<size:10>elki.index.tree.spatial.rstarvariants.rdknn" as elki.index.tree.spatial.rstarvariants.rdknn.RdKNNLeafEntry [[RdKNNLeafEntry.html]] {
        {static} -serialVersionUID: long
        -knnDistance: double
        +RdKNNLeafEntry()
        +RdKNNLeafEntry(DBID, NumberVector, double)
        +getKnnDistance(): double
        +setKnnDistance(double): void
        +writeExternal(ObjectOutput): void
        +readExternal(ObjectInput): void
    }

    class "<size:14>SpatialPointLeafEntry\n<size:10>elki.index.tree.spatial" as elki.index.tree.spatial.SpatialPointLeafEntry [[../../SpatialPointLeafEntry.html]]
    interface "<size:14>RdKNNEntry\n<size:10>elki.index.tree.spatial.rstarvariants.rdknn" as elki.index.tree.spatial.rstarvariants.rdknn.RdKNNEntry [[RdKNNEntry.html]] {
        {abstract} +getKnnDistance(): double
        {abstract} +setKnnDistance(double): void
    }

    elki.index.tree.spatial.SpatialPointLeafEntry <|-- elki.index.tree.spatial.rstarvariants.rdknn.RdKNNLeafEntry
    elki.index.tree.spatial.rstarvariants.rdknn.RdKNNEntry <|.. elki.index.tree.spatial.rstarvariants.rdknn.RdKNNLeafEntry

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
