@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ProjectedIndex.ProjectedRKNNByObject\n<size:10>elki.index.projected" as elki.index.projected.ProjectedIndex.ProjectedRKNNByObject [[ProjectedIndex.ProjectedRKNNByObject.html]] {
        ~inner: RKNNSearcher<​I>
        ~distq: DistanceQuery<O>
        +ProjectedRKNNByObject(DistanceQuery<O>, RKNNSearcher<​I>)
        +getRKNN(O, int): DoubleDBIDList
    }

    interface "<size:14>RKNNSearcher\n<size:10>elki.database.query.rknn" as elki.database.query.rknn.RKNNSearcher<O> [[../../database/query/rknn/RKNNSearcher.html]] {
        {abstract} +getRKNN(O, int): DoubleDBIDList
    }
    class "<size:14>ProjectedIndex\n<size:10>elki.index.projected" as elki.index.projected.ProjectedIndex<O, I> [[ProjectedIndex.html]]

    elki.database.query.rknn.RKNNSearcher <|.. elki.index.projected.ProjectedIndex.ProjectedRKNNByObject
    elki.index.projected.ProjectedIndex +-- elki.index.projected.ProjectedIndex.ProjectedRKNNByObject

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
