@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LinearScanKNNByObject\n<size:10>elki.database.query.knn" as elki.database.query.knn.LinearScanKNNByObject<O> [[LinearScanKNNByObject.html]] {
        -distanceQuery: DistanceQuery<O>
        +LinearScanKNNByObject(DistanceQuery<O>)
        +getKNN(O, int): KNNList
    }

    interface "<size:14>KNNSearcher\n<size:10>elki.database.query.knn" as elki.database.query.knn.KNNSearcher<O> [[KNNSearcher.html]] {
        {abstract} +getKNN(O, int): KNNList
    }
    interface "<size:14>LinearScanQuery\n<size:10>elki.database.query" as elki.database.query.LinearScanQuery [[../LinearScanQuery.html]]

    elki.database.query.knn.KNNSearcher <|.. elki.database.query.knn.LinearScanKNNByObject
    elki.database.query.LinearScanQuery <|.. elki.database.query.knn.LinearScanKNNByObject

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
