@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>CorePredicate\n<size:10>elki.clustering.dbscan.predicates" as elki.clustering.dbscan.predicates.CorePredicate<T> [[CorePredicate.html]] {
        {abstract} +instantiate(Database): Instance<T>
        {abstract} +acceptsType(SimpleTypeInformation<? extends T>): boolean
    }
    interface "<size:14>CorePredicate.Instance\n<size:10>elki.clustering.dbscan.predicates" as elki.clustering.dbscan.predicates.CorePredicate.Instance<T> [[CorePredicate.Instance.html]]

    elki.clustering.dbscan.predicates.CorePredicate +-- elki.clustering.dbscan.predicates.CorePredicate.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
