@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>OPTICSPlotSelectionVisualization\n<size:10>elki.visualization.visualizers.optics" as elki.visualization.visualizers.optics.OPTICSPlotSelectionVisualization [[OPTICSPlotSelectionVisualization.html]] {
        {static} -LOG: Logging
        {static} -NAME: String
        +processNewResult(VisualizerContext, Object): void
        +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
        +allowThumbnails(VisualizationTask): boolean
    }

    interface "<size:14>VisFactory\n<size:10>elki.visualization.visualizers" as elki.visualization.visualizers.VisFactory [[../VisFactory.html]] {
        {abstract} +processNewResult(VisualizerContext, Object): void
        {abstract} +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
    }
    enum "<size:14>OPTICSPlotSelectionVisualization.Mode\n<size:10>elki.visualization.visualizers.optics" as elki.visualization.visualizers.optics.OPTICSPlotSelectionVisualization.Mode [[OPTICSPlotSelectionVisualization.Mode.html]]
    class "<size:14>OPTICSPlotSelectionVisualization.Instance\n<size:10>elki.visualization.visualizers.optics" as elki.visualization.visualizers.optics.OPTICSPlotSelectionVisualization.Instance [[OPTICSPlotSelectionVisualization.Instance.html]]

    elki.visualization.visualizers.VisFactory <|.. elki.visualization.visualizers.optics.OPTICSPlotSelectionVisualization
    elki.visualization.visualizers.optics.OPTICSPlotSelectionVisualization +-- elki.visualization.visualizers.optics.OPTICSPlotSelectionVisualization.Mode
    elki.visualization.visualizers.optics.OPTICSPlotSelectionVisualization +-- elki.visualization.visualizers.optics.OPTICSPlotSelectionVisualization.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
