@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>OPTICSClusterVisualization.Instance\n<size:10>elki.visualization.visualizers.optics" as elki.visualization.visualizers.optics.OPTICSClusterVisualization.Instance [[OPTICSClusterVisualization.Instance.html]] {
        {static} #CSS_BRACKET: String
        ~clus: Clustering<OPTICSModel>
        +Instance(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection)
        +fullRedraw(): void
        -drawClusters(Clustering<OPTICSModel>, It<Cluster<OPTICSModel>>, int, Map<Cluster<?>, String>): void
        -addCSSClasses(): void
    }

    abstract class "<size:14>AbstractOPTICSVisualization\n<size:10>elki.visualization.visualizers.optics" as elki.visualization.visualizers.optics.AbstractOPTICSVisualization [[AbstractOPTICSVisualization.html]]
    class "<size:14>OPTICSClusterVisualization\n<size:10>elki.visualization.visualizers.optics" as elki.visualization.visualizers.optics.OPTICSClusterVisualization [[OPTICSClusterVisualization.html]]

    elki.visualization.visualizers.optics.AbstractOPTICSVisualization <|-- elki.visualization.visualizers.optics.OPTICSClusterVisualization.Instance
    elki.visualization.visualizers.optics.OPTICSClusterVisualization +-- elki.visualization.visualizers.optics.OPTICSClusterVisualization.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
