@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>OPTICSPlotVisualizer.Instance\n<size:10>elki.visualization.visualizers.optics" as elki.visualization.visualizers.optics.OPTICSPlotVisualizer.Instance [[OPTICSPlotVisualizer.Instance.html]] {
        +Instance(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection)
        +fullRedraw(): void
    }

    abstract class "<size:14>AbstractOPTICSVisualization\n<size:10>elki.visualization.visualizers.optics" as elki.visualization.visualizers.optics.AbstractOPTICSVisualization [[AbstractOPTICSVisualization.html]]
    class "<size:14>OPTICSPlotVisualizer\n<size:10>elki.visualization.visualizers.optics" as elki.visualization.visualizers.optics.OPTICSPlotVisualizer [[OPTICSPlotVisualizer.html]]

    elki.visualization.visualizers.optics.AbstractOPTICSVisualization <|-- elki.visualization.visualizers.optics.OPTICSPlotVisualizer.Instance
    elki.visualization.visualizers.optics.OPTICSPlotVisualizer +-- elki.visualization.visualizers.optics.OPTICSPlotVisualizer.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
