@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractDBIDSimilarity\n<size:10>elki.similarity" as elki.similarity.AbstractDBIDSimilarity [[AbstractDBIDSimilarity.html]] {
        #database: Relation<? extends DBID>
        +AbstractDBIDSimilarity(Relation<? extends DBID>)
    }

    interface "<size:14>DBIDSimilarity\n<size:10>elki.similarity" as elki.similarity.DBIDSimilarity [[DBIDSimilarity.html]]

    elki.similarity.DBIDSimilarity <|.. elki.similarity.AbstractDBIDSimilarity

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
