@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>IndexBasedSimilarity\n<size:10>elki.similarity" as elki.similarity.IndexBasedSimilarity<O> [[IndexBasedSimilarity.html]] {
        {abstract} +instantiate(Relation<T extends O>): Instance<T extends O, ?>
    }

    interface "<size:14>Similarity\n<size:10>elki.similarity" as elki.similarity.Similarity<O> [[Similarity.html]] {
        {abstract} +getInputTypeRestriction(): TypeInformation
        {abstract} +instantiate(Relation<T extends O>): SimilarityQuery<T extends O>
    }
    interface "<size:14>IndexBasedSimilarity.Instance\n<size:10>elki.similarity" as elki.similarity.IndexBasedSimilarity.Instance<T, I extends Index> [[IndexBasedSimilarity.Instance.html]]

    elki.similarity.Similarity <|-- elki.similarity.IndexBasedSimilarity
    elki.similarity.IndexBasedSimilarity +-- elki.similarity.IndexBasedSimilarity.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
