@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>NormalizedPrimitiveSimilarity\n<size:10>elki.similarity" as elki.similarity.NormalizedPrimitiveSimilarity<O> [[NormalizedPrimitiveSimilarity.html]]

    interface "<size:14>PrimitiveSimilarity\n<size:10>elki.similarity" as elki.similarity.PrimitiveSimilarity<O> [[PrimitiveSimilarity.html]] {
        {abstract} +similarity(O, O): double
    }
    interface "<size:14>NormalizedSimilarity\n<size:10>elki.similarity" as elki.similarity.NormalizedSimilarity<O> [[NormalizedSimilarity.html]]

    elki.similarity.PrimitiveSimilarity <|-- elki.similarity.NormalizedPrimitiveSimilarity
    elki.similarity.NormalizedSimilarity <|-- elki.similarity.NormalizedPrimitiveSimilarity

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
