@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractCutDendrogram\n<size:10>elki.clustering.hierarchical.extraction" as elki.clustering.hierarchical.extraction.AbstractCutDendrogram [[AbstractCutDendrogram.html]] {
        #hierarchical: boolean
        #algorithm: HierarchicalClusteringAlgorithm
        #simplify: boolean
        +AbstractCutDendrogram(HierarchicalClusteringAlgorithm, boolean, boolean)
        +run(Database): Clustering<DendrogramModel>
        {abstract} +run(ClusterMergeHistory): Clustering<DendrogramModel>
        +getInputTypeRestriction(): TypeInformation[]
        {abstract} #getLogger(): Logging
    }

    interface "<size:14>ClusteringAlgorithm\n<size:10>elki.clustering" as elki.clustering.ClusteringAlgorithm<Clustering<DendrogramModel>> [[../../ClusteringAlgorithm.html]]
    abstract class "<size:14>AbstractCutDendrogram.Instance\n<size:10>elki.clustering.hierarchical.extraction" as elki.clustering.hierarchical.extraction.AbstractCutDendrogram.Instance [[AbstractCutDendrogram.Instance.html]]
    abstract class "<size:14>AbstractCutDendrogram.Par\n<size:10>elki.clustering.hierarchical.extraction" as elki.clustering.hierarchical.extraction.AbstractCutDendrogram.Par [[AbstractCutDendrogram.Par.html]]

    elki.clustering.ClusteringAlgorithm <|.. elki.clustering.hierarchical.extraction.AbstractCutDendrogram
    elki.clustering.hierarchical.extraction.AbstractCutDendrogram +-- elki.clustering.hierarchical.extraction.AbstractCutDendrogram.Instance
    elki.clustering.hierarchical.extraction.AbstractCutDendrogram +-- elki.clustering.hierarchical.extraction.AbstractCutDendrogram.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
