@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>KMeansQualityMeasure\n<size:10>elki.clustering.kmeans.quality" as elki.clustering.kmeans.quality.KMeansQualityMeasure<O extends NumberVector> [[KMeansQualityMeasure.html]] {
        {abstract} +quality(Clustering<? extends MeanModel>, NumberVectorDistance<? super NumberVector>, Relation<V extends NumberVector>): double
        {abstract} +isBetter(double, double): boolean
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
