@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RadialBasisFunctionKernel\n<size:10>elki.similarity.kernel" as elki.similarity.kernel.RadialBasisFunctionKernel [[RadialBasisFunctionKernel.html]] {
        -mgamma: double
        +RadialBasisFunctionKernel(double)
        +similarity(NumberVector, NumberVector): double
    }

    abstract class "<size:14>AbstractVectorSimilarity\n<size:10>elki.similarity" as elki.similarity.AbstractVectorSimilarity [[../AbstractVectorSimilarity.html]]
    class "<size:14>RadialBasisFunctionKernel.Par\n<size:10>elki.similarity.kernel" as elki.similarity.kernel.RadialBasisFunctionKernel.Par [[RadialBasisFunctionKernel.Par.html]]

    elki.similarity.AbstractVectorSimilarity <|-- elki.similarity.kernel.RadialBasisFunctionKernel
    elki.similarity.kernel.RadialBasisFunctionKernel +-- elki.similarity.kernel.RadialBasisFunctionKernel.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
