@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RandomSamplingStreamFilter\n<size:10>elki.datasource.filter.selection" as elki.datasource.filter.selection.RandomSamplingStreamFilter [[RandomSamplingStreamFilter.html]] {
        #prob: double
        #random: Random
        +RandomSamplingStreamFilter(double, RandomFactory)
        +getMeta(): BundleMeta
        +data(int): Object
        +nextEvent(): Event
    }

    abstract class "<size:14>AbstractStreamFilter\n<size:10>elki.datasource.filter" as elki.datasource.filter.AbstractStreamFilter [[../AbstractStreamFilter.html]]
    class "<size:14>RandomSamplingStreamFilter.Par\n<size:10>elki.datasource.filter.selection" as elki.datasource.filter.selection.RandomSamplingStreamFilter.Par [[RandomSamplingStreamFilter.Par.html]]

    elki.datasource.filter.AbstractStreamFilter <|-- elki.datasource.filter.selection.RandomSamplingStreamFilter
    elki.datasource.filter.selection.RandomSamplingStreamFilter +-- elki.datasource.filter.selection.RandomSamplingStreamFilter.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
