@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SortByLabelFilter\n<size:10>elki.datasource.filter.selection" as elki.datasource.filter.selection.SortByLabelFilter [[SortByLabelFilter.html]] {
        {static} -LOG: Logging
        +filter(MultipleObjectsBundle): MultipleObjectsBundle
    }

    interface "<size:14>ObjectFilter\n<size:10>elki.datasource.filter" as elki.datasource.filter.ObjectFilter [[../ObjectFilter.html]] {
        {abstract} +filter(MultipleObjectsBundle): MultipleObjectsBundle
    }

    elki.datasource.filter.ObjectFilter <|.. elki.datasource.filter.selection.SortByLabelFilter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
