@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractSilhouetteVisualization\n<size:10>elki.visualization.visualizers.silhouette" as elki.visualization.visualizers.silhouette.AbstractSilhouetteVisualization [[AbstractSilhouetteVisualization.html]] {
        #silhouette: SilhouetteProjection
        #plotwidth: double
        #plotheight: double
        +AbstractSilhouetteVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection)
        #makeLayerElement(): void
    }

    abstract class "<size:14>AbstractVisualization\n<size:10>elki.visualization.visualizers" as elki.visualization.visualizers.AbstractVisualization [[../AbstractVisualization.html]] {
        {abstract} +fullRedraw(): void
    }

    elki.visualization.visualizers.AbstractVisualization <|-- elki.visualization.visualizers.silhouette.AbstractSilhouetteVisualization

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
