@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SilhouettePlotVisualizer.Instance\n<size:10>elki.visualization.visualizers.silhouette" as elki.visualization.visualizers.silhouette.SilhouettePlotVisualizer.Instance [[SilhouettePlotVisualizer.Instance.html]] {
        +Instance(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection)
        +fullRedraw(): void
    }

    abstract class "<size:14>AbstractSilhouetteVisualization\n<size:10>elki.visualization.visualizers.silhouette" as elki.visualization.visualizers.silhouette.AbstractSilhouetteVisualization [[AbstractSilhouetteVisualization.html]]
    class "<size:14>SilhouettePlotVisualizer\n<size:10>elki.visualization.visualizers.silhouette" as elki.visualization.visualizers.silhouette.SilhouettePlotVisualizer [[SilhouettePlotVisualizer.html]]

    elki.visualization.visualizers.silhouette.AbstractSilhouetteVisualization <|-- elki.visualization.visualizers.silhouette.SilhouettePlotVisualizer.Instance
    elki.visualization.visualizers.silhouette.SilhouettePlotVisualizer +-- elki.visualization.visualizers.silhouette.SilhouettePlotVisualizer.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
