@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SilhouettePlotVisualizer\n<size:10>elki.visualization.visualizers.silhouette" as elki.visualization.visualizers.silhouette.SilhouettePlotVisualizer [[SilhouettePlotVisualizer.html]] {
        {static} -NAME: String
        +processNewResult(VisualizerContext, Object): void
        +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
        +allowThumbnails(VisualizationTask): boolean
    }

    interface "<size:14>VisFactory\n<size:10>elki.visualization.visualizers" as elki.visualization.visualizers.VisFactory [[../VisFactory.html]] {
        {abstract} +processNewResult(VisualizerContext, Object): void
        {abstract} +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
    }
    class "<size:14>SilhouettePlotVisualizer.Instance\n<size:10>elki.visualization.visualizers.silhouette" as elki.visualization.visualizers.silhouette.SilhouettePlotVisualizer.Instance [[SilhouettePlotVisualizer.Instance.html]]

    elki.visualization.visualizers.VisFactory <|.. elki.visualization.visualizers.silhouette.SilhouettePlotVisualizer
    elki.visualization.visualizers.silhouette.SilhouettePlotVisualizer +-- elki.visualization.visualizers.silhouette.SilhouettePlotVisualizer.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
