@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ListBasedColorLibrary\n<size:10>elki.visualization.colors" as elki.visualization.colors.ListBasedColorLibrary [[ListBasedColorLibrary.html]] {
        -colors: String[]
        -name: String
        +ListBasedColorLibrary(String[], String)
        +getColor(int): String
        +getNumberOfNativeColors(): int
        #getName(): String
    }

    interface "<size:14>ColorLibrary\n<size:10>elki.visualization.colors" as elki.visualization.colors.ColorLibrary [[ColorLibrary.html]] {
        {abstract} +getNumberOfNativeColors(): int
        {abstract} +getColor(int): String
    }

    elki.visualization.colors.ColorLibrary <|.. elki.visualization.colors.ListBasedColorLibrary

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
