@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MTreeFactory.Par\n<size:10>elki.index.tree.metrical.mtreevariants.mtree" as elki.index.tree.metrical.mtreevariants.mtree.MTreeFactory.Par<O> {
        +make(): MTreeFactory<O>
        #makeSettings(): MTreeSettings<O, MTreeNode<O>, MTreeEntry>
    }

    abstract class "<size:14>AbstractMTreeFactory.Par\n<size:10>elki.index.tree.metrical.mtreevariants" as elki.index.tree.metrical.mtreevariants.AbstractMTreeFactory.Par<O, MTreeNode<O>, MTreeEntry, MTreeSettings<O, MTreeNode<O>, MTreeEntry>> [[../AbstractMTreeFactory.Par.html]] {
        {abstract} #makeSettings(): MTreeSettings<O, MTreeNode<O>, MTreeEntry>
        {abstract} +make(): AbstractMTreeFactory<O, N extends AbstractMTreeNode<O, N, E extends MTreeEntry>, E extends MTreeEntry, ?>
    }
    class "<size:14>MTreeFactory\n<size:10>elki.index.tree.metrical.mtreevariants.mtree" as elki.index.tree.metrical.mtreevariants.mtree.MTreeFactory<O> [[MTreeFactory.html]]

    elki.index.tree.metrical.mtreevariants.AbstractMTreeFactory.Par <|-- elki.index.tree.metrical.mtreevariants.mtree.MTreeFactory.Par
    elki.index.tree.metrical.mtreevariants.mtree.MTreeFactory +-- elki.index.tree.metrical.mtreevariants.mtree.MTreeFactory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
