@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>HammingDistance.Par\n<size:10>elki.distance.set" as elki.distance.set.HammingDistance.Par [[HammingDistance.Par.html]] {
        +make(): HammingDistance
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>HammingDistance\n<size:10>elki.distance.set" as elki.distance.set.HammingDistance [[HammingDistance.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.distance.set.HammingDistance.Par
    elki.distance.set.HammingDistance +-- elki.distance.set.HammingDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
