@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractProjectionAlgorithm\n<size:10>elki.projection" as elki.projection.AbstractProjectionAlgorithm<R> [[AbstractProjectionAlgorithm.html]] {
        -keep: boolean
        {static} +KEEP_ID: OptionID
        +AbstractProjectionAlgorithm(boolean)
        #removePreviousRelation(Relation<?>): void
    }

    interface "<size:14>Algorithm\n<size:10>elki" as elki.Algorithm [[../Algorithm.html]] {
        {abstract} +getInputTypeRestriction(): TypeInformation[]
    }

    elki.Algorithm <|.. elki.projection.AbstractProjectionAlgorithm

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
