@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PerplexityAffinityMatrixBuilder.Par\n<size:10>elki.projection" as elki.projection.PerplexityAffinityMatrixBuilder.Par<O> [[PerplexityAffinityMatrixBuilder.Par.html]] {
        {static} +PERPLEXITY_ID: OptionID
        #perplexity: double
        #distance: Distance<? super O>
        +configure(Parameterization): void
        +make(): PerplexityAffinityMatrixBuilder<O>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>PerplexityAffinityMatrixBuilder\n<size:10>elki.projection" as elki.projection.PerplexityAffinityMatrixBuilder<O> [[PerplexityAffinityMatrixBuilder.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.projection.PerplexityAffinityMatrixBuilder.Par
    elki.projection.PerplexityAffinityMatrixBuilder +-- elki.projection.PerplexityAffinityMatrixBuilder.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
