@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>GaussianKernelDensityFunction.Par\n<size:10>elki.math.statistics.kernelfunctions" as elki.math.statistics.kernelfunctions.GaussianKernelDensityFunction.Par [[GaussianKernelDensityFunction.Par.html]] {
        +make(): GaussianKernelDensityFunction
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>GaussianKernelDensityFunction\n<size:10>elki.math.statistics.kernelfunctions" as elki.math.statistics.kernelfunctions.GaussianKernelDensityFunction [[GaussianKernelDensityFunction.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.math.statistics.kernelfunctions.GaussianKernelDensityFunction.Par
    elki.math.statistics.kernelfunctions.GaussianKernelDensityFunction +-- elki.math.statistics.kernelfunctions.GaussianKernelDensityFunction.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
