@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>DendrogramVisualization.DrawingStyle\n<size:10>elki.visualization.visualizers.visunproj" as elki.visualization.visualizers.visunproj.DendrogramVisualization.DrawingStyle [[DendrogramVisualization.DrawingStyle.html]] {
        {static} +RECTANGULAR
        {static} +TRIANGULAR_MAX
        {static} +TRIANGULAR
    }

    class "<size:14>DendrogramVisualization\n<size:10>elki.visualization.visualizers.visunproj" as elki.visualization.visualizers.visunproj.DendrogramVisualization [[DendrogramVisualization.html]]

    elki.visualization.visualizers.visunproj.DendrogramVisualization +-- elki.visualization.visualizers.visunproj.DendrogramVisualization.DrawingStyle

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
