@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ClassTree\n<size:10>elki.gui.util" as elki.gui.util.ClassTree [[ClassTree.html]] {
        {static} +build(List<Class<?>>, String): TreeNode
        {static} -simplifyTree(MutableTreeNode, String): MutableTreeNode
    }
    class "<size:14>ClassTree.PackageNode\n<size:10>elki.gui.util" as elki.gui.util.ClassTree.PackageNode [[ClassTree.PackageNode.html]]
    class "<size:14>ClassTree.ClassNode\n<size:10>elki.gui.util" as elki.gui.util.ClassTree.ClassNode [[ClassTree.ClassNode.html]]

    elki.gui.util.ClassTree +-- elki.gui.util.ClassTree.PackageNode
    elki.gui.util.ClassTree +-- elki.gui.util.ClassTree.ClassNode

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
