@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractRefiningIndex.AbstractRefiningQuery\n<size:10>elki.index" as elki.index.AbstractRefiningIndex.AbstractRefiningQuery [[AbstractRefiningIndex.AbstractRefiningQuery.html]] {
        #distanceQuery: DistanceQuery<O>
        +AbstractRefiningQuery(DistanceQuery<O>)
        #refine(DBIDRef, O): double
        #incRefinements(int): void
    }

    abstract class "<size:14>AbstractRefiningIndex\n<size:10>elki.index" as elki.index.AbstractRefiningIndex<O> [[AbstractRefiningIndex.html]] {
        {abstract} +getLogger(): Logging
    }

    elki.index.AbstractRefiningIndex +-- elki.index.AbstractRefiningIndex.AbstractRefiningQuery

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
