@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>RKNNIndex\n<size:10>elki.index" as elki.index.RKNNIndex<O> [[RKNNIndex.html]] {
        {abstract} +rkNNByObject(DistanceQuery<O>, int, int): RKNNSearcher<O>
        {abstract} +rkNNByDBID(DistanceQuery<O>, int, int): RKNNSearcher<DBIDRef>
    }

    interface "<size:14>Index\n<size:10>elki.index" as elki.index.Index [[Index.html]] {
        {abstract} +initialize(): void
    }

    elki.index.Index <|-- elki.index.RKNNIndex

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
