@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>SimilarityRangeIndex\n<size:10>elki.index" as elki.index.SimilarityRangeIndex<O> [[SimilarityRangeIndex.html]] {
        {abstract} +similarityRangeByObject(SimilarityQuery<O>, double, int): RangeSearcher<O>
        {abstract} +similarityRangeByDBID(SimilarityQuery<O>, double, int): RangeSearcher<DBIDRef>
    }

    interface "<size:14>Index\n<size:10>elki.index" as elki.index.Index [[Index.html]] {
        {abstract} +initialize(): void
    }

    elki.index.Index <|-- elki.index.SimilarityRangeIndex

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
