@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RepresentativeUncertainClustering\n<size:10>elki.clustering.uncertain" as elki.clustering.uncertain.RepresentativeUncertainClustering [[RepresentativeUncertainClustering.html]] {
        {static} -LOG: Logging
        #distance: ClusteringDistanceSimilarity
        #metaAlgorithm: ClusteringAlgorithm<?>
        #samplesAlgorithm: ClusteringAlgorithm<?>
        #numsamples: int
        #random: RandomFactory
        #alpha: double
        #keep: boolean
        +RepresentativeUncertainClustering(ClusteringDistanceSimilarity, ClusteringAlgorithm<?>, ClusteringAlgorithm<?>, int, RandomFactory, double, boolean)
        +getInputTypeRestriction(): TypeInformation[]
        +run(Database, Relation<? extends UncertainObject>): Clustering<?>
        -computeConfidence(int, int): double
        #runClusteringAlgorithm(Object, DBIDs, DataStore<DoubleVector>, int, String): Clustering<?>
    }

    interface "<size:14>ClusteringAlgorithm\n<size:10>elki.clustering" as elki.clustering.ClusteringAlgorithm<Clustering<?>> [[../ClusteringAlgorithm.html]]
    class "<size:14>RepresentativeUncertainClustering.RepresentativenessEvaluation\n<size:10>elki.clustering.uncertain" as elki.clustering.uncertain.RepresentativeUncertainClustering.RepresentativenessEvaluation [[RepresentativeUncertainClustering.RepresentativenessEvaluation.html]]
    class "<size:14>RepresentativeUncertainClustering.Par\n<size:10>elki.clustering.uncertain" as elki.clustering.uncertain.RepresentativeUncertainClustering.Par [[RepresentativeUncertainClustering.Par.html]]

    elki.clustering.ClusteringAlgorithm <|.. elki.clustering.uncertain.RepresentativeUncertainClustering
    elki.clustering.uncertain.RepresentativeUncertainClustering +-- elki.clustering.uncertain.RepresentativeUncertainClustering.RepresentativenessEvaluation
    elki.clustering.uncertain.RepresentativeUncertainClustering +-- elki.clustering.uncertain.RepresentativeUncertainClustering.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
