@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>COPAC.Settings\n<size:10>elki.clustering.correlation" as elki.clustering.correlation.COPAC.Settings [[COPAC.Settings.html]] {
        +k: int
        +pca: PCARunner
        +filter: EigenPairFilter
        +epsilon: double
        +minpts: int
    }

    class "<size:14>COPAC\n<size:10>elki.clustering.correlation" as elki.clustering.correlation.COPAC [[COPAC.html]]

    elki.clustering.correlation.COPAC +-- elki.clustering.correlation.COPAC.Settings

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
