@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SVGCheckbox\n<size:10>elki.visualization.svg" as elki.visualization.svg.SVGCheckbox [[SVGCheckbox.html]] {
        #checked: boolean
        #listenerList: EventListenerList
        #label: String
        +SVGCheckbox(boolean)
        +SVGCheckbox(boolean, String)
        +renderCheckBox(SVGPlot, double, double, double): Element
        +addCheckBoxListener(ChangeListener): void
        +removeCheckBoxListener(ChangeListener): void
        +isChecked(): boolean
        #fireSwitchEvent(ChangeEvent): void
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
