@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SVGHyperSphere\n<size:10>elki.visualization.svg" as elki.visualization.svg.SVGHyperSphere [[SVGHyperSphere.html]] {
        {static} +EUCLIDEAN_KAPPA: double
        {static} +drawManhattan(SVGPlot, Projection2D, NumberVector, double): Element
        {static} +drawEuclidean(SVGPlot, Projection2D, NumberVector, double): Element
        {static} +drawLp(SVGPlot, Projection2D, NumberVector, double, double): Element
        {static} +drawCross(SVGPlot, Projection2D, NumberVector, double): Element
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
