@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SVGPath\n<size:10>elki.visualization.svg" as elki.visualization.svg.SVGPath [[SVGPath.html]] {
        -buf: StringBuilder
        -lastaction: char
        {static} +PATH_CLOSE: char
        {static} +PATH_LINE_TO: char
        {static} +PATH_LINE_TO_RELATIVE: char
        {static} +PATH_MOVE: char
        {static} +PATH_MOVE_RELATIVE: char
        {static} +PATH_HORIZONTAL_LINE_TO: char
        {static} +PATH_HORIZONTAL_LINE_TO_RELATIVE: char
        {static} +PATH_VERTICAL_LINE_TO: char
        {static} +PATH_VERTICAL_LINE_TO_RELATIVE: char
        {static} +PATH_CUBIC_TO: char
        {static} +PATH_CUBIC_TO_RELATIVE: char
        {static} +PATH_SMOOTH_CUBIC_TO: char
        {static} +PATH_SMOOTH_CUBIC_TO_RELATIVE: char
        {static} +PATH_QUAD_TO: char
        {static} +PATH_QUAD_TO_RELATIVE: char
        {static} +PATH_SMOOTH_QUAD_TO: char
        {static} +PATH_SMOOTH_QUAD_TO_RELATIVE: char
        {static} +PATH_ARC: char
        {static} +PATH_ARC_RELATIVE: char
        +SVGPath()
        +SVGPath(double, double)
        +SVGPath(double[])
        +SVGPath(Polygon)
        +drawTo(double, double): SVGPath
        +drawTo(double[]): SVGPath
        +isStarted(): boolean
        +lineTo(double, double): SVGPath
        +lineTo(double[]): SVGPath
        +relativeLineTo(double, double): SVGPath
        +relativeLineTo(double[]): SVGPath
        +horizontalLineTo(double): SVGPath
        +relativeHorizontalLineTo(double): SVGPath
        +verticalLineTo(double): SVGPath
        +relativeVerticalLineTo(double): SVGPath
        +moveTo(double, double): SVGPath
        +moveTo(double[]): SVGPath
        +relativeMoveTo(double, double): SVGPath
        +relativeMoveTo(double[]): SVGPath
        +cubicTo(double, double, double, double, double, double): SVGPath
        +cubicTo(double[], double[], double[]): SVGPath
        +relativeCubicTo(double, double, double, double, double, double): SVGPath
        +relativeCubicTo(double[], double[], double[]): SVGPath
        +smoothCubicTo(double, double, double, double): SVGPath
        +smoothCubicTo(double[], double[]): SVGPath
        +relativeSmoothCubicTo(double, double, double, double): SVGPath
        +relativeSmoothCubicTo(double[], double[]): SVGPath
        +quadTo(double, double, double, double): SVGPath
        +quadTo(double[], double[]): SVGPath
        +relativeQuadTo(double, double, double, double): SVGPath
        +relativeQuadTo(double[], double[]): SVGPath
        +smoothQuadTo(double, double): SVGPath
        +smoothQuadTo(double[]): SVGPath
        +relativeSmoothQuadTo(double, double): SVGPath
        +relativeSmoothQuadTo(double[]): SVGPath
        +ellipticalArc(double, double, double, double, double, double, double): SVGPath
        +ellipticalArc(double, double, double, double, double, double[]): SVGPath
        +ellipticalArc(double[], double, double, double, double[]): SVGPath
        +relativeEllipticalArc(double, double, double, double, double, double, double): SVGPath
        +relativeEllipticalArc(double, double, double, double, double, double[]): SVGPath
        +relativeEllipticalArc(double[], double, double, double, double[]): SVGPath
        -append(char): SVGPath
        -append(double): SVGPath
        +close(): SVGPath
        +makeElement(SVGPlot): Element
        +makeElement(SVGPlot, String): Element
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
