@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SVGScoreBar\n<size:10>elki.visualization.svg" as elki.visualization.svg.SVGScoreBar [[SVGScoreBar.html]] {
        #val: double
        #min: double
        #max: double
        #reversed: boolean
        #label: String
        -format: NumberFormat
        +setFill(double, double, double): void
        +setReversed(boolean): void
        +addLabel(String): void
        +showValues(NumberFormat): void
        +build(SVGPlot, double, double, double, double): Element
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
