@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ArrayIter\n<size:10>elki.utilities.datastructures.iterator" as elki.utilities.datastructures.iterator.ArrayIter [[ArrayIter.html]] {
        {abstract} +advance(): ArrayIter
        {abstract} +advance(int): ArrayIter
        {abstract} +retract(): ArrayIter
        {abstract} +seek(int): ArrayIter
        {abstract} +getOffset(): int
    }

    interface "<size:14>Iter\n<size:10>elki.utilities.datastructures.iterator" as elki.utilities.datastructures.iterator.Iter [[Iter.html]] {
        {abstract} +valid(): boolean
        {abstract} +advance(): Iter
    }

    elki.utilities.datastructures.iterator.Iter <|-- elki.utilities.datastructures.iterator.ArrayIter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
