@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ArrayListIter\n<size:10>elki.utilities.datastructures.iterator" as elki.utilities.datastructures.iterator.ArrayListIter<O> [[ArrayListIter.html]] {
        ~data: List<O>
        ~pos: int
        +ArrayListIter(List<O>)
        +valid(): boolean
        +advance(): ArrayListIter<O>
        +getOffset(): int
        +advance(int): ArrayListIter<O>
        +retract(): ArrayListIter<O>
        +seek(int): ArrayListIter<O>
        +get(): O
    }

    interface "<size:14>ArrayIter\n<size:10>elki.utilities.datastructures.iterator" as elki.utilities.datastructures.iterator.ArrayIter [[ArrayIter.html]] {
        {abstract} +advance(): ArrayIter
        {abstract} +advance(int): ArrayIter
        {abstract} +retract(): ArrayIter
        {abstract} +seek(int): ArrayIter
        {abstract} +getOffset(): int
    }
    interface "<size:14>It\n<size:10>elki.utilities.datastructures.iterator" as elki.utilities.datastructures.iterator.It<O> [[It.html]] {
        {abstract} +get(): O
        {abstract} +advance(): It<O>
    }

    elki.utilities.datastructures.iterator.ArrayIter <|.. elki.utilities.datastructures.iterator.ArrayListIter
    elki.utilities.datastructures.iterator.It <|.. elki.utilities.datastructures.iterator.ArrayListIter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
