@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>EmptyIterator\n<size:10>elki.utilities.datastructures.iterator" as elki.utilities.datastructures.iterator.EmptyIterator<O> [[EmptyIterator.html]] {
        {static} -STATIC: It<Object>
        {static} +empty(): It<O>
        +valid(): boolean
        +advance(): It<O>
        +get(): O
        +filter(Class<? super T>): It<T>
        +filter(Predicate<? super O>): It<O>
        +forEach(Consumer<? super O>): void
    }

    interface "<size:14>It\n<size:10>elki.utilities.datastructures.iterator" as elki.utilities.datastructures.iterator.It<O> [[It.html]] {
        {abstract} +get(): O
        {abstract} +advance(): It<O>
    }

    elki.utilities.datastructures.iterator.It <|.. elki.utilities.datastructures.iterator.EmptyIterator

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
