@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>KNNProcessor\n<size:10>elki.parallel.processor" as elki.parallel.processor.KNNProcessor [[KNNProcessor.html]] {
        ~k: int
        ~knnq: Supplier<KNNSearcher<DBIDRef>>
        ~out: SharedObject<KNNList>
        +KNNProcessor(int, Supplier<KNNSearcher<DBIDRef>>)
        +connectKNNOutput(SharedObject<KNNList>): void
        +instantiate(Executor): Instance
        +cleanup(Instance): void
    }

    interface "<size:14>Processor\n<size:10>elki.parallel.processor" as elki.parallel.processor.Processor [[Processor.html]] {
        {abstract} +instantiate(Executor): Instance
        {abstract} +cleanup(Instance): void
    }
    class "<size:14>KNNProcessor.Instance\n<size:10>elki.parallel.processor" as elki.parallel.processor.KNNProcessor.Instance [[KNNProcessor.Instance.html]]

    elki.parallel.processor.Processor <|.. elki.parallel.processor.KNNProcessor
    elki.parallel.processor.KNNProcessor +-- elki.parallel.processor.KNNProcessor.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
