@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>WriteDoubleDataStoreProcessor.Instance\n<size:10>elki.parallel.processor" as elki.parallel.processor.WriteDoubleDataStoreProcessor.Instance [[WriteDoubleDataStoreProcessor.Instance.html]] {
        ~input: Instance
        +Instance(Instance)
        +map(DBIDRef): void
    }

    interface "<size:14>Processor.Instance\n<size:10>elki.parallel.processor" as elki.parallel.processor.Processor.Instance [[Processor.Instance.html]] {
        {abstract} +map(DBIDRef): void
    }
    class "<size:14>WriteDoubleDataStoreProcessor\n<size:10>elki.parallel.processor" as elki.parallel.processor.WriteDoubleDataStoreProcessor [[WriteDoubleDataStoreProcessor.html]]

    elki.parallel.processor.Processor.Instance <|.. elki.parallel.processor.WriteDoubleDataStoreProcessor.Instance
    elki.parallel.processor.WriteDoubleDataStoreProcessor +-- elki.parallel.processor.WriteDoubleDataStoreProcessor.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
