@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PrecomputedKNearestNeighborNeighborhood\n<size:10>elki.outlier.spatial.neighborhood" as elki.outlier.spatial.neighborhood.PrecomputedKNearestNeighborNeighborhood [[PrecomputedKNearestNeighborNeighborhood.html]] {
        {static} -LOG: Logging
        +PrecomputedKNearestNeighborNeighborhood(DataStore<DBIDs>)
        #getLogger(): Logging
    }

    abstract class "<size:14>AbstractPrecomputedNeighborhood\n<size:10>elki.outlier.spatial.neighborhood" as elki.outlier.spatial.neighborhood.AbstractPrecomputedNeighborhood [[AbstractPrecomputedNeighborhood.html]] {
        {abstract} #getLogger(): Logging
    }
    class "<size:14>PrecomputedKNearestNeighborNeighborhood.Factory\n<size:10>elki.outlier.spatial.neighborhood" as elki.outlier.spatial.neighborhood.PrecomputedKNearestNeighborNeighborhood.Factory<O> [[PrecomputedKNearestNeighborNeighborhood.Factory.html]]

    elki.outlier.spatial.neighborhood.AbstractPrecomputedNeighborhood <|-- elki.outlier.spatial.neighborhood.PrecomputedKNearestNeighborNeighborhood
    elki.outlier.spatial.neighborhood.PrecomputedKNearestNeighborNeighborhood +-- elki.outlier.spatial.neighborhood.PrecomputedKNearestNeighborNeighborhood.Factory

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
