@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ParallelAxisVisualization\n<size:10>elki.visualization.visualizers.parallel" as elki.visualization.visualizers.parallel.ParallelAxisVisualization [[ParallelAxisVisualization.html]] {
        {static} -LOG: Logging
        {static} -NAME: String
        +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
        +processNewResult(VisualizerContext, Object): void
        +allowThumbnails(VisualizationTask): boolean
    }

    interface "<size:14>VisFactory\n<size:10>elki.visualization.visualizers" as elki.visualization.visualizers.VisFactory [[../VisFactory.html]] {
        {abstract} +processNewResult(VisualizerContext, Object): void
        {abstract} +makeVisualization(VisualizerContext, VisualizationTask, VisualizationPlot, double, double, Projection): Visualization
    }
    class "<size:14>ParallelAxisVisualization.Instance\n<size:10>elki.visualization.visualizers.parallel" as elki.visualization.visualizers.parallel.ParallelAxisVisualization.Instance [[ParallelAxisVisualization.Instance.html]]

    elki.visualization.visualizers.VisFactory <|.. elki.visualization.visualizers.parallel.ParallelAxisVisualization
    elki.visualization.visualizers.parallel.ParallelAxisVisualization +-- elki.visualization.visualizers.parallel.ParallelAxisVisualization.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
