@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>OPTICSHeap\n<size:10>elki.clustering.optics" as elki.clustering.optics.OPTICSHeap<O> [[OPTICSHeap.html]] {
        {static} -LOG: Logging
        +OPTICSHeap(Distance<? super O>, double, int)
        +run(Relation<O>): ClusterOrder
    }

    abstract class "<size:14>AbstractOPTICS\n<size:10>elki.clustering.optics" as elki.clustering.optics.AbstractOPTICS<O> [[AbstractOPTICS.html]] {
        {abstract} +run(Relation<O>): ClusterOrder
    }
    class "<size:14>OPTICSHeap.Instance\n<size:10>elki.clustering.optics" as elki.clustering.optics.OPTICSHeap.Instance [[OPTICSHeap.Instance.html]]
    class "<size:14>OPTICSHeap.Par\n<size:10>elki.clustering.optics" as elki.clustering.optics.OPTICSHeap.Par<O> [[OPTICSHeap.Par.html]]

    elki.clustering.optics.AbstractOPTICS <|-- elki.clustering.optics.OPTICSHeap
    elki.clustering.optics.OPTICSHeap +-- elki.clustering.optics.OPTICSHeap.Instance
    elki.clustering.optics.OPTICSHeap +-- elki.clustering.optics.OPTICSHeap.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
