@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractVectorConversionFilter\n<size:10>elki.datasource.filter" as elki.datasource.filter.AbstractVectorConversionFilter<I, O extends NumberVector> [[AbstractVectorConversionFilter.html]] {
        #factory: Factory<O extends NumberVector>
        #initializeOutputType(SimpleTypeInformation<O extends NumberVector>): void
    }

    abstract class "<size:14>AbstractConversionFilter\n<size:10>elki.datasource.filter" as elki.datasource.filter.AbstractConversionFilter<I, O extends NumberVector> [[AbstractConversionFilter.html]] {
        {abstract} #getLogger(): Logging
        {abstract} #filterSingleObject(I): O extends NumberVector
        {abstract} #getInputTypeRestriction(): SimpleTypeInformation<? super I>
        {abstract} #convertedType(SimpleTypeInformation<​I>): SimpleTypeInformation<? super O>
    }

    elki.datasource.filter.AbstractConversionFilter <|-- elki.datasource.filter.AbstractVectorConversionFilter

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
