@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AssociationRuleGeneration.PartialItemset\n<size:10>elki.itemsetmining.associationrules" as elki.itemsetmining.associationrules.AssociationRuleGeneration.PartialItemset [[AssociationRuleGeneration.PartialItemset.html]] {
        +len: int
        +begin: int
        +indices: int[]
        +PartialItemset(int[])
        +length(): int
        +iter(): int
        +iterValid(int): boolean
        +iterAdvance(int): int
        +iterDim(int): int
    }

    abstract class "<size:14>Itemset\n<size:10>elki.itemsetmining" as elki.itemsetmining.Itemset [[../Itemset.html]] {
        {abstract} +length(): int
        {abstract} +iter(): int
        {abstract} +iterAdvance(int): int
        {abstract} +iterValid(int): boolean
        {abstract} +iterDim(int): int
    }
    class "<size:14>AssociationRuleGeneration\n<size:10>elki.itemsetmining.associationrules" as elki.itemsetmining.associationrules.AssociationRuleGeneration [[AssociationRuleGeneration.html]]

    elki.itemsetmining.Itemset <|-- elki.itemsetmining.associationrules.AssociationRuleGeneration.PartialItemset
    elki.itemsetmining.associationrules.AssociationRuleGeneration +-- elki.itemsetmining.associationrules.AssociationRuleGeneration.PartialItemset

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
