@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>FastCLARANS\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.FastCLARANS<V> [[FastCLARANS.html]] {
        {static} -LOG: Logging
        +FastCLARANS(Distance<? super V>, int, int, double, RandomFactory)
        +run(Relation<V>): Clustering<MedoidModel>
    }

    class "<size:14>CLARANS\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.CLARANS<V> [[CLARANS.html]]
    class "<size:14>FastCLARANS.Assignment\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.FastCLARANS.Assignment [[FastCLARANS.Assignment.html]]
    class "<size:14>FastCLARANS.Par\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.FastCLARANS.Par<V> [[FastCLARANS.Par.html]]

    elki.clustering.kmedoids.CLARANS <|-- elki.clustering.kmedoids.FastCLARANS
    elki.clustering.kmedoids.FastCLARANS +-- elki.clustering.kmedoids.FastCLARANS.Assignment
    elki.clustering.kmedoids.FastCLARANS +-- elki.clustering.kmedoids.FastCLARANS.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
