@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>FastPAM1.Par\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.FastPAM1.Par<V> [[FastPAM1.Par.html]] {
        +make(): FastPAM1<V>
    }

    class "<size:14>PAM.Par\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.PAM.Par<V> [[PAM.Par.html]]
    class "<size:14>FastPAM1\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.FastPAM1<O> [[FastPAM1.html]]

    elki.clustering.kmedoids.PAM.Par <|-- elki.clustering.kmedoids.FastPAM1.Par
    elki.clustering.kmedoids.FastPAM1 +-- elki.clustering.kmedoids.FastPAM1.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
