@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>FastCLARANS.Par\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.FastCLARANS.Par<V> [[FastCLARANS.Par.html]] {
        #defaultRate(): double
        +make(): FastCLARANS<V>
    }

    class "<size:14>CLARANS.Par\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.CLARANS.Par<V> [[CLARANS.Par.html]]
    class "<size:14>FastCLARANS\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.FastCLARANS<V> [[FastCLARANS.html]]

    elki.clustering.kmedoids.CLARANS.Par <|-- elki.clustering.kmedoids.FastCLARANS.Par
    elki.clustering.kmedoids.FastCLARANS +-- elki.clustering.kmedoids.FastCLARANS.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
