@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ReynoldsPAM\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.ReynoldsPAM<O> [[ReynoldsPAM.html]] {
        {static} -LOG: Logging
        {static} -KEY: String
        +ReynoldsPAM(Distance<? super O>, int, int, KMedoidsInitialization<O>)
        +run(Relation<O>, int, DistanceQuery<? super O>): Clustering<MedoidModel>
        #getLogger(): Logging
    }

    class "<size:14>PAM\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.PAM<O> [[PAM.html]]
    class "<size:14>ReynoldsPAM.Instance\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.ReynoldsPAM.Instance [[ReynoldsPAM.Instance.html]]
    class "<size:14>ReynoldsPAM.Par\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.ReynoldsPAM.Par<V> [[ReynoldsPAM.Par.html]]

    elki.clustering.kmedoids.PAM <|-- elki.clustering.kmedoids.ReynoldsPAM
    elki.clustering.kmedoids.ReynoldsPAM +-- elki.clustering.kmedoids.ReynoldsPAM.Instance
    elki.clustering.kmedoids.ReynoldsPAM +-- elki.clustering.kmedoids.ReynoldsPAM.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
