@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SingleAssignmentKMedoids.Instance\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.SingleAssignmentKMedoids.Instance [[SingleAssignmentKMedoids.Instance.html]] {
        ~ids: DBIDs
        ~distQ: DistanceQuery<?>
        ~assignment: WritableIntegerDataStore
        +Instance(DistanceQuery<?>, DBIDs, WritableIntegerDataStore)
        #run(ArrayModifiableDBIDs): double
        #assignToNearestCluster(ArrayModifiableDBIDs): double
    }

    class "<size:14>SingleAssignmentKMedoids\n<size:10>elki.clustering.kmedoids" as elki.clustering.kmedoids.SingleAssignmentKMedoids<O> [[SingleAssignmentKMedoids.html]]

    elki.clustering.kmedoids.SingleAssignmentKMedoids +-- elki.clustering.kmedoids.SingleAssignmentKMedoids.Instance

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
