@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PCARunner\n<size:10>elki.math.linearalgebra.pca" as elki.math.linearalgebra.pca.PCARunner [[PCARunner.html]] {
        #covarianceMatrixBuilder: CovarianceMatrixBuilder
        +PCARunner(CovarianceMatrixBuilder)
        +processIds(DBIDs, Relation<? extends NumberVector>): PCAResult
        +processQueryResult(DoubleDBIDList, Relation<? extends NumberVector>): PCAResult
        +processCovarMatrix(double[]): PCAResult
        +processEVD(EigenvalueDecomposition): PCAResult
        +getCovarianceMatrixBuilder(): CovarianceMatrixBuilder
        +setCovarianceMatrixBuilder(CovarianceMatrixBuilder): void
    }
    class "<size:14>PCARunner.Par\n<size:10>elki.math.linearalgebra.pca" as elki.math.linearalgebra.pca.PCARunner.Par [[PCARunner.Par.html]]

    elki.math.linearalgebra.pca.PCARunner +-- elki.math.linearalgebra.pca.PCARunner.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
