@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RANSACCovarianceMatrixBuilder.Par\n<size:10>elki.math.linearalgebra.pca" as elki.math.linearalgebra.pca.RANSACCovarianceMatrixBuilder.Par [[RANSACCovarianceMatrixBuilder.Par.html]] {
        {static} +ITER_ID: OptionID
        {static} +SEED_ID: OptionID
        ~iterations: int
        ~rnd: RandomFactory
        +configure(Parameterization): void
        +make(): RANSACCovarianceMatrixBuilder
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>RANSACCovarianceMatrixBuilder\n<size:10>elki.math.linearalgebra.pca" as elki.math.linearalgebra.pca.RANSACCovarianceMatrixBuilder [[RANSACCovarianceMatrixBuilder.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.math.linearalgebra.pca.RANSACCovarianceMatrixBuilder.Par
    elki.math.linearalgebra.pca.RANSACCovarianceMatrixBuilder +-- elki.math.linearalgebra.pca.RANSACCovarianceMatrixBuilder.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
