@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>StandardCovarianceMatrixBuilder\n<size:10>elki.math.linearalgebra.pca" as elki.math.linearalgebra.pca.StandardCovarianceMatrixBuilder [[StandardCovarianceMatrixBuilder.html]] {
        +processIds(DBIDs, Relation<? extends NumberVector>): double[]
    }

    interface "<size:14>CovarianceMatrixBuilder\n<size:10>elki.math.linearalgebra.pca" as elki.math.linearalgebra.pca.CovarianceMatrixBuilder [[CovarianceMatrixBuilder.html]] {
        {abstract} +processIds(DBIDs, Relation<? extends NumberVector>): double[]
    }

    elki.math.linearalgebra.pca.CovarianceMatrixBuilder <|.. elki.math.linearalgebra.pca.StandardCovarianceMatrixBuilder

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
