@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>APIViolationException\n<size:10>elki.utilities.exceptions" as elki.utilities.exceptions.APIViolationException [[APIViolationException.html]] {
        {static} -serialVersionUID: long
        +APIViolationException(String)
        +APIViolationException(String, Throwable)
    }

    class "<size:14>AbortException\n<size:10>elki.utilities.exceptions" as elki.utilities.exceptions.AbortException [[AbortException.html]]

    elki.utilities.exceptions.AbortException <|-- elki.utilities.exceptions.APIViolationException

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
