@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MissingPrerequisitesException\n<size:10>elki.utilities.exceptions" as elki.utilities.exceptions.MissingPrerequisitesException [[MissingPrerequisitesException.html]] {
        {static} -serialVersionUID: long
        +MissingPrerequisitesException(String)
        +MissingPrerequisitesException(String, Throwable)
    }

    class "<size:14>AbortException\n<size:10>elki.utilities.exceptions" as elki.utilities.exceptions.AbortException [[AbortException.html]]

    elki.utilities.exceptions.AbortException <|-- elki.utilities.exceptions.MissingPrerequisitesException

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
