@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ObjectBundle\n<size:10>elki.datasource.bundle" as elki.datasource.bundle.ObjectBundle [[ObjectBundle.html]] {
        {abstract} +meta(): BundleMeta
        {abstract} +meta(int): SimpleTypeInformation<?>
        {abstract} +metaLength(): int
        {abstract} +dataLength(): int
        {abstract} +data(int, int): Object
        {abstract} +assignDBID(int, DBIDVar): boolean
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
