@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>StreamFromBundle\n<size:10>elki.datasource.bundle" as elki.datasource.bundle.StreamFromBundle [[StreamFromBundle.html]] {
        ~bundle: MultipleObjectsBundle
        ~onum: int
        +StreamFromBundle(MultipleObjectsBundle)
        +getMeta(): BundleMeta
        +data(int): Object
        +hasDBIDs(): boolean
        +assignDBID(DBIDVar): boolean
        +nextEvent(): Event
        +asMultipleObjectsBundle(): MultipleObjectsBundle
    }

    interface "<size:14>BundleStreamSource\n<size:10>elki.datasource.bundle" as elki.datasource.bundle.BundleStreamSource [[BundleStreamSource.html]] {
        {abstract} +getMeta(): BundleMeta
        {abstract} +data(int): Object
        {abstract} +hasDBIDs(): boolean
        {abstract} +assignDBID(DBIDVar): boolean
        {abstract} +nextEvent(): Event
        {abstract} +asMultipleObjectsBundle(): MultipleObjectsBundle
    }

    elki.datasource.bundle.BundleStreamSource <|.. elki.datasource.bundle.StreamFromBundle

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
