@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>RangeSearcher\n<size:10>elki.database.query.range" as elki.database.query.range.RangeSearcher<O> [[RangeSearcher.html]] {
        +getRange(O, double): DoubleDBIDList
        {abstract} +getRange(O, double, ModifiableDoubleDBIDList): ModifiableDoubleDBIDList
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
