@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ClusterFeature\n<size:10>elki.index.tree.betula.features" as elki.index.tree.betula.features.ClusterFeature [[ClusterFeature.html]] {
        {abstract} +addToStatistics(NumberVector): void
        {abstract} +addToStatistics(ClusterFeature): void
        {abstract} +resetStatistics(): void
        {abstract} +getWeight(): int
        {abstract} +centroid(int): double
        +doubleValue(int): double
        +longValue(int): long
        {abstract} +variance(): double
        {abstract} +sumdev(): double
        {abstract} +variance(int): double
        {abstract} +covariance(): double[]
        +getCF(): ClusterFeature
    }

    interface "<size:14>AsClusterFeature\n<size:10>elki.index.tree.betula.features" as elki.index.tree.betula.features.AsClusterFeature [[AsClusterFeature.html]] {
        {abstract} +getCF(): ClusterFeature
    }
    interface "<size:14>NumberVector\n<size:10>elki.data" as elki.data.NumberVector [[../../../../data/NumberVector.html]] {
        {abstract} +doubleValue(int): double
        {abstract} +longValue(int): long
        {abstract} +toArray(): double[]
    }
    interface "<size:14>ClusterFeature.Factory\n<size:10>elki.index.tree.betula.features" as elki.index.tree.betula.features.ClusterFeature.Factory<F extends ClusterFeature> [[ClusterFeature.Factory.html]]

    elki.index.tree.betula.features.AsClusterFeature <|-- elki.index.tree.betula.features.ClusterFeature
    elki.data.NumberVector <|-- elki.index.tree.betula.features.ClusterFeature
    elki.index.tree.betula.features.ClusterFeature +-- elki.index.tree.betula.features.ClusterFeature.Factory

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
