@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>VVVFeature.Factory\n<size:10>elki.index.tree.betula.features" as elki.index.tree.betula.features.VVVFeature.Factory [[VVVFeature.Factory.html]] {
        {static} +STATIC: Factory
        +make(int): VVVFeature
    }

    interface "<size:14>ClusterFeature.Factory\n<size:10>elki.index.tree.betula.features" as elki.index.tree.betula.features.ClusterFeature.Factory<VVVFeature> [[ClusterFeature.Factory.html]] {
        {abstract} +make(int): VVVFeature
    }
    class "<size:14>VVVFeature\n<size:10>elki.index.tree.betula.features" as elki.index.tree.betula.features.VVVFeature [[VVVFeature.html]]
    class "<size:14>VVVFeature.Factory.Par\n<size:10>elki.index.tree.betula.features" as elki.index.tree.betula.features.VVVFeature.Factory.Par [[VVVFeature.Factory.Par.html]]

    elki.index.tree.betula.features.ClusterFeature.Factory <|.. elki.index.tree.betula.features.VVVFeature.Factory
    elki.index.tree.betula.features.VVVFeature +-- elki.index.tree.betula.features.VVVFeature.Factory
    elki.index.tree.betula.features.VVVFeature.Factory +-- elki.index.tree.betula.features.VVVFeature.Factory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
