@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DetailView\n<size:10>elki.visualization.gui.detail" as elki.visualization.gui.detail.DetailView [[DetailView.html]] {
        {static} -LOG: Logging
        -item: PlotItem
        ~ratio: double
        ~context: VisualizerContext
        ~taskmap: Map<VisualizationTask, Visualization>
        -width: double
        -height: double
        ~pendingRefresh: AtomicReference<Runnable>
        +DetailView(VisualizerContext, PlotItem, double)
        -addBackground(VisualizerContext): void
        -initialize(): void
        -refresh(): void
        -instantiateVisualization(VisualizationTask): Visualization
        +destroy(): void
        +dispose(): void
        +getRatio(): double
        +setRatio(double): void
        -lazyRefresh(): void
        +resultAdded(Object, Object): void
        +resultChanged(Object): void
        +resultRemoved(Object, Object): void
        +visualizationChanged(VisualizationItem): void
        #redraw(): void
        +getPlotItem(): PlotItem
    }

    class "<size:14>VisualizationPlot\n<size:10>elki.visualization.gui" as elki.visualization.gui.VisualizationPlot [[../VisualizationPlot.html]]
    interface "<size:14>ResultListener\n<size:10>elki.result" as elki.result.ResultListener [[../../../result/ResultListener.html]]
    interface "<size:14>VisualizationListener\n<size:10>elki.visualization" as elki.visualization.VisualizationListener [[../../VisualizationListener.html]] {
        {abstract} +visualizationChanged(VisualizationItem): void
    }

    elki.visualization.gui.VisualizationPlot <|-- elki.visualization.gui.detail.DetailView
    elki.result.ResultListener <|.. elki.visualization.gui.detail.DetailView
    elki.visualization.VisualizationListener <|.. elki.visualization.gui.detail.DetailView

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
