@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>KNNChangeEvent.Type\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.KNNChangeEvent.Type [[KNNChangeEvent.Type.html]] {
        {static} +INSERT
        {static} +DELETE
    }

    class "<size:14>KNNChangeEvent\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.KNNChangeEvent [[KNNChangeEvent.html]]

    elki.index.preprocessed.knn.KNNChangeEvent +-- elki.index.preprocessed.knn.KNNChangeEvent.Type

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
