@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MetricalIndexApproximationMaterializeKNNPreprocessor.Factory\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.MetricalIndexApproximationMaterializeKNNPreprocessor.Factory<O extends NumberVector, N extends Node<E extends MTreeEntry>, E extends MTreeEntry> [[MetricalIndexApproximationMaterializeKNNPreprocessor.Factory.html]] {
        +Factory(int, Distance<? super NumberVector>)
        +instantiate(Relation<O extends NumberVector>): MetricalIndexApproximationMaterializeKNNPreprocessor<O extends NumberVector, N extends Node<E extends MTreeEntry>, E extends MTreeEntry>
    }

    abstract class "<size:14>AbstractMaterializeKNNPreprocessor.Factory\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.AbstractMaterializeKNNPreprocessor.Factory<O extends NumberVector> [[AbstractMaterializeKNNPreprocessor.Factory.html]] {
        {abstract} +instantiate(Relation<O>): AbstractMaterializeKNNPreprocessor<O>
    }
    class "<size:14>MetricalIndexApproximationMaterializeKNNPreprocessor\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.MetricalIndexApproximationMaterializeKNNPreprocessor<O extends NumberVector, N extends Node<E extends MTreeEntry>, E extends MTreeEntry> [[MetricalIndexApproximationMaterializeKNNPreprocessor.html]]
    class "<size:14>MetricalIndexApproximationMaterializeKNNPreprocessor.Factory.Par\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.MetricalIndexApproximationMaterializeKNNPreprocessor.Factory.Par<O extends NumberVector, N extends Node<E extends MTreeEntry>, E extends MTreeEntry> [[MetricalIndexApproximationMaterializeKNNPreprocessor.Factory.Par.html]]

    elki.index.preprocessed.knn.AbstractMaterializeKNNPreprocessor.Factory <|-- elki.index.preprocessed.knn.MetricalIndexApproximationMaterializeKNNPreprocessor.Factory
    elki.index.preprocessed.knn.MetricalIndexApproximationMaterializeKNNPreprocessor +-- elki.index.preprocessed.knn.MetricalIndexApproximationMaterializeKNNPreprocessor.Factory
    elki.index.preprocessed.knn.MetricalIndexApproximationMaterializeKNNPreprocessor.Factory +-- elki.index.preprocessed.knn.MetricalIndexApproximationMaterializeKNNPreprocessor.Factory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
