@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>NNDescent.Factory\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.NNDescent.Factory<O> [[NNDescent.Factory.html]] {
        -rnd: RandomFactory
        -delta: double
        -rho: double
        -noInitialNeighbors: boolean
        -iterations: int
        +Factory(int, Distance<? super O>, RandomFactory, double, double, boolean, int)
        +instantiate(Relation<O>): NNDescent<O>
    }

    abstract class "<size:14>AbstractMaterializeKNNPreprocessor.Factory\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.AbstractMaterializeKNNPreprocessor.Factory<O> [[AbstractMaterializeKNNPreprocessor.Factory.html]] {
        {abstract} +instantiate(Relation<O>): AbstractMaterializeKNNPreprocessor<O>
    }
    class "<size:14>NNDescent\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.NNDescent<O> [[NNDescent.html]]
    class "<size:14>NNDescent.Factory.Par\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.NNDescent.Factory.Par<O>

    elki.index.preprocessed.knn.AbstractMaterializeKNNPreprocessor.Factory <|-- elki.index.preprocessed.knn.NNDescent.Factory
    elki.index.preprocessed.knn.NNDescent +-- elki.index.preprocessed.knn.NNDescent.Factory
    elki.index.preprocessed.knn.NNDescent.Factory +-- elki.index.preprocessed.knn.NNDescent.Factory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
