@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PartitionApproximationMaterializeKNNPreprocessor\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.PartitionApproximationMaterializeKNNPreprocessor<O> [[PartitionApproximationMaterializeKNNPreprocessor.html]] {
        {static} -LOG: Logging
        -partitions: int
        -rnd: RandomFactory
        +PartitionApproximationMaterializeKNNPreprocessor(Relation<O>, Distance<? super O>, int, int, RandomFactory)
        #preprocess(): void
        #getLogger(): Logging
    }

    abstract class "<size:14>AbstractMaterializeKNNPreprocessor\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.AbstractMaterializeKNNPreprocessor<O> [[AbstractMaterializeKNNPreprocessor.html]] {
        {abstract} #preprocess(): void
        {abstract} #getLogger(): Logging
    }
    class "<size:14>PartitionApproximationMaterializeKNNPreprocessor.Factory\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.PartitionApproximationMaterializeKNNPreprocessor.Factory<O> [[PartitionApproximationMaterializeKNNPreprocessor.Factory.html]]

    elki.index.preprocessed.knn.AbstractMaterializeKNNPreprocessor <|-- elki.index.preprocessed.knn.PartitionApproximationMaterializeKNNPreprocessor
    elki.index.preprocessed.knn.PartitionApproximationMaterializeKNNPreprocessor +-- elki.index.preprocessed.knn.PartitionApproximationMaterializeKNNPreprocessor.Factory

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
