@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RandomSampleKNNPreprocessor.Factory.Par\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.RandomSampleKNNPreprocessor.Factory.Par<O> {
        {static} +SHARE_ID: OptionID
        {static} +SEED_ID: OptionID
        -share: double
        -rnd: RandomFactory
        +configure(Parameterization): void
        +make(): Factory<O>
    }

    abstract class "<size:14>AbstractMaterializeKNNPreprocessor.Factory.Par\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.AbstractMaterializeKNNPreprocessor.Factory.Par<O> {
        {abstract} +make(): Factory<O>
    }
    class "<size:14>RandomSampleKNNPreprocessor.Factory\n<size:10>elki.index.preprocessed.knn" as elki.index.preprocessed.knn.RandomSampleKNNPreprocessor.Factory<O> [[RandomSampleKNNPreprocessor.Factory.html]]

    elki.index.preprocessed.knn.AbstractMaterializeKNNPreprocessor.Factory.Par <|-- elki.index.preprocessed.knn.RandomSampleKNNPreprocessor.Factory.Par
    elki.index.preprocessed.knn.RandomSampleKNNPreprocessor.Factory +-- elki.index.preprocessed.knn.RandomSampleKNNPreprocessor.Factory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
