@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>KullbackLeiblerDivergenceAsymmetricDistance.Par\n<size:10>elki.distance.probabilistic" as elki.distance.probabilistic.KullbackLeiblerDivergenceAsymmetricDistance.Par [[KullbackLeiblerDivergenceAsymmetricDistance.Par.html]] {
        +make(): KullbackLeiblerDivergenceAsymmetricDistance
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>KullbackLeiblerDivergenceAsymmetricDistance\n<size:10>elki.distance.probabilistic" as elki.distance.probabilistic.KullbackLeiblerDivergenceAsymmetricDistance [[KullbackLeiblerDivergenceAsymmetricDistance.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.distance.probabilistic.KullbackLeiblerDivergenceAsymmetricDistance.Par
    elki.distance.probabilistic.KullbackLeiblerDivergenceAsymmetricDistance +-- elki.distance.probabilistic.KullbackLeiblerDivergenceAsymmetricDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
