@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>Relation\n<size:10>elki.database.relation" as elki.database.relation.Relation<O> [[Relation.html]] {
        {abstract} +get(DBIDRef): O
        {abstract} +getDataTypeInformation(): SimpleTypeInformation<O>
        {abstract} +getDBIDs(): DBIDs
        {abstract} +iterDBIDs(): DBIDIter
        {abstract} +size(): int
        {abstract} +getLongName(): String
        +forEach(BiConsumer<? super DBIDRef, ? super O>): void
    }

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
