@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>BetulaDiagonalGaussianModelFactory\n<size:10>elki.clustering.em.models" as elki.clustering.em.models.BetulaDiagonalGaussianModelFactory [[BetulaDiagonalGaussianModelFactory.html]] {
        #initializer: AbstractCFKMeansInitialization
        +BetulaDiagonalGaussianModelFactory(AbstractCFKMeansInitialization)
        +buildInitialModels(List<? extends ClusterFeature>, int, CFTree<?>): List<DiagonalGaussianModel>
    }

    interface "<size:14>BetulaClusterModelFactory\n<size:10>elki.clustering.em.models" as elki.clustering.em.models.BetulaClusterModelFactory<DiagonalGaussianModel> [[BetulaClusterModelFactory.html]] {
        {abstract} +buildInitialModels(List<? extends ClusterFeature>, int, CFTree<?>): List<M extends BetulaClusterModel>
    }
    class "<size:14>BetulaDiagonalGaussianModelFactory.Par\n<size:10>elki.clustering.em.models" as elki.clustering.em.models.BetulaDiagonalGaussianModelFactory.Par [[BetulaDiagonalGaussianModelFactory.Par.html]]

    elki.clustering.em.models.BetulaClusterModelFactory <|.. elki.clustering.em.models.BetulaDiagonalGaussianModelFactory
    elki.clustering.em.models.BetulaDiagonalGaussianModelFactory +-- elki.clustering.em.models.BetulaDiagonalGaussianModelFactory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
