@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>TextbookMultivariateGaussianModelFactory.Par\n<size:10>elki.clustering.em.models" as elki.clustering.em.models.TextbookMultivariateGaussianModelFactory.Par {
        #initializer: KMeansInitialization
        +configure(Parameterization): void
        +make(): TextbookMultivariateGaussianModelFactory
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>TextbookMultivariateGaussianModelFactory\n<size:10>elki.clustering.em.models" as elki.clustering.em.models.TextbookMultivariateGaussianModelFactory [[TextbookMultivariateGaussianModelFactory.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.clustering.em.models.TextbookMultivariateGaussianModelFactory.Par
    elki.clustering.em.models.TextbookMultivariateGaussianModelFactory +-- elki.clustering.em.models.TextbookMultivariateGaussianModelFactory.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
