@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ParallelKNNWeightOutlier.Par\n<size:10>elki.outlier.distance.parallel" as elki.outlier.distance.parallel.ParallelKNNWeightOutlier.Par<O> {
        #distance: Distance<? super O>
        #k: int
        +configure(Parameterization): void
        +make(): ParallelKNNWeightOutlier<O>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>ParallelKNNWeightOutlier\n<size:10>elki.outlier.distance.parallel" as elki.outlier.distance.parallel.ParallelKNNWeightOutlier<O> [[ParallelKNNWeightOutlier.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.outlier.distance.parallel.ParallelKNNWeightOutlier.Par
    elki.outlier.distance.parallel.ParallelKNNWeightOutlier +-- elki.outlier.distance.parallel.ParallelKNNWeightOutlier.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
