@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ParallelKNNOutlier.Par\n<size:10>elki.outlier.distance.parallel" as elki.outlier.distance.parallel.ParallelKNNOutlier.Par<O> {
        #distance: Distance<? super O>
        #k: int
        +configure(Parameterization): void
        +make(): ParallelKNNOutlier<O>
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>ParallelKNNOutlier\n<size:10>elki.outlier.distance.parallel" as elki.outlier.distance.parallel.ParallelKNNOutlier<O> [[ParallelKNNOutlier.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.outlier.distance.parallel.ParallelKNNOutlier.Par
    elki.outlier.distance.parallel.ParallelKNNOutlier +-- elki.outlier.distance.parallel.ParallelKNNOutlier.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
