@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LPIntegerNormDistance.Par\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.LPIntegerNormDistance.Par [[LPIntegerNormDistance.Par.html]] {
        #p: int
        +configure(Parameterization): void
        +make(): LPIntegerNormDistance
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>LPIntegerNormDistance\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.LPIntegerNormDistance [[LPIntegerNormDistance.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.distance.minkowski.LPIntegerNormDistance.Par
    elki.distance.minkowski.LPIntegerNormDistance +-- elki.distance.minkowski.LPIntegerNormDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
