@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SparseManhattanDistance\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.SparseManhattanDistance [[SparseManhattanDistance.html]] {
        {static} +STATIC: SparseManhattanDistance
        +distance(SparseNumberVector, SparseNumberVector): double
        +norm(SparseNumberVector): double
    }

    class "<size:14>SparseLPNormDistance\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.SparseLPNormDistance [[SparseLPNormDistance.html]]
    class "<size:14>SparseManhattanDistance.Par\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.SparseManhattanDistance.Par [[SparseManhattanDistance.Par.html]]

    elki.distance.minkowski.SparseLPNormDistance <|-- elki.distance.minkowski.SparseManhattanDistance
    elki.distance.minkowski.SparseManhattanDistance +-- elki.distance.minkowski.SparseManhattanDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
