@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>WeightedSquaredEuclideanDistance\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.WeightedSquaredEuclideanDistance [[WeightedSquaredEuclideanDistance.html]] {
        #weights: double[]
        +WeightedSquaredEuclideanDistance(double[])
        +distance(NumberVector, NumberVector): double
        +norm(NumberVector): double
        +minDist(SpatialComparable, SpatialComparable): double
        +isSquared(): boolean
    }

    abstract class "<size:14>AbstractNumberVectorDistance\n<size:10>elki.distance" as elki.distance.AbstractNumberVectorDistance [[../AbstractNumberVectorDistance.html]]
    interface "<size:14>SpatialPrimitiveDistance\n<size:10>elki.distance" as elki.distance.SpatialPrimitiveDistance<NumberVector> [[../SpatialPrimitiveDistance.html]] {
        {abstract} +minDist(SpatialComparable, SpatialComparable): double
    }
    interface "<size:14>WeightedNumberVectorDistance\n<size:10>elki.distance" as elki.distance.WeightedNumberVectorDistance<NumberVector> [[../WeightedNumberVectorDistance.html]]
    interface "<size:14>Norm\n<size:10>elki.distance" as elki.distance.Norm<NumberVector> [[../Norm.html]] {
        {abstract} +norm(NumberVector): double
    }
    class "<size:14>WeightedSquaredEuclideanDistance.Par\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.WeightedSquaredEuclideanDistance.Par [[WeightedSquaredEuclideanDistance.Par.html]]

    elki.distance.AbstractNumberVectorDistance <|-- elki.distance.minkowski.WeightedSquaredEuclideanDistance
    elki.distance.SpatialPrimitiveDistance <|.. elki.distance.minkowski.WeightedSquaredEuclideanDistance
    elki.distance.WeightedNumberVectorDistance <|.. elki.distance.minkowski.WeightedSquaredEuclideanDistance
    elki.distance.Norm <|.. elki.distance.minkowski.WeightedSquaredEuclideanDistance
    elki.distance.minkowski.WeightedSquaredEuclideanDistance +-- elki.distance.minkowski.WeightedSquaredEuclideanDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
