@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>WeightedSquaredEuclideanDistance.Par\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.WeightedSquaredEuclideanDistance.Par [[WeightedSquaredEuclideanDistance.Par.html]] {
        #weights: double[]
        +configure(Parameterization): void
        +make(): WeightedSquaredEuclideanDistance
    }

    interface "<size:14>Parameterizer\n<size:10>elki.utilities.optionhandling" as elki.utilities.optionhandling.Parameterizer [[../../utilities/optionhandling/Parameterizer.html]] {
        {abstract} +make(): Object
    }
    class "<size:14>WeightedSquaredEuclideanDistance\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.WeightedSquaredEuclideanDistance [[WeightedSquaredEuclideanDistance.html]]

    elki.utilities.optionhandling.Parameterizer <|.. elki.distance.minkowski.WeightedSquaredEuclideanDistance.Par
    elki.distance.minkowski.WeightedSquaredEuclideanDistance +-- elki.distance.minkowski.WeightedSquaredEuclideanDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
