@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>WeightedMaximumDistance\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.WeightedMaximumDistance [[WeightedMaximumDistance.html]] {
        +WeightedMaximumDistance(double[])
        -preDistance(NumberVector, NumberVector, int, int): double
        -preDistanceVM(NumberVector, SpatialComparable, int, int): double
        -preDistanceMBR(SpatialComparable, SpatialComparable, int, int): double
        -preNorm(NumberVector, int, int): double
        -preNormMBR(SpatialComparable, int, int): double
        +distance(NumberVector, NumberVector): double
        +norm(NumberVector): double
        +minDist(SpatialComparable, SpatialComparable): double
    }

    class "<size:14>WeightedLPNormDistance\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.WeightedLPNormDistance [[WeightedLPNormDistance.html]]
    class "<size:14>WeightedMaximumDistance.Par\n<size:10>elki.distance.minkowski" as elki.distance.minkowski.WeightedMaximumDistance.Par [[WeightedMaximumDistance.Par.html]]

    elki.distance.minkowski.WeightedLPNormDistance <|-- elki.distance.minkowski.WeightedMaximumDistance
    elki.distance.minkowski.WeightedMaximumDistance +-- elki.distance.minkowski.WeightedMaximumDistance.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
