@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CTLuMedianAlgorithm\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.CTLuMedianAlgorithm<N> [[CTLuMedianAlgorithm.html]] {
        +CTLuMedianAlgorithm(Factory<N>)
        +getInputTypeRestriction(): TypeInformation[]
        +run(Database, Relation<N>, Relation<? extends NumberVector>): OutlierResult
    }

    abstract class "<size:14>AbstractNeighborhoodOutlier\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.AbstractNeighborhoodOutlier<N> [[AbstractNeighborhoodOutlier.html]]
    class "<size:14>CTLuMedianAlgorithm.Par\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.CTLuMedianAlgorithm.Par<N>

    elki.outlier.spatial.AbstractNeighborhoodOutlier <|-- elki.outlier.spatial.CTLuMedianAlgorithm
    elki.outlier.spatial.CTLuMedianAlgorithm +-- elki.outlier.spatial.CTLuMedianAlgorithm.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
