@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CTLuMeanMultipleAttributes\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.CTLuMeanMultipleAttributes<N, O extends NumberVector> [[CTLuMeanMultipleAttributes.html]] {
        {static} -LOG: Logging
        +CTLuMeanMultipleAttributes(Factory<N>)
        +getInputTypeRestriction(): TypeInformation[]
        +run(Database, Relation<N>, Relation<O extends NumberVector>): OutlierResult
    }

    abstract class "<size:14>AbstractNeighborhoodOutlier\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.AbstractNeighborhoodOutlier<N> [[AbstractNeighborhoodOutlier.html]]
    class "<size:14>CTLuMeanMultipleAttributes.Par\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.CTLuMeanMultipleAttributes.Par<N, O extends NumberVector>

    elki.outlier.spatial.AbstractNeighborhoodOutlier <|-- elki.outlier.spatial.CTLuMeanMultipleAttributes
    elki.outlier.spatial.CTLuMeanMultipleAttributes +-- elki.outlier.spatial.CTLuMeanMultipleAttributes.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
