@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CTLuGLSBackwardSearchAlgorithm\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.CTLuGLSBackwardSearchAlgorithm<V extends NumberVector> [[CTLuGLSBackwardSearchAlgorithm.html]] {
        #distance: Distance<? super NumberVector>
        #alpha: double
        #k: int
        +CTLuGLSBackwardSearchAlgorithm(Distance<? super NumberVector>, int, double)
        +getInputTypeRestriction(): TypeInformation[]
        +run(Relation<V extends NumberVector>, Relation<? extends NumberVector>): OutlierResult
        -singleIteration(Relation<V extends NumberVector>, Relation<? extends NumberVector>): Pair<DBIDVar, Double>
    }

    interface "<size:14>OutlierAlgorithm\n<size:10>elki.outlier" as elki.outlier.OutlierAlgorithm [[../OutlierAlgorithm.html]]
    class "<size:14>CTLuGLSBackwardSearchAlgorithm.Par\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.CTLuGLSBackwardSearchAlgorithm.Par<V extends NumberVector>

    elki.outlier.OutlierAlgorithm <|.. elki.outlier.spatial.CTLuGLSBackwardSearchAlgorithm
    elki.outlier.spatial.CTLuGLSBackwardSearchAlgorithm +-- elki.outlier.spatial.CTLuGLSBackwardSearchAlgorithm.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
