@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SOF.Par\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.SOF.Par<N, O> {
        +make(): SOF<N, O>
    }

    abstract class "<size:14>AbstractDistanceBasedSpatialOutlier.Par\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.AbstractDistanceBasedSpatialOutlier.Par<N, O>
    class "<size:14>SOF\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.SOF<N, O> [[SOF.html]]

    elki.outlier.spatial.AbstractDistanceBasedSpatialOutlier.Par <|-- elki.outlier.spatial.SOF.Par
    elki.outlier.spatial.SOF +-- elki.outlier.spatial.SOF.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
