@startuml
    remove .*\.(Instance|Par|Parameterizer|Factory)$
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>TrimmedMeanApproach\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.TrimmedMeanApproach<N> [[TrimmedMeanApproach.html]] {
        {static} -LOG: Logging
        -p: double
        +TrimmedMeanApproach(Factory<N>, double)
        +getInputTypeRestriction(): TypeInformation[]
        +run(Database, Relation<N>, Relation<? extends NumberVector>): OutlierResult
    }

    abstract class "<size:14>AbstractNeighborhoodOutlier\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.AbstractNeighborhoodOutlier<N> [[AbstractNeighborhoodOutlier.html]]
    class "<size:14>TrimmedMeanApproach.Par\n<size:10>elki.outlier.spatial" as elki.outlier.spatial.TrimmedMeanApproach.Par<N>

    elki.outlier.spatial.AbstractNeighborhoodOutlier <|-- elki.outlier.spatial.TrimmedMeanApproach
    elki.outlier.spatial.TrimmedMeanApproach +-- elki.outlier.spatial.TrimmedMeanApproach.Par

    center footer UMLDoclet 2.0.19, PlantUML 1.2022.8
@enduml
